#!/usr/bin/env python3
"""
generate_task_checklist.py -- Owner directive 2026-07-20: "make a prompt
for your self use... which have the list of files, process and
instructions that needs to be updated by you or superboss for every task.
Make it via script so that software does it."

Software-generated, not hand-typed: the FILE PATHS below are pulled live
from MASTER_INDEX.yaml's own registries (so if a path ever changes,
regenerating this checklist auto-updates it instead of silently going
stale) -- only the PROCEDURAL STEPS (the order of operations) are fixed
text, because a workflow sequence isn't the kind of thing that's
"in" the data to extract; it's this session's own accumulated, real
operating discipline, written down once here.

Run: python3 generate_task_checklist.py MASTER_INDEX.yaml
Prints the self_use_task_checklist YAML block to stdout -- paste it back
into MASTER_INDEX.yaml (same review-before-splice discipline as
generate_quick_reference.py).
"""
import sys
import yaml


def get_path(registries, reg_id, field="path"):
    for r in registries:
        if r.get("id") == reg_id:
            val = r.get(field)
            if isinstance(val, str):
                return val
    return f"UNKNOWN (registries.{reg_id}.{field} not found -- regenerate this checklist)"


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "MASTER_INDEX.yaml"
    with open(path, encoding="utf-8") as f:
        doc = yaml.safe_load(f)
    registries = doc.get("registries", [])

    checklist = {
        "self_use_task_checklist": {
            "purpose": (
                "The one prompt this session (or superboss) reads before "
                "and after every task, regardless of size. Generated by "
                "ai-os/scripts/generate_task_checklist.py -- re-run after "
                "any registries: edit that changes one of the paths below, "
                "do not hand-edit this block."
            ),
            "before_starting_any_task": [
                f"Check {get_path(registries, 'system_index')} via superboss-register.py check-duplicate <term> -- does this already exist?",
                "Scan MASTER_INDEX.yaml quick_reference (top of this file) for a matching id before reading the full registries: section.",
                f"If touching the ops-layer worker fleet: read {get_path(registries, 'system_sync_mechanism')}'s own header before extending it -- do not build a parallel mechanism (registries.system_sync_mechanism.do_not_build_a_new_sync_script).",
                f"If touching AI dispatch/routing: read {get_path(registries, 'constitution')} control_model + the AI router migration inventory (registries.ai_router_migration_inventory_2026_07_20) before assuming a call site is unmigrated by oversight vs. deliberate deferral.",
                "Check the credit-spend governance gate (registries.credit_spend_governance) BEFORE any AI-costing action -- see that entry's own rule: no AI call without an approved plan.",
            ],
            "while_working": [
                "Prefer a deterministic script/package over an AI call wherever one exists -- see registries.credit_spend_governance's own 'software first, AI second' rule.",
                "Test before trusting: typecheck/lint/unit-test any app-layer (compliance-tracker/projexa) change; syntax-check + isolated function test any ops-layer script change; re-run the exact command CI runs when fixing a CI-only failure (do not assume a local pass means CI passes).",
                "Verify claims against real state before recording them -- this session's own repeated pattern of catching its own false claims (e.g. registries.ops_task_sync_bridge.correction_2026_07_20) exists specifically because a plausible-sounding claim is not the same as a verified one.",
            ],
            "after_finishing_any_task": [
                f"Register new/changed scripts in system_index (superboss-register.py index-add) -- {get_path(registries, 'system_index')}.",
                f"Add or update the relevant entry under {path}'s registries: section (id/status/path/scope schema, see the file's own HOW TO USE section).",
                f"Regenerate quick_reference via {get_path(registries, 'system_diagram').rsplit('/', 1)[0]}/generate_quick_reference.py {path} and splice the output back in.",
                f"Mirror any new/changed /opt/veridian/scripts/*.py|sh file into the repo copy (compliance-tracker/ai-os/scripts/) -- or just run {get_path(registries, 'system_sync_mechanism')} --check mirror, which does this automatically.",
                "Deploy the live MASTER_INDEX.yaml copy to BOTH canonical paths (live + repo mirror) and validate with yaml.safe_load on both before trusting either.",
                "Commit with a message that explains WHY, not just WHAT -- and if opening a PR, post the 8-field structured AUDIT: PASS/FAIL comment this repo's CI requires (audit-protocol.ts's AuditProtocolFields) before expecting audit-check to pass.",
                "If the task was part of an Owner directive with an explicit 3-round-audit requirement: do NOT skip it -- round 1 re-verifies claims, round 2 looks for edge cases a surface check would miss, round 3 compiles an honest gap list rather than a zero-gap claim.",
            ],
            "credit_spend_reminder": (
                "Every AI-costing action this checklist's 'while_working' "
                "step above refers to is gated by registries."
                "credit_spend_governance -- see that entry for the full "
                "mechanism. This checklist does not duplicate that gate's "
                "own rules, only points to it."
            ),
        }
    }

    print(yaml.safe_dump(checklist, default_flow_style=False, sort_keys=False, allow_unicode=True, width=100), end="")


if __name__ == "__main__":
    main()
