// Priority 15 Wave 2 (PROJEXA HR & Payroll follow-up): real per-employee
// payslip PDF -- the module previously only shipped a client-side CSV
// register export (PayrollClient.tsx's exportRegisterCsv()), no per-payslip
// document. Uses erp-payroll-service.ts's getPayslipDetail() for the data
// and src/lib/pdf-generator.ts's shared jsPDF helpers for rendering -- see
// that file's header for why it's factored out generically rather than
// built one-off here.
import { NextRequest, NextResponse } from "next/server"
import { requireAuthOrApiKey } from "@/lib/supabase/auth-guard"
import { getPayslipDetail, ServiceError } from "@/lib/services/erp-payroll-service"
import { createBrandedDocument, drawDocumentHeader, drawSectionLabel, drawFooterNote, pdfToBuffer, autoTable } from "@/lib/pdf-generator"

type RouteContext = { params: Promise<{ id: string }> }

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

export async function GET(request: NextRequest, { params }: RouteContext) {
  const ctx = await requireAuthOrApiKey(request)
  if (ctx.response) return ctx.response
  if (!ctx.orgId) return NextResponse.json({ error: "No organisation on this account" }, { status: 400 })

  try {
    const { id } = await params
    const detail = await getPayslipDetail({ orgId: ctx.orgId }, id)
    const { payslip, run, org, employeeName, employeeCode, jobTitle } = detail

    const periodLabel = run ? `${MONTHS[run.month - 1]} ${run.year}` : "—"

    const doc = createBrandedDocument()
    let y = drawDocumentHeader(doc, {
      orgName: org.name,
      orgAddress: org.address,
      orgGstin: org.gstin,
      documentTitle: "Payslip",
      documentSubtitle: periodLabel,
    })

    y += 20
    drawSectionLabel(doc, "Employee", 32, y)
    y += 16
    doc.setFontSize(11)
    doc.setFont("helvetica", "bold")
    doc.text(employeeName, 32, y)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    y += 14
    if (employeeCode) { doc.text(`Employee Code: ${employeeCode}`, 32, y); y += 13 }
    if (jobTitle) { doc.text(`Designation: ${jobTitle}`, 32, y); y += 13 }
    doc.text(`Pay Period: ${periodLabel}`, 32, y)
    y += 13
    doc.text(`Payslip Status: ${payslip.status === "finalized" ? "Finalized" : "Draft"}`, 32, y)
    y += 24

    const earningLines = payslip.lines.filter((l) => l.lineType === "earning")
    const deductionLines = payslip.lines.filter((l) => l.lineType === "deduction")

    drawSectionLabel(doc, "Earnings", 32, y)
    y += 8
    autoTable(doc, {
      startY: y,
      head: [["Component", "Amount"]],
      body: earningLines.length
        ? earningLines.map((l) => [l.label, Number(l.amount).toLocaleString("en-IN", { minimumFractionDigits: 2 })])
        : [["—", "0.00"]],
      foot: [["Gross Earnings", Number(payslip.grossEarnings).toLocaleString("en-IN", { minimumFractionDigits: 2 })]],
      theme: "grid",
      styles: { fontSize: 9, cellPadding: 6 },
      headStyles: { fillColor: "#1C2B3A", textColor: "#FFFFFF" },
      footStyles: { fillColor: "#f3f4f6", textColor: "#1C2B3A", fontStyle: "bold" },
      columnStyles: { 1: { halign: "right" } },
      margin: { left: 32, right: 32 },
    })

    y = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 60) + 20

    drawSectionLabel(doc, "Deductions", 32, y)
    y += 8
    autoTable(doc, {
      startY: y,
      head: [["Component", "Amount"]],
      body: deductionLines.length
        ? deductionLines.map((l) => [l.label, Number(l.amount).toLocaleString("en-IN", { minimumFractionDigits: 2 })])
        : [["—", "0.00"]],
      foot: [["Total Deductions", Number(payslip.totalDeductions).toLocaleString("en-IN", { minimumFractionDigits: 2 })]],
      theme: "grid",
      styles: { fontSize: 9, cellPadding: 6 },
      headStyles: { fillColor: "#1C2B3A", textColor: "#FFFFFF" },
      footStyles: { fillColor: "#f3f4f6", textColor: "#1C2B3A", fontStyle: "bold" },
      columnStyles: { 1: { halign: "right" } },
      margin: { left: 32, right: 32 },
    })

    y = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 60) + 24

    doc.setFillColor("#0E7C6E")
    doc.rect(32, y, doc.internal.pageSize.getWidth() - 64, 32, "F")
    doc.setTextColor("#FFFFFF")
    doc.setFontSize(12)
    doc.setFont("helvetica", "bold")
    doc.text("Net Pay", 44, y + 21)
    doc.text(
      Number(payslip.netPay).toLocaleString("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 }),
      doc.internal.pageSize.getWidth() - 44,
      y + 21,
      { align: "right" }
    )
    doc.setTextColor("#1C2B3A")

    drawFooterNote(doc, `Generated by VERIDIAN AI · System-generated payslip · Payslip ID: ${payslip.id}`)

    const buffer = pdfToBuffer(doc)
    const filename = `payslip-${employeeCode ?? employeeName.replace(/\s+/g, "-")}-${run ? `${run.year}-${String(run.month).padStart(2, "0")}` : payslip.id}.pdf`

    // Wrapped in a Blob rather than passed as a raw Uint8Array/Buffer --
    // NextResponse's BodyInit type doesn't line up with the
    // Uint8Array<ArrayBufferLike> generic this TS config produces from
    // jsPDF's arraybuffer output, but Blob is unambiguously a valid
    // BodyInit and is the standard way to hand binary bytes to a Response.
    return new NextResponse(new Blob([buffer], { type: "application/pdf" }), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    if (error instanceof ServiceError) return NextResponse.json({ error: error.message }, { status: error.status })
    console.error("v1 projexa payslip PDF error:", error)
    return NextResponse.json({ error: "Failed to generate payslip PDF" }, { status: 500 })
  }
}
