// LIVE push check of the PROJEXA local-first sync: an edit a laptop pushed is really executed and lands in the database, exactly once.
//
// What runs for real: the Edge handler (supabase/functions/projexa-sync/handler.ts) AND the exec pipeline (supabase/functions/ai-work-link-exec: handler +
// the generated app.bundle.mjs, i.e. the same code the deployed function runs) in THIS process, over the LIVE database: the ledger claim/finish functions
// through the Management API, the business write through APP_RUNTIME_DATABASE_URL (the role the deployed function uses). Only two things are stand-ins:
// the session check (`tok:<sub>`, no password or token is handled) and the HTTP hop between the two functions (an in-process fetch with a throwaway secret).
//
// It WRITES, once, on the E2E fixture organisation ("Meridian Construction Group (E2E)"): one task title is changed and restored. Everything is restored in
// a `finally`. Nothing prints a token, a sign-in id, an e-mail address, a connection string or a row's data (only counts, versions and statuses).
//   bun scripts/verify/projexa-sync-live-push-check.ts
// Needs: supabase/functions/ai-work-link-exec/app.bundle.mjs (bun scripts/build-ai-work-link-exec.ts), SUPABASE_ACCESS_TOKEN and APP_RUNTIME_DATABASE_URL (C:/ct/ct/.env.local).
import { readFileSync, existsSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { randomUUID } from "node:crypto"
import { handleSync, RateLimiter, createExecRun, createExecRunBatch, type Rpc, type RpcResult } from "../../supabase/functions/projexa-sync/handler"
import { handleExec, claimSyncOp } from "../../supabase/functions/ai-work-link-exec/handler"
import type { SessionVerifier } from "../../supabase/functions/ai-work-link/session"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const PROJECT = process.env.SUPABASE_PROJECT_REF || "pcrjmlpuqsbocqfwoxod"
const A_ORG = "4ecc472f-4152-4310-ae8d-cf8b7c52ab6d" // Meridian Construction Group (E2E)
const B_ORG = "1850e900-6b54-4108-b01c-cc42c00f3eb9" // R74-TEST-Tenant-B

function envValue(name: string): string {
  if (process.env[name]) return process.env[name]!
  for (const p of ["C:/ct/ct/.env.local", join(ROOT, ".env.local")]) {
    if (!existsSync(p)) continue
    const m = readFileSync(p, "utf8").match(new RegExp(`^${name}=(.*)$`, "m"))
    if (m) return m[1].trim().replace(/^["']|["']$/g, "")
  }
  throw new Error(`${name} is not set (environment or .env.local)`)
}
const TOKEN = envValue("SUPABASE_ACCESS_TOKEN")
process.env.APP_RUNTIME_DATABASE_URL = envValue("APP_RUNTIME_DATABASE_URL") // read by the pipeline; never printed

async function sqlText(query: string): Promise<{ ok: boolean; text: string }> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const res = await fetch(`https://api.supabase.com/v1/projects/${PROJECT}/database/query`, {
      method: "POST",
      headers: { Authorization: `Bearer ${TOKEN}`, "Content-Type": "application/json" },
      body: JSON.stringify({ query }),
      signal: AbortSignal.timeout(120_000),
    })
    const text = await res.text()
    if (res.status === 429 || res.status >= 500) {
      await new Promise((r) => setTimeout(r, 1500 * (attempt + 1)))
      continue
    }
    return { ok: res.ok, text }
  }
  throw new Error("Management API stayed unavailable")
}
async function sql(query: string): Promise<any[]> {
  const r = await sqlText(query)
  if (!r.ok) throw new Error(r.text.slice(0, 500))
  return JSON.parse(r.text)
}
const lit = (v: unknown): string => {
  if (v === null || v === undefined) return "null"
  if (typeof v === "number") return String(v)
  if (typeof v === "boolean") return v ? "true" : "false"
  if (Array.isArray(v)) return `array[${v.map(lit).join(",")}]::text[]`
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}
const rpc: Rpc = async (name, args = {}): Promise<RpcResult> => {
  const keys = Object.keys(args)
  const r = await sqlText(`select public.${name}(${keys.map((k) => `${k} => ${lit(args[k])}`).join(", ")}) as r`)
  if (r.ok) return { data: (JSON.parse(r.text) as Array<{ r: unknown }>)[0]?.r ?? null, error: null }
  const m = r.text.match(/ERROR:\s+(\w+):\s+([^\n"\\]*)/)
  return { data: null, error: { message: m ? m[2].trim() : r.text.slice(0, 200), code: m?.[1] } }
}

// the real exec pipeline, in process
// @ts-ignore generated by scripts/build-ai-work-link-exec.ts (git-ignored)
const bundle = await import("../../supabase/functions/ai-work-link-exec/app.bundle.mjs")
const LOCAL_SECRET = `live-check-${randomUUID()}` // a throwaway shared secret between the two in-process functions
const execDeps = {
  rpc: rpc as any,
  secret: LOCAL_SECRET,
  syncSecret: LOCAL_SECRET,
  syncClaim: (op: any) => claimSyncOp(rpc as any, op),
  dbConfigured: true,
  run: bundle.runLinkIntent,
  read: bundle.runLinkRead,
  syncRun: bundle.runSyncOp,
  health: bundle.linkExecHealth,
  log: () => {},
}
const inProcessExec: typeof fetch = (async (url: any, init: any) => handleExec(new Request(String(url), init), execDeps as any)) as any
const execOptions = { url: "http://exec.local", secret: LOCAL_SECRET, fetchImpl: inProcessExec }

const session: SessionVerifier = async (t) => (t.startsWith("tok:") ? { ok: true, sub: t.slice(4), email: null, issuer: "live-check", iat: null } : { ok: false, reason: "invalid" })
const limiter = new RateLimiter(1_000_000)
type J = Record<string, any>
async function hit(sub: string, path: string, body?: unknown): Promise<{ status: number; json: J }> {
  const req = new Request(`https://x.supabase.co/functions/v1/projexa-sync/${path}`, {
    method: body === undefined ? "GET" : "POST",
    headers: { authorization: `Bearer tok:${sub}`, "x-px-client": "live-check; protocol=2; schema=3" },
    body: body === undefined ? undefined : JSON.stringify(body),
  })
  const res = await handleSync(req, { rpc, session, limiter, execRun: createExecRun(execOptions), execRunBatch: createExecRunBatch(execOptions) })
  let json: J = {}
  try {
    json = (await res.json()) as J
  } catch {
    /* empty */
  }
  return { status: res.status, json }
}

const results: Array<{ ok: boolean; name: string }> = []
function check(ok: boolean, name: string, note?: string) {
  results.push({ ok, name })
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${note ? `   (${note})` : ""}`)
}
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

async function main() {
  const subOf = async (org: string, role: string) => (await sql(`select auth_user_id::text as sub from compliance.users where org_id = ${lit(org)} and role = ${lit(role)} and auth_user_id is not null order by id limit 1`))[0]?.sub as string | undefined
  const member = await subOf(A_ORG, "member")
  const viewer = await subOf(A_ORG, "client_viewer")
  const outsider = await subOf(B_ORG, "admin")
  if (!member || !viewer || !outsider) throw new Error("the fixture people were not found")

  // a real task the member can read, with its current version and title
  const projects = (await sql(`select id from compliance.projects where org_id = ${lit(A_ORG)} order by id`)).map((r) => String(r.id))
  let projectId = ""
  let task: J | undefined
  for (const p of projects) {
    const r = await hit(member, "pull", { project_id: p, kind: "tasks", after: null, limit: 5 })
    const it = (r.json.items as J[] | undefined)?.find((i) => i.data && typeof i.data.title === "string")
    if (r.status === 200 && it) {
      projectId = p
      task = it
      break
    }
  }
  if (!task) throw new Error("no readable task found in the fixture organisation")
  const taskId = String(task.id)
  const version0 = Number(task.version)
  const title0 = String(task.data.title)
  const dbTitle = async () => String((await sql(`select title from compliance.pms_issues where id = ${lit(taskId)} and org_id = ${lit(A_ORG)}`))[0]?.title)
  check((await dbTitle()) === title0, "setup: the task the laptop sees is the task in the database", `version ${version0}`)

  const push = (sub: string, ops: J[], device = "live-device-push-0001") => hit(sub, "push", { device_id: device, ops })
  const mkOp = (title: string, baseVersion: number, opId = randomUUID(), project = projectId) => ({ op_id: opId, function_id: "update_task", project_id: project, params: { projectId: project, issueId: taskId, title }, record: { kind: "tasks", id: taskId, base_version: baseVersion } })

  let version1 = version0
  try {
    // 1. the edit is pushed and really lands
    const op1 = mkOp(`${title0} (live push check)`, version0)
    const r1 = await push(member, [op1])
    const res1: J = r1.json.results?.[0] ?? {}
    console.log("  info: first push ->", r1.status, JSON.stringify(r1.json).slice(0, 700))
    check(r1.status === 200 && /applied|ok/i.test(String(res1.status)), "1  a pushed edit is executed by the real pipeline (applied)", `status ${r1.status}/${res1.status}`)
    check((await dbTitle()) === `${title0} (live push check)`, "1  and it is really in the database")
    version1 = Number(res1.version ?? 0) || version0 + 1
    check(version1 === version0 + 1, "1  the record's version went up by one", `${version0} -> ${version1}`)

    // 2. the same op again: exactly once
    const r2 = await push(member, [op1])
    const res2: J = r2.json.results?.[0] ?? {}
    check(/duplicate/i.test(String(res2.status ?? res2.action)) || res2.duplicate === true, "2  the SAME op pushed again is a duplicate (the stored result comes back, nothing runs twice)", JSON.stringify({ status: res2.status, action: res2.action }).slice(0, 100))
    check((await dbTitle()) === `${title0} (live push check)`, "2  the database is unchanged by the replay")

    // 3. a stale edit (based on the old version) is not silently written over the newer one
    const r3 = await push(member, [mkOp(`${title0} (stale edit)`, version0)], "live-device-push-0002")
    const res3: J = r3.json.results?.[0] ?? {}
    console.log("  info: stale push ->", r3.status, JSON.stringify({ status: res3.status, code: res3.code, action: res3.action }))
    const titleAfterStale = await dbTitle()
    check(titleAfterStale !== `${title0} (stale edit)` || /merge|applied/i.test(String(res3.status)), "3  a stale edit is merged or reported as a conflict, never a silent overwrite", `status ${res3.status}`)

    // 4. a viewer cannot write; a person of another organisation cannot reach the project
    const r4 = await push(viewer, [mkOp("viewer must not write", version1)], "live-device-push-0003")
    const res4: J = r4.json.results?.[0] ?? {}
    check(/reject|refus/i.test(String(res4.status ?? res4.action)) || res4.code === "ROLE_TOO_LOW", "4  a viewer's pushed edit is rejected", JSON.stringify({ status: res4.status, code: res4.code }))
    const r5 = await push(outsider, [mkOp("outsider must not write", version1)], "live-device-push-0004")
    const res5: J = r5.json.results?.[0] ?? {}
    check(/reject|refus/i.test(String(res5.status ?? res5.action)) || res5.code === "PROJECT_NOT_READABLE", "4  a person of another organisation's pushed edit is rejected", JSON.stringify({ status: res5.status, code: res5.code }))
    const t = await dbTitle()
    check(t !== "viewer must not write" && t !== "outsider must not write", "4  neither refused edit reached the database")

    // 5. the change feed carries it and a laptop pulls the new version
    let seen = false
    for (let i = 0; i < 10 && !seen; i++) {
      await sleep(i === 0 ? 300 : 1200)
      const pull = await hit(member, "pull", { project_id: projectId, kind: "tasks", after: null, limit: 200 })
      const row = (pull.json.items as J[] | undefined)?.find((x) => String(x.id) === taskId)
      seen = !!row && Number(row.version) >= version1
    }
    check(seen, "5  a laptop that pulls sees the pushed version (tracking + feed + pull, end to end)")
  } finally {
    // restore: push the original title back with the current version; fall back to a direct update if the push path itself is what failed
    const cur = await hit(member, "pull", { project_id: projectId, kind: "tasks", after: null, limit: 200 })
    const row = (cur.json.items as J[] | undefined)?.find((x) => String(x.id) === taskId)
    const base = Number(row?.version ?? version1)
    const back = await push(member, [mkOp(title0, base)], "live-device-push-0005")
    if ((await dbTitle()) !== title0) await sql(`update compliance.pms_issues set title = ${lit(title0)} where id = ${lit(taskId)} and org_id = ${lit(A_ORG)}`)
    check((await dbTitle()) === title0, "restore: the fixture task has its original title again", `restore push ${back.status}`)
  }

  const failed = results.filter((r) => !r.ok)
  console.log(`\n${results.length - failed.length} PASS, ${failed.length} FAIL`)
  if (failed.length) {
    for (const f of failed) console.log("  FAILED:", f.name)
    process.exit(1)
  }
  process.exit(0)
}
main().catch((e) => {
  console.error("ERROR:", String(e?.message ?? e).replace(/postgres(ql)?:\/\/\S+/gi, "<hidden>").slice(0, 700))
  process.exit(2)
})
