-- WO-DPDP-003 Section 4.9/4.10: commercial (file packs, custody, partner
-- sales) and the CERT-In-constrained auditor/cyber panel. All net-new.
--
-- Generated by `bun run db:generate`, then hand-edited: the raw generator
-- output also tried to CREATE TABLE dpdp.login_token and dpdp.session --
-- both already live in production (0417_dpdp_phase2_auth_tables). This is
-- the same drizzle-kit snapshot-drift class this repo's CLAUDE.md already
-- documents extensively elsewhere (tables added via db:push never make it
-- into a tracked snapshot, so a later db:generate "rediscovers" them as
-- missing) -- confirmed directly via information_schema before editing
-- this file, not assumed. Removed those two CREATE TABLE blocks; only the
-- 7 genuinely new tables below are real drizzle-kit output, unedited.
CREATE TYPE "dpdp"."credential_applies_to" AS ENUM('org', 'person', 'both');--> statement-breakpoint
CREATE TYPE "dpdp"."credential_region" AS ENUM('IN', 'EU', 'US', 'GLOBAL');--> statement-breakpoint
CREATE TYPE "dpdp"."firm_cred_state" AS ENUM('declared', 'evidence', 'expired');--> statement-breakpoint
CREATE TABLE "dpdp"."credential" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"issuer" text NOT NULL,
	"region" "dpdp"."credential_region" NOT NULL,
	"applies_to" "dpdp"."credential_applies_to" NOT NULL,
	"scope" text,
	"exact_wording" text,
	"no_scheme" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dpdp"."custody" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"obligation_file_id" text NOT NULL,
	"term_years" integer DEFAULT 10 NOT NULL,
	"paid_at" timestamp,
	"keep_until" timestamp
);
--> statement-breakpoint
CREATE TABLE "dpdp"."file_pack" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"pack_size" integer NOT NULL,
	"files_remaining" integer NOT NULL,
	"purchased_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "dpdp"."firm_cred" (
	"id" text PRIMARY KEY NOT NULL,
	"firm_id" text NOT NULL,
	"credential_id" text NOT NULL,
	"expires_on" date,
	"state" "dpdp"."firm_cred_state" DEFAULT 'declared' NOT NULL,
	"artefact_id" text
);
--> statement-breakpoint
CREATE TABLE "dpdp"."panel_firm" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"name" text NOT NULL,
	"city" text,
	"since" date,
	"headcount" integer,
	"response_sla" text,
	"jobs_via_us" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dpdp"."panel_request" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"firm_id" text NOT NULL,
	"requested_at" timestamp DEFAULT now() NOT NULL,
	"responded_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "dpdp"."partner_sale" (
	"id" text PRIMARY KEY NOT NULL,
	"partner_id" text NOT NULL,
	"org_id" text NOT NULL,
	"at" timestamp DEFAULT now() NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	"commission_paise" integer NOT NULL,
	"recurs" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
-- RLS: straightforward org_id-scoped tenant isolation, matching 0415's
-- own generic-loop pattern for the rest of dpdp.*. credential/panel_firm
-- are read-mostly reference/marketplace data -- credential has no org_id
-- at all (global reference list, like obligation_template), panel_firm and
-- panel_request are org-scoped for writes but panel_firm's own listing is
-- meant to be visible across orgs (the "find an auditor" marketplace is
-- read-across-orgs by design), so panel_firm gets a permissive SELECT
-- (any authenticated org may browse the marketplace) alongside an
-- owner-org-scoped write policy, not a single org_id=current_org_id() FOR ALL.
ALTER TABLE "dpdp"."file_pack" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."file_pack" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."custody" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."custody" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- partner_sale has no org_id-based tenant context to scope by (the acting
-- session is a partner applicant, not a dpdp org) -- readable/writable
-- only by service_role until a real partner-auth plane exists (WO-DPDP-003
-- doesn't specify partner login; flagged, not invented). app_runtime gets
-- no policy at all here deliberately, so RLS default-denies every app_runtime
-- access until that plane is designed.
ALTER TABLE "dpdp"."partner_sale" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

ALTER TABLE "dpdp"."panel_firm" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_marketplace_read ON "dpdp"."panel_firm" FOR SELECT TO app_runtime USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_write ON "dpdp"."panel_firm" FOR INSERT TO app_runtime WITH CHECK (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_update ON "dpdp"."panel_firm" FOR UPDATE TO app_runtime USING (org_id = dpdp.current_org_id()) WITH CHECK (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."panel_request" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."panel_request" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- credential/firm_cred: credential is global reference data (like
-- obligation_template -- readable by everyone, writable by nobody at the
-- app layer; only service_role seeds it). firm_cred is scoped through its
-- firm_id -> panel_firm.org_id, not its own org_id column (it has none).
ALTER TABLE "dpdp"."credential" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_read_all ON "dpdp"."credential" FOR SELECT TO app_runtime USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."firm_cred" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_read_all ON "dpdp"."firm_cred" FOR SELECT TO app_runtime USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_write ON "dpdp"."firm_cred" FOR INSERT TO app_runtime
    WITH CHECK (EXISTS (SELECT 1 FROM dpdp.panel_firm f WHERE f.id = firm_id AND f.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_update ON "dpdp"."firm_cred" FOR UPDATE TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.panel_firm f WHERE f.id = firm_id AND f.org_id = dpdp.current_org_id()))
    WITH CHECK (EXISTS (SELECT 1 FROM dpdp.panel_firm f WHERE f.id = firm_id AND f.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "dpdp"."file_pack", "dpdp"."custody", "dpdp"."partner_sale", "dpdp"."panel_firm",
  "dpdp"."credential", "dpdp"."firm_cred", "dpdp"."panel_request"
TO service_role;

-- Seed: the ONE CERT-In credential row, exact_wording as the sole source
-- of that sentence anywhere in this system (WO 4.10). dpdp_panel_service.ts
-- must render from this row, never a hand-typed string.
--
-- id is explicit (gen_random_uuid()) rather than omitted: found live
-- (2026-09-16, applying this migration for real) that this table's `id`
-- column has no SQL-level DEFAULT -- the app's own createId() default only
-- fires when Drizzle's own insert layer runs it in JS, never for a raw SQL
-- INSERT like this one. Without it: "null value in column id... violates
-- not-null constraint". Confirmed via a real rollback-then-retry, not
-- assumed.
INSERT INTO "dpdp"."credential" (id, kind, issuer, region, applies_to, scope, exact_wording, no_scheme) VALUES
  (gen_random_uuid()::text, 'cert_in_empanelment', 'CERT-In', 'IN', 'org', 'Section 10 data audit', 'This Organization is empanelled by CERT-In for providing information Security Auditing Service', false),
  (gen_random_uuid()::text, 'dpdp_auditor', 'none', 'IN', 'both', 'Section 10 data audit', NULL, true)
ON CONFLICT DO NOTHING;
