-- Task #46 CRM feature-parity gap-closure (2026-07-31). Continuation of
-- Wave 1 (drizzle/0251_crm_wave1_activities_campaigns_lost_reasons.sql):
-- crm_campaigns already covers name/type(campaign_type)/status/date-range
-- (start_date, end_date)/budget(budgeted_cost, actual_cost,
-- expected_revenue)/description/owner, but is missing a distinct
-- `objective` field -- the campaign's goal (e.g. "Brand Awareness", "Lead
-- Generation"), separate from campaign_type (the channel/format, e.g.
-- "Webinar", "Email") and from the freeform description column. Additive,
-- nullable, bare text column -- no backfill needed, no RLS/index changes
-- (crm_campaigns already has RLS + org_id index from 0251).
--
-- Migration numbering: originally written as 0302 against a journal
-- snapshot frozen at idx 278/tag 0300_stage12_dispatch_outcomes. Real
-- rebase-merge (rebase-sweep2b-668, replacement for PR #668) found that
-- number now collides with main's own real
-- 0302_sales_pipeline_dashboard_targets.sql (journal fully current on
-- main at idx 335/tag 0513_pms_project_status_access_rollup as of this
-- rebase -- checked via `git ls-tree -r origin/main -- drizzle/`) --
-- renamed to 0514 (above main's true highest, 0513) with a matching new
-- _journal.json entry (idx 336). Hand-written (not `db:generate`)
-- following 0251's own documented precedent that the generator can't
-- diff against this schema accurately.

ALTER TABLE compliance.crm_campaigns ADD COLUMN IF NOT EXISTS objective text;
