-- WO-DPDP-010: seed the 59-job library (31 firm + 28 institution) as DATA,
-- generated verbatim from veridian-dpdp.html's LIB object by
-- scripts/dpdp/gen-library-seed.mjs -- do not hand-edit this file; re-run the
-- generator if the spec's LIB changes. This is the "0.2-wo010" library
-- version; the WO's own §2 note applies: "the library will be replaced by a
-- lawyer-reviewed version, so make that a data change, not a code change" --
-- a future lawyer-reviewed revision is a NEW library_version row + NEW
-- obligation_template rows (is_current flipped), never an edit to these.
--
-- Judgment calls made here, none of which are in the spec itself (flagged
-- per WO-DPDP-010 §0's invitation to flag anything not directly specified):
--  * plain_text = name (the spec has no separate long-form legal text distinct
--    from the short "what has to be done" line -- the short line IS the
--    verbatim copy).
--  * proof_kind: 'doc' only for the "Publish a privacy policy" job (it
--    produces the policy-version artefact); 'declaration' for everything
--    else. The spec doesn't model photo evidence at all today.
--  * answerable_by: 'processor' for the 5 outside-firm role tags (Website
--    firm/Payroll firm/Group company/Bus firm/School software firm),
--    'internal' otherwise.
--  * recurrence stays the column default ('none') -- the spec's "your list
--    refreshes every quarter" is a whole-library-cycle behaviour, not a
--    per-job cadence, and is out of this migration's scope.
INSERT INTO dpdp.library_version (id, version, released_on, changelog, is_current)
VALUES ('dpdp_lib_0_2_wo010', '0.2-wo010', CURRENT_DATE, 'WO-DPDP-010: 59-job library (31 firm + 28 institution) ported verbatim from veridian-dpdp.html LIB. Supersedes 0.1-draft (schema-only, zero templates).', true)
ON CONFLICT (version) DO NOTHING;

UPDATE dpdp.library_version SET is_current = false WHERE id <> 'dpdp_lib_0_2_wo010' AND is_current = true;

INSERT INTO dpdp.obligation_template
  (id, library_version_id, key, name, plain_text, proof_kind, default_days, answerable_by, role_tag, applies_when, product, part, data_set, data_types, law_codes, depends_on_key)
VALUES
  ('tmpl_firm_01', 'dpdp_lib_0_2_wo010', 'firm-01', 'Name the Grievance Officer (responsible for DPDP policy)', 'Name the Grievance Officer (responsible for DPDP policy)', 'declaration', 4, 'internal', 'Grievance Officer (responsible for DPDP policy)', '{"fromArea":true}'::jsonb, 'firm', 1, 'Whole organisation', NULL, ARRAY['d:§8(9)','d:§8(10)','s:R5(9)']::text[], NULL),
  ('tmpl_firm_02', 'dpdp_lib_0_2_wo010', 'firm-02', 'Name a DPDP coordinator', 'Name a DPDP coordinator', 'declaration', 4, 'internal', 'DPDP coordinator', '{"fromArea":true}'::jsonb, 'firm', 1, 'Whole organisation', NULL, ARRAY['g:']::text[], NULL),
  ('tmpl_firm_03', 'dpdp_lib_0_2_wo010', 'firm-03', 'Publish the Grievance Officer’s name and contact — on your website or a free VERIDIAN page', 'Publish the Grievance Officer’s name and contact — on your website or a free VERIDIAN page', 'declaration', 10, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'firm', 1, 'Whole organisation', NULL, ARRAY['d:§8(9)','d:R9','s:R5(9)']::text[], NULL),
  ('tmpl_firm_04', 'dpdp_lib_0_2_wo010', 'firm-04', 'Write down where it is kept, why you need it, and who can open it', 'Write down where it is kept, why you need it, and who can open it', 'declaration', 10, 'internal', 'Customer data', NULL, 'firm', 2, 'Customers', ARRAY['Name','Phone','Email','Address','PAN','Bank details']::text[], ARRAY['d:§4','d:§8(4)']::text[], NULL),
  ('tmpl_firm_05', 'dpdp_lib_0_2_wo010', 'firm-05', 'Write down where it is kept, why you need it, and who can open it', 'Write down where it is kept, why you need it, and who can open it', 'declaration', 10, 'internal', 'Staff records', NULL, 'firm', 2, 'Employees', ARRAY['Name','PAN','Aadhaar','Bank account','Salary','Photo','Medical']::text[], ARRAY['d:§7(i)','d:§8(4)']::text[], NULL),
  ('tmpl_firm_06', 'dpdp_lib_0_2_wo010', 'firm-06', 'Write down where it is kept, why you need it, and who can open it', 'Write down where it is kept, why you need it, and who can open it', 'declaration', 12, 'internal', 'Staff records', NULL, 'firm', 2, 'Job applicants', ARRAY['Name','CV','Phone','Email']::text[], ARRAY['d:§4','d:§8(4)']::text[], NULL),
  ('tmpl_firm_07', 'dpdp_lib_0_2_wo010', 'firm-07', 'Write down where it is kept, why you need it, and who can open it', 'Write down where it is kept, why you need it, and who can open it', 'declaration', 12, 'processor', 'Website firm', NULL, 'firm', 2, 'Website visitors', ARRAY['Name','Phone','Email','Cookies']::text[], ARRAY['d:§4','d:§8(4)']::text[], NULL),
  ('tmpl_firm_08', 'dpdp_lib_0_2_wo010', 'firm-08', 'Write down where the recordings are kept and for how long', 'Write down where the recordings are kept and for how long', 'declaration', 12, 'internal', 'CCTV', NULL, 'firm', 2, 'CCTV', ARRAY['Video of staff and visitors']::text[], ARRAY['d:§4','d:§8(7)']::text[], NULL),
  ('tmpl_firm_09', 'dpdp_lib_0_2_wo010', 'firm-09', 'Write down where fingerprints or face scans are stored and who can open them', 'Write down where fingerprints or face scans are stored and who can open them', 'declaration', 12, 'internal', 'Staff records', NULL, 'firm', 2, 'Attendance machine', ARRAY['Fingerprint','Face']::text[], ARRAY['d:§8(5)','s:R3']::text[], NULL),
  ('tmpl_firm_10', 'dpdp_lib_0_2_wo010', 'firm-10', 'Write down how long each is kept — keep only what tax and labour law require, delete the rest', 'Write down how long each is kept — keep only what tax and labour law require, delete the rest', 'declaration', 14, 'internal', 'Accounts', NULL, 'firm', 2, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(7)','d:R8']::text[], NULL),
  ('tmpl_firm_11', 'dpdp_lib_0_2_wo010', 'firm-11', 'Give a privacy notice when you collect their data — on the form, invoice or website', 'Give a privacy notice when you collect their data — on the form, invoice or website', 'declaration', 14, 'internal', 'Customer data', NULL, 'firm', 3, 'Customers', ARRAY['All of the above']::text[], ARRAY['d:§5','d:R3','s:R5(3)']::text[], NULL),
  ('tmpl_firm_12', 'dpdp_lib_0_2_wo010', 'firm-12', 'Take consent before sending marketing messages — and make stopping as easy as starting', 'Take consent before sending marketing messages — and make stopping as easy as starting', 'declaration', 14, 'internal', 'Customer data', NULL, 'firm', 3, 'Customers', ARRAY['Phone','Email']::text[], ARRAY['d:§6(1)','d:§6(4)']::text[], NULL),
  ('tmpl_firm_13', 'dpdp_lib_0_2_wo010', 'firm-13', 'Tell staff what you hold and why — no consent is needed for employment', 'Tell staff what you hold and why — no consent is needed for employment', 'declaration', 14, 'internal', 'Staff records', NULL, 'firm', 3, 'Employees', ARRAY['All of the above']::text[], ARRAY['d:§5','d:§7(i)']::text[], NULL),
  ('tmpl_firm_14', 'dpdp_lib_0_2_wo010', 'firm-14', 'Take written consent for sensitive data', 'Take written consent for sensitive data', 'declaration', 10, 'internal', 'Staff records', NULL, 'firm', 3, 'Employees', ARRAY['Fingerprint','Medical','Bank account']::text[], ARRAY['s:R5(1)']::text[], NULL),
  ('tmpl_firm_15', 'dpdp_lib_0_2_wo010', 'firm-15', 'Publish a privacy policy on the website', 'Publish a privacy policy on the website', 'doc', 10, 'processor', 'Website firm', NULL, 'firm', 3, 'Website visitors', ARRAY['Cookies','Form data']::text[], ARRAY['s:R4','d:§5','d:R3']::text[], NULL),
  ('tmpl_firm_16', 'dpdp_lib_0_2_wo010', 'firm-16', 'Put up a notice wherever there is a camera', 'Put up a notice wherever there is a camera', 'declaration', 10, 'internal', 'CCTV', NULL, 'firm', 3, 'CCTV', ARRAY['Video']::text[], ARRAY['d:§5']::text[], NULL),
  ('tmpl_firm_17', 'dpdp_lib_0_2_wo010', 'firm-17', 'Mask Aadhaar copies — keep only the last 4 digits visible', 'Mask Aadhaar copies — keep only the last 4 digits visible', 'declaration', 10, 'internal', 'Staff records', NULL, 'firm', 4, 'Employees · Customers', ARRAY['Aadhaar']::text[], ARRAY['a:§29','d:§8(5)','d:R6']::text[], NULL),
  ('tmpl_firm_18', 'dpdp_lib_0_2_wo010', 'firm-18', 'Passwords on every computer, access only for those who need it, regular backups', 'Passwords on every computer, access only for those who need it, regular backups', 'declaration', 14, 'internal', 'IT & computers', NULL, 'firm', 4, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(5)','d:R6','s:R8']::text[], NULL),
  ('tmpl_firm_19', 'dpdp_lib_0_2_wo010', 'firm-19', 'Keep a record of who opened personal data — for at least one year', 'Keep a record of who opened personal data — for at least one year', 'declaration', 21, 'internal', 'IT & computers', NULL, 'firm', 4, 'All data sets', ARRAY['Access logs']::text[], ARRAY['d:R6(1)(c)','d:R8(3)']::text[], NULL),
  ('tmpl_firm_20', 'dpdp_lib_0_2_wo010', 'firm-20', 'Write down what to do if data leaks — tell the Board and every person affected, full report within 72 hours', 'Write down what to do if data leaks — tell the Board and every person affected, full report within 72 hours', 'declaration', 21, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'firm', 4, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(6)','d:R7']::text[], NULL),
  ('tmpl_firm_21', 'dpdp_lib_0_2_wo010', 'firm-21', 'Check your own laptop and phone for customer data — never forward it on personal WhatsApp', 'Check your own laptop and phone for customer data — never forward it on personal WhatsApp', 'declaration', 12, 'internal', 'All staff', '{"grp":true}'::jsonb, 'firm', 4, 'Everyone', ARRAY['Customer data on personal devices']::text[], ARRAY['d:§8(5)']::text[], NULL),
  ('tmpl_firm_22', 'dpdp_lib_0_2_wo010', 'firm-22', 'Website firm signs the data agreement', 'Website firm signs the data agreement', 'declaration', 12, 'processor', 'Website firm', NULL, 'firm', 5, 'Website visitors', ARRAY['Enquiries']::text[], ARRAY['d:§8(2)','d:R6(1)(f)','s:R7']::text[], NULL),
  ('tmpl_firm_23', 'dpdp_lib_0_2_wo010', 'firm-23', 'Payroll firm signs the data agreement', 'Payroll firm signs the data agreement', 'declaration', 12, 'processor', 'Payroll firm', NULL, 'firm', 5, 'Employees', ARRAY['Bank account','PAN','Salary']::text[], ARRAY['d:§8(2)','d:R6(1)(f)','s:R7']::text[], NULL),
  ('tmpl_firm_24', 'dpdp_lib_0_2_wo010', 'firm-24', 'Group company signs a data-sharing agreement', 'Group company signs a data-sharing agreement', 'declaration', 12, 'processor', 'Group company', NULL, 'firm', 5, 'Customers · Employees', ARRAY['Shared records']::text[], ARRAY['d:§8(2)','s:R7']::text[], NULL),
  ('tmpl_firm_25', 'dpdp_lib_0_2_wo010', 'firm-25', 'Check where your software keeps data — Tally, Zoho, Google — and whether it is outside India', 'Check where your software keeps data — Tally, Zoho, Google — and whether it is outside India', 'declaration', 21, 'internal', 'IT & computers', NULL, 'firm', 5, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(2)','d:§16','d:R15']::text[], NULL),
  ('tmpl_firm_26', 'dpdp_lib_0_2_wo010', 'firm-26', 'Publish how people can ask to see, correct or delete their data', 'Publish how people can ask to see, correct or delete their data', 'declaration', 21, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'firm', 6, 'All data sets', ARRAY['All']::text[], ARRAY['d:§11','d:§12','d:R14(1)']::text[], NULL),
  ('tmpl_firm_27', 'dpdp_lib_0_2_wo010', 'firm-27', 'Answer every complaint within 90 days — within one month under today’s law', 'Answer every complaint within 90 days — within one month under today’s law', 'declaration', 21, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'firm', 6, 'All data sets', ARRAY['All']::text[], ARRAY['d:§13','d:R14(3)','s:R5(9)']::text[], NULL),
  ('tmpl_firm_28', 'dpdp_lib_0_2_wo010', 'firm-28', 'Delete a customer’s data when they ask or when it is no longer needed — and tell anyone you shared it with', 'Delete a customer’s data when they ask or when it is no longer needed — and tell anyone you shared it with', 'declaration', 21, 'internal', 'Customer data', NULL, 'firm', 6, 'Customers', ARRAY['All']::text[], ARRAY['d:§8(7)','d:§12(3)']::text[], NULL),
  ('tmpl_firm_29', 'dpdp_lib_0_2_wo010', 'firm-29', 'Owner confirms all the answers are true', 'Owner confirms all the answers are true', 'declaration', 25, 'internal', 'OWNER', NULL, 'firm', 7, 'Whole organisation', NULL, ARRAY['d:§8(1)']::text[], NULL),
  ('tmpl_firm_30', 'dpdp_lib_0_2_wo010', 'firm-30', 'CA manager checks the proof', 'CA manager checks the proof', 'declaration', 27, 'internal', 'CAMGR', NULL, 'firm', 7, 'Whole organisation', NULL, ARRAY['g:']::text[], 'firm-29'),
  ('tmpl_firm_31', 'dpdp_lib_0_2_wo010', 'firm-31', 'CA partner signs the file', 'CA partner signs the file', 'declaration', 30, 'internal', 'CAPARTNER', NULL, 'firm', 7, 'Whole organisation', NULL, ARRAY['g:']::text[], 'firm-30'),
  ('tmpl_institution_01', 'dpdp_lib_0_2_wo010', 'institution-01', 'Name the Grievance Officer (responsible for DPDP policy)', 'Name the Grievance Officer (responsible for DPDP policy)', 'declaration', 4, 'internal', 'Grievance Officer (responsible for DPDP policy)', '{"fromArea":true}'::jsonb, 'institution', 1, 'Whole school', NULL, ARRAY['d:§8(9)','d:§8(10)']::text[], NULL),
  ('tmpl_institution_02', 'dpdp_lib_0_2_wo010', 'institution-02', 'Name a DPDP coordinator', 'Name a DPDP coordinator', 'declaration', 4, 'internal', 'DPDP coordinator', '{"fromArea":true}'::jsonb, 'institution', 1, 'Whole school', NULL, ARRAY['g:']::text[], NULL),
  ('tmpl_institution_03', 'dpdp_lib_0_2_wo010', 'institution-03', 'Publish the Grievance Officer’s name and contact — on the school website or a free VERIDIAN page', 'Publish the Grievance Officer’s name and contact — on the school website or a free VERIDIAN page', 'declaration', 10, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'institution', 1, 'Whole school', NULL, ARRAY['d:§8(9)','d:R9']::text[], NULL),
  ('tmpl_institution_04', 'dpdp_lib_0_2_wo010', 'institution-04', 'Write down where it is kept — ERP, admission files, UDISE+ — and who can open it', 'Write down where it is kept — ERP, admission files, UDISE+ — and who can open it', 'declaration', 10, 'internal', 'Admission office', NULL, 'institution', 2, 'Students', ARRAY['Name','Date of birth','Photo','Address','Aadhaar','Marks','Attendance','Health','Category']::text[], ARRAY['d:§4','d:§8(4)','d:§9']::text[], NULL),
  ('tmpl_institution_05', 'dpdp_lib_0_2_wo010', 'institution-05', 'Write down where it is kept and who can open it', 'Write down where it is kept and who can open it', 'declaration', 10, 'internal', 'Fees office', NULL, 'institution', 2, 'Parents', ARRAY['Name','Phone','Email','Occupation','Income']::text[], ARRAY['d:§4','d:§8(4)']::text[], NULL),
  ('tmpl_institution_06', 'dpdp_lib_0_2_wo010', 'institution-06', 'Write down where it is kept and who can open it', 'Write down where it is kept and who can open it', 'declaration', 10, 'internal', 'Staff records', NULL, 'institution', 2, 'Staff', ARRAY['Name','PAN','Aadhaar','Bank account','Salary','Medical']::text[], ARRAY['d:§7(i)','d:§8(4)']::text[], NULL),
  ('tmpl_institution_07', 'dpdp_lib_0_2_wo010', 'institution-07', 'Write down where they are — school phones, website, magazine, Instagram', 'Write down where they are — school phones, website, magazine, Instagram', 'declaration', 12, 'internal', 'DPDP coordinator', NULL, 'institution', 2, 'Photos & videos', ARRAY['Children’s photos','Videos']::text[], ARRAY['d:§8(4)','d:§9']::text[], NULL),
  ('tmpl_institution_08', 'dpdp_lib_0_2_wo010', 'institution-08', 'Write down what the bus system records and who can see it', 'Write down what the bus system records and who can see it', 'declaration', 12, 'internal', 'Transport in-charge', NULL, 'institution', 2, 'School buses', ARRAY['Live location','Pickup address','Parent phone']::text[], ARRAY['d:§8(4)','d:§9(3)','d:R12']::text[], NULL),
  ('tmpl_institution_09', 'dpdp_lib_0_2_wo010', 'institution-09', 'Write down where recordings are kept and for how long', 'Write down where recordings are kept and for how long', 'declaration', 12, 'internal', 'CCTV', NULL, 'institution', 2, 'CCTV', ARRAY['Video of children and staff']::text[], ARRAY['d:§4','d:§8(7)']::text[], NULL),
  ('tmpl_institution_10', 'dpdp_lib_0_2_wo010', 'institution-10', 'Write down how long each is kept — admission and TC registers as your board requires; delete the rest', 'Write down how long each is kept — admission and TC registers as your board requires; delete the rest', 'declaration', 14, 'internal', 'Admission office', NULL, 'institution', 2, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(7)','d:R8']::text[], NULL),
  ('tmpl_institution_11', 'dpdp_lib_0_2_wo010', 'institution-11', 'Take verifiable consent from a parent at admission — the school exemption covers only tracking for learning and safety, not admission data', 'Take verifiable consent from a parent at admission — the school exemption covers only tracking for learning and safety, not admission data', 'declaration', 14, 'internal', 'Admission office', NULL, 'institution', 3, 'Students', ARRAY['All of the above']::text[], ARRAY['d:§9(1)','d:R10','d:R12']::text[], NULL),
  ('tmpl_institution_12', 'dpdp_lib_0_2_wo010', 'institution-12', 'Take a separate Yes or No from parents for photos on the website, magazine and social media', 'Take a separate Yes or No from parents for photos on the website, magazine and social media', 'declaration', 14, 'internal', 'DPDP coordinator', NULL, 'institution', 3, 'Photos & videos', ARRAY['Children’s photos']::text[], ARRAY['d:§6','d:§9(1)']::text[], NULL),
  ('tmpl_institution_13', 'dpdp_lib_0_2_wo010', 'institution-13', 'Give parents a notice — what you hold, why, and how to complain', 'Give parents a notice — what you hold, why, and how to complain', 'declaration', 14, 'internal', 'DPDP coordinator', NULL, 'institution', 3, 'Parents', ARRAY['All']::text[], ARRAY['d:§5','d:R3']::text[], NULL),
  ('tmpl_institution_14', 'dpdp_lib_0_2_wo010', 'institution-14', 'Tell staff what you hold and why — no consent is needed for employment', 'Tell staff what you hold and why — no consent is needed for employment', 'declaration', 14, 'internal', 'Staff records', NULL, 'institution', 3, 'Staff', ARRAY['All of the above']::text[], ARRAY['d:§5','d:§7(i)']::text[], NULL),
  ('tmpl_institution_15', 'dpdp_lib_0_2_wo010', 'institution-15', 'Put up a notice wherever there is a camera', 'Put up a notice wherever there is a camera', 'declaration', 10, 'internal', 'CCTV', NULL, 'institution', 3, 'CCTV', ARRAY['Video']::text[], ARRAY['d:§5']::text[], NULL),
  ('tmpl_institution_16', 'dpdp_lib_0_2_wo010', 'institution-16', 'Mask Aadhaar copies — keep only the last 4 digits visible', 'Mask Aadhaar copies — keep only the last 4 digits visible', 'declaration', 10, 'internal', 'Admission office', NULL, 'institution', 4, 'Students · Staff', ARRAY['Aadhaar']::text[], ARRAY['a:§29','d:§8(5)','d:R6']::text[], NULL),
  ('tmpl_institution_17', 'dpdp_lib_0_2_wo010', 'institution-17', 'Passwords on the ERP and every office computer, access only for those who need it, backups', 'Passwords on the ERP and every office computer, access only for those who need it, backups', 'declaration', 14, 'internal', 'IT & computers', NULL, 'institution', 4, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(5)','d:R6']::text[], NULL),
  ('tmpl_institution_18', 'dpdp_lib_0_2_wo010', 'institution-18', 'Keep a record of who opened student data — for at least one year', 'Keep a record of who opened student data — for at least one year', 'declaration', 21, 'internal', 'IT & computers', NULL, 'institution', 4, 'All data sets', ARRAY['Access logs']::text[], ARRAY['d:R6(1)(c)','d:R8(3)']::text[], NULL),
  ('tmpl_institution_19', 'dpdp_lib_0_2_wo010', 'institution-19', 'Write down what to do if data leaks — tell the Board and every family affected, full report within 72 hours', 'Write down what to do if data leaks — tell the Board and every family affected, full report within 72 hours', 'declaration', 21, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'institution', 4, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(6)','d:R7']::text[], NULL),
  ('tmpl_institution_20', 'dpdp_lib_0_2_wo010', 'institution-20', 'Check your own laptop and phone for student photos and marks — never share them on personal WhatsApp', 'Check your own laptop and phone for student photos and marks — never share them on personal WhatsApp', 'declaration', 12, 'internal', 'Teachers', '{"grp":true}'::jsonb, 'institution', 4, 'Teachers', ARRAY['Children’s photos','Marks']::text[], ARRAY['d:§8(5)','d:§9']::text[], NULL),
  ('tmpl_institution_21', 'dpdp_lib_0_2_wo010', 'institution-21', 'No ads, profiling or tracking of children beyond learning and safety', 'No ads, profiling or tracking of children beyond learning and safety', 'declaration', 21, 'internal', 'DPDP coordinator', NULL, 'institution', 4, 'Students', ARRAY['Behaviour','Online activity']::text[], ARRAY['d:§9(3)','d:R12']::text[], NULL),
  ('tmpl_institution_22', 'dpdp_lib_0_2_wo010', 'institution-22', 'Bus firm signs the data agreement — location only during the journey, only for safety', 'Bus firm signs the data agreement — location only during the journey, only for safety', 'declaration', 12, 'processor', 'Bus firm', NULL, 'institution', 5, 'School buses', ARRAY['Live location']::text[], ARRAY['d:§8(2)','d:R12']::text[], NULL),
  ('tmpl_institution_23', 'dpdp_lib_0_2_wo010', 'institution-23', 'School software firm signs the data agreement', 'School software firm signs the data agreement', 'declaration', 12, 'processor', 'School software firm', NULL, 'institution', 5, 'Students · Parents', ARRAY['Marks','Attendance','Fees']::text[], ARRAY['d:§8(2)','d:R6(1)(f)']::text[], NULL),
  ('tmpl_institution_24', 'dpdp_lib_0_2_wo010', 'institution-24', 'Check where your apps keep data — ERP, fee app, WhatsApp groups — and whether it is outside India', 'Check where your apps keep data — ERP, fee app, WhatsApp groups — and whether it is outside India', 'declaration', 21, 'internal', 'IT & computers', NULL, 'institution', 5, 'All data sets', ARRAY['All']::text[], ARRAY['d:§8(2)','d:§16','d:R15']::text[], NULL),
  ('tmpl_institution_25', 'dpdp_lib_0_2_wo010', 'institution-25', 'Publish how parents can ask to see, correct or delete their child’s data', 'Publish how parents can ask to see, correct or delete their child’s data', 'declaration', 21, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'institution', 6, 'All data sets', ARRAY['All']::text[], ARRAY['d:§11','d:§12','d:R14(1)']::text[], NULL),
  ('tmpl_institution_26', 'dpdp_lib_0_2_wo010', 'institution-26', 'Answer every complaint within 90 days', 'Answer every complaint within 90 days', 'declaration', 21, 'internal', 'Grievance Officer (responsible for DPDP policy)', NULL, 'institution', 6, 'All data sets', ARRAY['All']::text[], ARRAY['d:§13','d:R14(3)']::text[], NULL),
  ('tmpl_institution_27', 'dpdp_lib_0_2_wo010', 'institution-27', 'Delete a student’s data when it is no longer needed — keep the registers your board requires', 'Delete a student’s data when it is no longer needed — keep the registers your board requires', 'declaration', 21, 'internal', 'Admission office', NULL, 'institution', 6, 'Students', ARRAY['All']::text[], ARRAY['d:§8(7)','d:§12(3)']::text[], NULL),
  ('tmpl_institution_28', 'dpdp_lib_0_2_wo010', 'institution-28', 'Sign off all the answers', 'Sign off all the answers', 'declaration', 25, 'internal', 'OWNER', NULL, 'institution', 7, 'Whole school', NULL, ARRAY['d:§8(1)']::text[], NULL)
ON CONFLICT (library_version_id, key) DO NOTHING;

-- Resolve depends_on_key -> a real dependent obligation_template.id, kept as
-- a convenience view-free lookup: dpdp-obligation-library.ts resolves this
-- at instantiation time (per-org obligation rows), not here -- this table is
-- shared/global, so there is nothing org-specific to wire up yet.
