-- PROJEXA-BUILD-001 U-22 (Phase 3, WO 3.1 / 3.2 / 3.6, PMD-17): the data half
-- of the evidence standard on platform.sumeet_requirements. Rows only; no
-- schema change. Needs drizzle/0616_build001_requirement_evidence.sql first.
--
-- WHAT
--   (a) INSERT the 31 exceptions-directive rows EXC-ITEM-01..EXC-ITEM-31
--       (ON CONFLICT (id) DO NOTHING). Ids, titles and detectors are
--       ai-os/projexa-build-001/REQUIREMENTS_111_REGISTER.csv; the detectors are
--       the find*() functions of src/lib/services/construction-exceptions-service.ts
--       at commit 6d531f53 (PR #1752), wired into getProjectExceptions().
--       source = 'construction-exceptions-service.ts@6d531f53' (register row BR-307; platform.sumeet_gap is
--       NOT the source, PMD-17). sort_order continues after the highest
--       non-EXC row (83 on 2026-09-25, so 84..114). updated_at takes its
--       default now(); updated_by = 'BUILD-001 U-22'.
--       Set honestly: status 'OPEN - ...' (none is DONE), closure_state 'OPEN',
--       built 'YES' for items 1-28 (the detector exists on main and its
--       verify_command passed on 2026-09-25) and 'n/a' for the META items 29-31,
--       verified_in_db and tested_in_live_ui NULL (never checked against live
--       data or the PROJEXA screen). Each row gets a verify_command (items 1-28:
--       the detector's own tests in construction-exceptions-service.test.ts plus
--       the aggregator test that proves all 28 item numbers are reported; items
--       29-31: a register-level SELECT on platform.sumeet_requirements, BR-310)
--       and, for items 1-28, evidence_ref = the 6d531f53 commit.
--   (b) UPDATE the existing register rows: 69 of the 80 get a
--       verify_command and 72 get an evidence_ref, each only where the
--       column is still NULL (coalesce), so a value written by hand is never
--       overwritten. updated_at and updated_by are NOT touched on these rows,
--       so the down file can restore them exactly. status is never changed.
--       Every value, what was run and its result on 2026-09-25 are in
--       ai-os/projexa-build-001/U22_REQUIREMENT_CHECKS.md.
--
-- CONVENTION: a verify_command runs from the compliance-tracker repo root. A
--   sql-assert command over tenant data or over platform.sumeet_requirements
--   (RLS on, service_role policy only) needs VERIFY_DATABASE_URL for a role
--   that can see the rows; app_runtime reads 0 for the wrong reason (PMD-22).
--
-- NOT SET, ON PURPOSE (listed in U22_REQUIREMENT_CHECKS.md for the PM):
--   verify_command stays NULL where no compliance-tracker-runnable check
--   exercises the requirement (UI-only PROJEXA rows R-15, R-31, R-92; owner
--   decisions and security items R-A1, R-A2, R-A3, R-A5, R-A7; R-B2, R-C17,
--   R-96). evidence_ref stays NULL where no commit, PR or dated query result
--   could be found (R-A1, R-A2, R-A3, R-A7, R-C17, R-93, R-96, R-98).
--
-- HOW IT IS APPLIED: through the Supabase MCP (apply_migration) by the PM,
--   after 0616, after the PGlite proof
--   src/lib/services/sumeet-requirements-evidence-migration.pglite.test.ts
--   passes. Not in PHASE2_MIGRATIONS.txt: a rows-only file leaves the schema
--   hash unchanged, so the schema-hash rehearsal cannot prove it.
--   Idempotent: ON CONFLICT DO NOTHING and coalesce, so a second run changes
--   nothing.
--
-- DATA LOSS: none. New rows only, and only NULL cells of the two new columns
--   are filled.
--
-- ROLLBACK: drizzle/down/0617_build001_requirement_evidence_data.down.sql

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $guard$
BEGIN
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema = 'platform' AND table_name = 'sumeet_requirements'
        AND column_name IN ('verify_command', 'evidence_ref')) <> 2 THEN
    RAISE EXCEPTION '0617 REFUSED: platform.sumeet_requirements has no verify_command / evidence_ref columns. Apply drizzle/0616_build001_requirement_evidence.sql first. Nothing was changed.';
  END IF;
END
$guard$;

-- (a) the 31 exceptions-directive rows ---------------------------------------
INSERT INTO platform.sumeet_requirements
  (id, sort_order, area, requirement, source, status, built, verified_in_db, tested_in_live_ui,
   route, file_path, github_pr, next_action, updated_by, closure_state, verify_command, evidence_ref)
SELECT v.id,
       base.max_sort + v.n,
       v.area, v.requirement, 'construction-exceptions-service.ts@6d531f53', v.status, v.built, NULL, NULL,
       v.route, v.file_path, v.github_pr, v.next_action, 'BUILD-001 U-22', 'OPEN', v.verify_command, v.evidence_ref
FROM (VALUES
    ('EXC-ITEM-01', 1, 'Exceptions', 'Extra work is done, never captured', 'OPEN - detector present in construction-exceptions-service.ts (findDiaryWithoutProgressEntry); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findDiaryWithoutProgressEntry)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findDiaryWithoutProgressEntry|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-02', 2, 'Exceptions', 'Extra work is done, never billed', 'OPEN - detector present in construction-exceptions-service.ts (findApprovedChangeOrdersNeverBilled); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findApprovedChangeOrdersNeverBilled)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findApprovedChangeOrdersNeverBilled|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-03', 3, 'Exceptions', 'Site builds from the drawing but not confirmed', 'OPEN - detector present in construction-exceptions-service.ts (findUnconfirmedDrawingProgress); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findUnconfirmedDrawingProgress)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "drawing with no confirmation|confirmed drawing reference|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-04', 4, 'Exceptions', 'Site builds from the old drawing', 'OPEN - detector present in construction-exceptions-service.ts (findOldDrawingProgress); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findOldDrawingProgress)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "superseded drawing|current drawing version|findOldDrawingProgress \(#4\)|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-05', 5, 'Exceptions', 'Approvals stuck', 'OPEN - detector present in construction-exceptions-service.ts (findStuckApprovals); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findStuckApprovals)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findStuckApprovals|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-06', 6, 'Exceptions', 'Wrong approval given', 'OPEN - detector present in construction-exceptions-service.ts (findSelfApprovedChangeOrders); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findSelfApprovedChangeOrders)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findSelfApprovedChangeOrders|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-07', 7, 'Exceptions', 'Work without approval happened', 'OPEN - detector present in construction-exceptions-service.ts (findWorkWithoutApprovedBoq); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findWorkWithoutApprovedBoq)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findWorkWithoutApprovedBoq|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-08', 8, 'Exceptions', 'Work happened not captured', 'OPEN - detector present in construction-exceptions-service.ts (findDiaryWithoutProgressEntry (shared with 1)); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findDiaryWithoutProgressEntry (shared with 1))', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findDiaryWithoutProgressEntry|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-09', 9, 'Exceptions', 'Work happened not billed', 'OPEN - detector present in construction-exceptions-service.ts (findProgressNeverBilled); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findProgressNeverBilled)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findProgressNeverBilled|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-10', 10, 'Exceptions', 'Work disputed with vendor', 'OPEN - detector present in construction-exceptions-service.ts (findOpenVendorDisputes); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findOpenVendorDisputes)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "open vendor dispute is flagged|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-11', 11, 'Exceptions', 'Work disputed by customer', 'OPEN - detector present in construction-exceptions-service.ts (findOpenCustomerComplaints(work_dispute)); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findOpenCustomerComplaints(work_dispute))', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "narrows to work_dispute|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-12', 12, 'Exceptions', 'Customer complained', 'OPEN - detector present in construction-exceptions-service.ts (findOpenCustomerComplaints); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findOpenCustomerComplaints)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "open complaint is flagged|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-13', 13, 'Exceptions', 'New SCOPE OF WORK decided', 'OPEN - detector present in construction-exceptions-service.ts (findNewBoqRevisions); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findNewBoqRevisions)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findNewBoqRevisions|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-14', 14, 'Exceptions', 'New BOQ decided', 'OPEN - detector present in construction-exceptions-service.ts (findNewBoqRevisions (shared with 13)); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findNewBoqRevisions (shared with 13))', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findNewBoqRevisions|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-15', 15, 'Exceptions', 'Approval from customer on new SCOPE OF WORK', 'OPEN - detector present in construction-exceptions-service.ts (findBoqWithoutCustomerApproval); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findBoqWithoutCustomerApproval)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findBoqWithoutCustomerApproval|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-16', 16, 'Exceptions', 'Approval from customer on new BOQ', 'OPEN - detector present in construction-exceptions-service.ts (findBoqWithoutCustomerApproval (shared with 15)); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findBoqWithoutCustomerApproval (shared with 15))', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findBoqWithoutCustomerApproval|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-17', 17, 'Exceptions', 'Approvals given without comparing SCOPE OF WORK AND BOQ', 'OPEN - detector present in construction-exceptions-service.ts (findApprovalsWithoutBoqComparison); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findApprovalsWithoutBoqComparison)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findApprovalsWithoutBoqComparison|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-18', 18, 'Exceptions', 'Material ordered WITHOUT SCOPE OF WORK AND BOQ', 'OPEN - detector present in construction-exceptions-service.ts (findMaterialWithoutBoqLine); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findMaterialWithoutBoqLine)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findMaterialWithoutBoqLine|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-19', 19, 'Exceptions', 'Material ordered twice, or late', 'OPEN - detector present in construction-exceptions-service.ts (findLateOrDuplicateMaterial); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findLateOrDuplicateMaterial)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findLateOrDuplicateMaterial|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-20', 20, 'Exceptions', 'The daily report never arrives', 'OPEN - detector present in construction-exceptions-service.ts (findMissingDailyReports); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findMissingDailyReports)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findMissingDailyReports|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-21', 21, 'Exceptions', 'Manpower on paper, payroll disputes', 'OPEN - detector present in construction-exceptions-service.ts (findUnlinkedRoster); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findUnlinkedRoster)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findUnlinkedRoster|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-22', 22, 'Exceptions', 'Multiple versions of the BOQ -- which one is final, which is worked upon', 'OPEN - detector present in construction-exceptions-service.ts (findAmbiguousBoqVersions); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findAmbiguousBoqVersions)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findAmbiguousBoqVersions|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-23', 23, 'Exceptions', 'Subcontractor invoices don''t match the work', 'OPEN - detector present in construction-exceptions-service.ts (findMismatchedSubcontractorInvoices); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findMismatchedSubcontractorInvoices)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findMismatchedSubcontractorInvoices|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-24', 24, 'Exceptions', 'Snags lost, retention held', 'OPEN - detector present in construction-exceptions-service.ts (findOverdueSnags + findRetentionHeldDespiteSnagsClosed); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findOverdueSnags + findRetentionHeldDespiteSnagsClosed)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findOverdueSnags|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-25', 25, 'Exceptions', 'The user decides from memory', 'OPEN - detector present in construction-exceptions-service.ts (findApprovalsWithoutEvidence); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findApprovalsWithoutEvidence)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findApprovalsWithoutEvidence|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-26', 26, 'Exceptions', 'The user forgets', 'OPEN - detector present in construction-exceptions-service.ts (findMissingDailyReports (shared with 20)); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findMissingDailyReports (shared with 20))', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findMissingDailyReports|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-27', 27, 'Exceptions', 'The user doesn''t remember', 'OPEN - detector present in construction-exceptions-service.ts (findMaterialWithoutBoqLine (shared with 18)); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findMaterialWithoutBoqLine (shared with 18))', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findMaterialWithoutBoqLine|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-28', 28, 'Exceptions', 'The user reports wrong but it should be caught by software', 'OPEN - detector present in construction-exceptions-service.ts (findProgressRegressions); not yet verified against live project data or the PROJEXA exceptions screen', 'YES', '/api/v1/projexa/exceptions?projectId=<id>', 'src/lib/services/construction-exceptions-service.ts (findProgressRegressions)', 'compliance-tracker#1752', 'Verify against a real project (verified_in_db) and on the PROJEXA exceptions screen (tested_in_live_ui) before any DONE status.', 'bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t "findProgressRegressions|returns exactly the 28 numbered items"', '6d531f534b611ce2f6822b982c8be28369aa5390'),
    ('EXC-ITEM-29', 29, 'Exceptions (META)', 'The software should do all above (META)', 'OPEN - META item of the 31-item exceptions directive; checked only by the register-level query in verify_command', 'n/a', NULL, NULL, NULL, 'Closes when the register query in verify_command returns its expected value.', 'node scripts/verify/sql-assert.mjs --project ct --sql "select count(*) from platform.sumeet_requirements r where r.id ~ ''^EXC-ITEM-(0[1-9]|1[0-9]|2[0-8])\$'' and r.status like ''DONE%'' and coalesce(to_jsonb(r)->>''evidence_ref'', '''') ~ ''^([0-9a-f]{7,40}|PR#[0-9]+|SQL [0-9]{4}-[0-9]{2}-[0-9]{2}: .+)\$''" --equals 28', NULL),
    ('EXC-ITEM-30', 30, 'Exceptions (META)', 'The software should have proper engine, wiring, logic, calculation for all above (META)', 'OPEN - META item of the 31-item exceptions directive; checked only by the register-level query in verify_command', 'n/a', NULL, NULL, NULL, 'Closes when the register query in verify_command returns its expected value.', 'node scripts/verify/sql-assert.mjs --project ct --sql "select count(*) from platform.sumeet_requirements r where r.id ~ ''^EXC-ITEM-(0[1-9]|1[0-9]|2[0-8])\$'' and r.built = ''YES'' and to_jsonb(r)->>''verify_command'' like ''bun test --isolate src/lib/services/construction-exceptions-service.test.ts -t %''" --equals 28', NULL),
    ('EXC-ITEM-31', 31, 'Exceptions (META)', 'PROJEXA-AI.COM should be able to capture, analyze, fix all of these as software for every project (META)', 'OPEN - META item of the 31-item exceptions directive; checked only by the register-level query in verify_command', 'n/a', NULL, NULL, NULL, 'Closes when the register query in verify_command returns its expected value.', 'node scripts/verify/sql-assert.mjs --project ct --sql "select count(*) from platform.sumeet_requirements r where r.id ~ ''^EXC-ITEM-(0[1-9]|1[0-9]|2[0-8])\$'' and r.tested_in_live_ui = ''YES''" --equals 28', NULL)
  ) AS v(id, n, area, requirement, status, built, route, file_path, github_pr, next_action, verify_command, evidence_ref)
CROSS JOIN (SELECT coalesce(max(sort_order), 0) AS max_sort
            FROM platform.sumeet_requirements WHERE id NOT LIKE 'EXC-ITEM-%') AS base
ON CONFLICT (id) DO NOTHING;

-- (b) verify_command and evidence_ref on the existing rows -------------------
UPDATE platform.sumeet_requirements AS r
SET verify_command = coalesce(r.verify_command, v.verify_command),
    evidence_ref   = coalesce(r.evidence_ref, v.evidence_ref)
FROM (VALUES
    ('R-01', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.creation-closure.test.ts src/app/api/v1/construction/boq/boq-route.nested-pricing.test.ts', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-02', 'bun test --isolate src/lib/services/construction-boq-service.test.ts -t "computeHierarchicalAmount"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-03', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.creation-closure.test.ts -t "R-03:"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-04', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.creation-closure.test.ts -t "R-04:"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-10', 'node scripts/verify/sql-assert.mjs --project ct --sql "select count(*) from information_schema.columns where table_schema = ''compliance'' and table_name = ''construction_boq_line_items'' and column_name in (''item_code'', ''parent_line_item_id'', ''breakdown_percentage'')" --equals 3', 'b3de3e1ad613849b8c4f40fa8a000a93793b2398'),
    ('R-11', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.parent-code-validation.test.ts', '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-12', 'bun test --isolate src/lib/services/construction-boq-service.weighted-subtask-pricing.test.ts -t "R-12"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-13', 'bun test --isolate src/lib/services/construction-boq-service.weighted-subtask-pricing.test.ts -t "R-13"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-14', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.creation-closure.test.ts -t "R-14:"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-15', NULL, '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-16', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.parent-code-validation.test.ts -t "R-16"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-17', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.parent-code-validation.test.ts -t "R-17"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-18', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.parent-code-validation.test.ts -t "R-18"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-19', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.nested-pricing.test.ts -t "R-19"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-20', 'bun test --isolate src/lib/services/construction-boq-service.revision-integration.test.ts -t "R-20"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-21', 'bun test --isolate src/lib/services/construction-boq-service.revision-variation.test.ts -t "R-21"', 'a4eb8c4b21dad2b3f2319d98cf0bacef8a2d6abf'),
    ('R-22', 'bun test --isolate src/lib/services/construction-boq-service.scope-reduction-guard.test.ts -t "R-22"', 'a4eb8c4b21dad2b3f2319d98cf0bacef8a2d6abf'),
    ('R-23', 'bun test --isolate src/lib/services/construction-boq-service.scope-reduction-guard.test.ts src/lib/services/construction-boq-service.revision-integration.test.ts -t "R-23|R-C13"', 'a4eb8c4b21dad2b3f2319d98cf0bacef8a2d6abf'),
    ('R-24', 'bun test --isolate src/lib/services/construction-boq-service.revision-variation.test.ts -t "R-24"', 'a4eb8c4b21dad2b3f2319d98cf0bacef8a2d6abf'),
    ('R-30', 'bun test --isolate src/lib/services/construction-boq-service.dual-view-wiring.test.ts -t "getBoq"', '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-31', NULL, '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-32', 'bun test --isolate src/lib/services/boq-dual-view-service.test.ts src/lib/services/construction-boq-service.dual-view-wiring.test.ts -t "R-32"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-33', 'bun test --isolate src/lib/services/construction-reports-service.boq-budget-closure.test.ts -t "R-33"', '8f87a2b79cbe88ff221cec09469df2c44cbb24ab'),
    ('R-40', 'bun test --isolate src/lib/services/construction-progress-service.test.ts -t "createProgressEntry"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-41', 'bun test --isolate src/lib/pdf/work-progress-report-pdf.test.ts -t "computeRows"', '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-42', 'bun test --isolate src/lib/pdf/work-progress-report-pdf.test.ts -t "computeRows"', '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-43', 'bun test --isolate src/lib/pdf/work-progress-report-pdf.test.ts -t "computeRows"', '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-44', 'bun test --isolate src/lib/services/construction-reports-service.earned-value.test.ts -t "R-44:"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-45', 'bun test --isolate src/lib/services/construction-reports-service.earned-value.test.ts -t "R-45:"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-46', 'bun test --isolate src/lib/services/construction-progress-service.test.ts -t "R-46"', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-47', 'bun test --isolate src/lib/services/construction-progress-service.test.ts -t "outside 0-100|assertPercentComplete"', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-48', 'bun test --isolate src/lib/pdf/work-progress-report-pdf.test.ts src/app/api/v1/projexa/work-progress/report/pdf/route.test.ts', '2b6bfbb88a30f15e47b9a3e770c05ebceecff8bd'),
    ('R-50', 'bun test --isolate src/app/api/v1/projexa/dashboard/route.test.ts "src/app/api/v1/projexa/dashboard/[projectId]/route.test.ts" -t "R-50"', '02fca7415d9f133298cb19711057d2b816c8769a'),
    ('R-51', 'bun test --isolate src/lib/services/construction-dashboard-service.test.ts src/lib/services/construction-reports-service.test.ts -t "earned value|earnedValue|R-51"', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-52', 'bun test --isolate src/lib/services/construction-reports-service.boq-budget-closure.test.ts -t "R-52"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-60', 'bun test --isolate src/lib/services/erp-accounting-service.test.ts src/app/api/v1/projexa/currencies/route.test.ts', '5e1d24a66e4cf4f54e61d913c1315aafb9d8df26'),
    ('R-61', 'bun test --isolate src/lib/services/erp-accounting-service.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-62', 'bun test --isolate src/lib/services/erp-accounting-service.test.ts -t "getBaseCurrency"', '2b6bfbb88a30f15e47b9a3e770c05ebceecff8bd'),
    ('R-63', 'node scripts/verify/sql-assert.mjs --project ct --sql "select count(*) from compliance.erp_currencies where org_id = ''projexa_demo_org'' and is_base_currency" --equals 1', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-70', 'bun test --isolate src/lib/services/construction-boq-import-service.test.ts src/lib/services/construction-boq-service.test.ts -t "Sumeet real-file shape|R-70"', 'db469a9e52f8f0b6423c7cf61a4d7963f6f9adbd'),
    ('R-71', 'bun test --isolate src/lib/services/construction-boq-import-service.test.ts -t "clear 400 error|BLOCKING issue|blocking too|skipped with a warning"', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-72', 'bun test --isolate src/lib/services/construction-boq-import-service.test.ts -t "mapBoqHeaders|Sumeet real-file shape"', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-80', 'bun test --isolate src/app/api/v1/projexa/assistant/route.test.ts src/app/api/v1/projexa/chain-options/route.test.ts', 'cc4b84f47a2e06238f728fde138975af5e434d32'),
    ('R-81', 'bun test --isolate src/app/api/v1/projexa/module-chain/route.test.ts src/app/api/v1/projexa/chain-options/route.test.ts', 'cc4b84f47a2e06238f728fde138975af5e434d32'),
    ('R-82', 'bun test --isolate src/app/api/v1/projexa/assistant/route.test.ts', 'cc4b84f47a2e06238f728fde138975af5e434d32'),
    ('R-90', 'bun test --isolate src/app/api/v1/construction/boq/boq-route.creation-closure.test.ts -t "R-04:"', '63e7e43ac8474f899da67a6e7812d7f238b6ee15'),
    ('R-91', 'bun test --isolate src/lib/errors/error-catalog.test.ts -t "friendlyErrorMessage"', 'f051b3da40cafc048fcd57b5204702f45869f1f5'),
    ('R-A4', 'bun test --isolate src/app/api/v1/projexa/scope/route.test.ts -t "R-A4"', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-A5', NULL, 'd40bc80c60c21310fae2952ffc844530c1eab458'),
    ('R-B1', 'test "$(git grep -c -F ''test("demo gate: TC-01, TC-10, TC-11, TC-30, TC-40'' -- e2e/demo-gate-smoke-env1.spec.ts | awk -F: ''{s+=$2} END {print s+0}'')" = "1"', '4760c244c26f143cdb1401a1547c56fa23a33b5a'),
    ('R-B2', NULL, '7886f1d7ca9fd749ca7306c437bd752d8039ab12'),
    ('R-A6', 'bun test --isolate src/lib/dependency-pins.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-C01', 'bun test --isolate src/app/api/v1/projexa/permits/route.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-C02', 'bun test --isolate src/app/api/v1/projexa/drawings/route.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-C03', 'bun test --isolate src/app/api/v1/documents/route.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-C04', 'bun test --isolate "src/app/api/veri-meetings/[id]/minutes/route.test.ts"', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-C07', 'bun test --isolate src/lib/services/construction-labour-service.test.ts src/lib/services/construction-reports-service.test.ts -t "recordAttendance|createRosterEntry|aggregateManpowerDailySummary|rollUpAttendanceByTrade|manpower-cost"', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-C08', 'bun test --isolate src/lib/services/construction-materials-service.test.ts', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-C09', 'bun test --isolate src/lib/services/construction-boq-service.vendor-budget.test.ts', 'a4eb8c4b21dad2b3f2319d98cf0bacef8a2d6abf'),
    ('R-C10', 'bun test --isolate src/app/api/v1/projexa/schedule/route.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-C11', 'bun test --isolate src/lib/services/construction-reports-service.boq-budget-closure.test.ts -t "R-C11"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-C12', 'bun test --isolate src/lib/services/pms-time-service.test.ts', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-C13', 'bun test --isolate src/lib/services/construction-boq-service.revision-integration.test.ts -t "R-C13"', '28cf473c4791e02aeccdc60c25fbd1184f7ef258'),
    ('R-C14', 'bun test --isolate src/app/api/v1/construction/site-instructions/route.test.ts', '40be85bf3f6622e9a3173a6f50be56b9efd0b089'),
    ('R-C15', 'bun test --isolate src/app/api/v1/projexa/reports/share/route.test.ts "src/app/api/v1/projexa/reports/[reportName]/export/route.test.ts" src/lib/services/report-share-service.shareable-types.test.ts', 'b6999822037f01512e86b86335ef8a6f8b9c67af'),
    ('R-C16', 'bun test --isolate src/lib/crr/capture.test.ts src/lib/crr/recall.test.ts', 'a4eb8c4b21dad2b3f2319d98cf0bacef8a2d6abf'),
    ('R-92', NULL, 'cb095a32daa4756b7dbf4970ba51f4604128b8e9'),
    ('R-93', 'bun test --isolate src/lib/services/construction-boq-service.dual-view-wiring.test.ts src/lib/services/boq-dual-view-service.test.ts -t "getBoq|computeBoqLineMoneyView"', NULL),
    ('R-94', 'bun test --isolate src/lib/services/pms-taxonomy-service.test.ts src/app/api/v1/projexa/milestones/route.test.ts', '20cacb8f7918b10136b711c0c86ec05562bfa08c'),
    ('R-95', 'bun test --isolate src/app/api/v1/projexa/billing-claims/route.test.ts "src/app/api/v1/projexa/billing-claims/[id]/route.test.ts"', '0411dba1d89e9e8400e2aac80d5391264a646807'),
    ('R-97', 'bun test --isolate src/app/api/v1/projexa/change-orders/route.test.ts', 'c4ce4fae26045371f6e7168a75c9ef152cca39bd'),
    ('R-98', 'bun test --isolate src/lib/services/construction-boq-service.revision-integration.test.ts', NULL),
    ('R-99', 'bun test --isolate src/lib/services/boq-analysis-service.test.ts src/app/api/v1/projexa/reports/boq-analysis/route.test.ts src/app/api/v1/projexa/billing-claims/route.test.ts', '20cacb8f7918b10136b711c0c86ec05562bfa08c'),
    ('R-100', 'bun test --isolate src/lib/services/boq-analysis-service.test.ts src/lib/services/boq-dual-view-service.test.ts -t "THE ANSWER|computeProfitAtBothLevels"', '20cacb8f7918b10136b711c0c86ec05562bfa08c')
  ) AS v(id, verify_command, evidence_ref)
WHERE r.id = v.id
  AND ((r.verify_command IS NULL AND v.verify_command IS NOT NULL)
       OR (r.evidence_ref IS NULL AND v.evidence_ref IS NOT NULL));

COMMIT;
