-- PROJEXA-BUILD-002 WP-05e, WP-05f and AW-312 (register rows AW-305, AW-306 and the exception-capture row): the fifth generated seed of the
-- Universal AI Work Link's function allow-list, for coverage waves 5 and 6 and the eight owner exception items that had no write path. It
-- follows drizzle/0644_build002_awl_seed_project_boq.sql, drizzle/0643_build002_record_kinds.sql, drizzle/0650_build002_awl_seed_coverage_waves_1_2.sql
-- and drizzle/0647_build002_awl_seed_waves_3_4.sql, which stay as they were applied.
--
-- WHAT
--   platform.ai_work_link_functions       22 rows added to the 70 of 0647, so the table holds 92 rows
--                                         and 73 of them are on links, from src/lib/pipeline/function-registry.ts and
--                                         scripts/gen-ai-link-registry.data.ts:
--                                           wave 5   create_mom, update_mom_minutes, add_meeting_action_item, add_meeting_outcome, capture_artifact
--                                                    level 1 (a link may run them directly), no money, rank 2
--                                                    create_drawing        level 2 (a draft: a current drawing takes over the build set), rank 2
--                                                    record_material_receipt  level 2, money sensitive (a unit cost), rank 2
--                                                    publish_mom           level 2 (it locks the minutes), rank 3
--                                                    approve_timesheet, reject_timesheet  level 2 (a manager's decision), rank 3
--                                           wave 6   get_gantt_schedule, compare_schedule_baseline   level 0 reads, rank 2
--                                                    get_project_exceptions, compare_boq_revisions, get_project_budget_variance
--                                                                          level 0 reads that state amounts, money sensitive, rank 3
--                                                    capture_schedule_baseline  level 2 (it freezes the plan of record), rank 3
--                                                    update_task           level 1, rank 2
--                                           AW-312   set_progress_drawing, record_customer_complaint  level 2, rank 2
--                                                    record_vendor_dispute level 2, money sensitive (an amount), rank 2
--                                                    record_customer_approval  level 2, rank 3
--                                                    link_roster_employee  on no link (excluded_reason): an employee id is HR data, not project data
--                                         The other 70 rows are written again exactly as 0647 wrote them.
--   platform.ai_work_link_record_kinds    the same 33 record kinds as 0643, unchanged.
--   public.ai_work_link__registry_version()  the sha256 of exactly the rows above, so the running database can say it holds this seed.
--
-- WHAT IS NOT HERE. The declared parameters, the id parameters and the required parameters of each function are read by the Edge Function from
-- supabase/functions/ai-work-link/function-registry.generated.json, not from the database, so they are not columns and not rows. Links already
-- minted keep the function ceiling they were minted with (allowed_functions): a person re-mints a link to use a new function.
--
-- GENERATED. The block between the BEGIN and END GENERATED markers is written by scripts/gen-ai-link-registry.ts (CURRENT_SEED_MIGRATION
-- points here). Do not edit it by hand. `bun scripts/gen-ai-link-registry.ts --check` and src/scripts/gen-ai-link-registry.test.ts fail
-- while this block, or either JSON file under supabase/functions/ai-work-link/, differs from what the registry generates.
--
-- ONE-SHOT ONCE APPLIED. After this file has been applied live it is never edited again; the next registry change adds another seed
-- migration and moves CURRENT_SEED_MIGRATION.
--
-- IDEMPOTENT: rows are upserted by key and rows of a function or kind the block no longer names are deleted, so applying this file twice, or
-- after 0647, leaves the tables exactly as the block says. Nothing here touches platform.ai_work_link_settings.
--
-- DATA LOSS: none. Additive: 22 rows and a function body.
--
-- HOW IT IS APPLIED: by the PM through the Supabase MCP, after the always-aborted rehearsal passed and migrations 0621 to 0647 and 0650 are applied.
-- This migration is written by an engineer agent and is not applied by it.
--
-- ROLLBACK: drizzle/down/0648_build002_awl_seed_waves_5_6.down.sql

BEGIN;

SET LOCAL lock_timeout = '5s';

-- BEGIN GENERATED BY scripts/gen-ai-link-registry.ts (do not edit by hand; run the generator)
-- registry version 9a7682c82eb3dfaa65e6836871fdab63d5efe3c6a1e8b267835a7fe3d25bbff4
DELETE FROM platform.ai_work_link_functions WHERE function_id <> ALL (ARRAY['add_boq_lines', 'add_meeting_action_item', 'add_meeting_outcome', 'add_roster_entry', 'answer_rfi', 'apply_boq_import', 'approve_timesheet', 'capture_artifact', 'capture_schedule_baseline', 'close_rfi', 'compare_boq_revisions', 'compare_schedule_baseline', 'create_activity', 'create_boq', 'create_boq_revision', 'create_change_order', 'create_document', 'create_drawing', 'create_material', 'create_meeting', 'create_milestone', 'create_mom', 'create_progress_category', 'create_project', 'create_punch_list_item', 'create_rfi', 'create_schedule_task', 'create_site_diary', 'create_site_instruction', 'create_submittal', 'detect_construction_budget_schedule_risk', 'generate_construction_progress_summary', 'get_billing_due_queue', 'get_boq_line_items', 'get_change_order', 'get_compliance_stats', 'get_construction_budget_status', 'get_construction_kpi_status', 'get_construction_project_dashboard', 'get_daily_progress_report', 'get_designer_timesheet_report', 'get_gantt_schedule', 'get_manpower_cost_report', 'get_material_cost_report', 'get_overdue_items', 'get_project_analysis', 'get_project_budget_variance', 'get_project_exceptions', 'get_project_schedule', 'get_sales_pipeline_overview', 'link_roster_employee', 'list_billing_claims', 'list_change_orders', 'list_compliance_items', 'list_customers', 'list_delayed_activities', 'list_departments', 'list_gst_import_batches', 'list_gst_returns', 'list_leads', 'list_milestones', 'list_notices', 'list_opportunities', 'list_over_budget_projects', 'list_sales_orders', 'mark_punch_item_ready', 'preview_boq_import', 'publish_mom', 'record_attendance', 'record_attendance_batch', 'record_customer_approval', 'record_customer_complaint', 'record_material_issue', 'record_material_receipt', 'record_timesheet', 'record_vendor_dispute', 'record_work_progress', 'reject_timesheet', 'review_budget', 'review_submittal', 'run_named_report', 'seal_boq', 'set_progress_drawing', 'update_line_item_budget', 'update_milestone', 'update_mom_minutes', 'update_progress_entry', 'update_project', 'update_roster_entry', 'update_task', 'verify_punch_item_closed', 'void_material_receipt']::text[]);
INSERT INTO platform.ai_work_link_functions (function_id, product, kind, link_level, money_sensitive, min_role_rank, excluded_reason, text_params) VALUES
  ('add_boq_lines', 'projexa', 'write', 2, true, 2, NULL, '{}'::text[]),
  ('add_meeting_action_item', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('add_meeting_outcome', 'projexa', 'write', 1, false, 2, NULL, ARRAY['notes']::text[]),
  ('add_roster_entry', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'trade', 'employeeCode']::text[]),
  ('answer_rfi', 'projexa', 'write', 2, false, 2, NULL, ARRAY['answer']::text[]),
  ('apply_boq_import', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('approve_timesheet', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('capture_artifact', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'text']::text[]),
  ('capture_schedule_baseline', 'projexa', 'write', 2, false, 3, NULL, ARRAY['name']::text[]),
  ('close_rfi', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('compare_boq_revisions', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('compare_schedule_baseline', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('create_activity', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'unit']::text[]),
  ('create_boq', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_boq_revision', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_change_order', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title', 'description', 'reason', 'trade']::text[]),
  ('create_document', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'category']::text[]),
  ('create_drawing', 'projexa', 'write', 2, false, 2, NULL, ARRAY['name', 'externalUrl', 'drawingNo', 'rev', 'discipline', 'kind']::text[]),
  ('create_material', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'unit', 'spec']::text[]),
  ('create_meeting', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('create_milestone', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('create_mom', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'minutes', 'meetingType', 'attendees', 'agenda']::text[]),
  ('create_progress_category', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name']::text[]),
  ('create_project', 'projexa', 'write', NULL, false, 0, 'A link is bound to one project, so it cannot make another one: the New project with my AI flow and the internal pipeline do.', '{}'::text[]),
  ('create_punch_list_item', 'projexa', 'write', 1, false, 2, NULL, ARRAY['description', 'location', 'trade']::text[]),
  ('create_rfi', 'projexa', 'write', 1, false, 2, NULL, ARRAY['subject', 'question']::text[]),
  ('create_schedule_task', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('create_site_diary', 'projexa', 'write', 1, false, 2, NULL, ARRAY['weather', 'workDone', 'visitors', 'issues', 'instructions', 'materialReceived', 'remarks']::text[]),
  ('create_site_instruction', 'projexa', 'write', 2, false, 2, NULL, ARRAY['toContractor', 'description', 'drawingRef']::text[]),
  ('create_submittal', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'specSection']::text[]),
  ('detect_construction_budget_schedule_risk', 'projexa', 'read', NULL, false, 0, 'Calls a server-side model (F-2): the internal AI never runs on link traffic.', '{}'::text[]),
  ('generate_construction_progress_summary', 'projexa', 'read', NULL, false, 0, 'Calls a server-side model (F-2): the internal AI never runs on link traffic.', '{}'::text[]),
  ('get_billing_due_queue', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_boq_line_items', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_change_order', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_compliance_stats', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('get_construction_budget_status', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_construction_kpi_status', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_construction_project_dashboard', 'projexa', 'read', 0, true, 1, NULL, '{}'::text[]),
  ('get_daily_progress_report', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_designer_timesheet_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_gantt_schedule', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_manpower_cost_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_material_cost_report', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_overdue_items', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('get_project_analysis', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_budget_variance', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_exceptions', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_schedule', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_sales_pipeline_overview', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('link_roster_employee', 'projexa', 'write', NULL, false, 0, 'An employee id is an organisation-wide HR record (personal data), not project data, so it cannot be checked against the link''s project (spec 9.10, F-3). The internal pipeline runs it for a manager.', '{}'::text[]),
  ('list_billing_claims', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('list_change_orders', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('list_compliance_items', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_customers', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_delayed_activities', 'projexa', 'read', NULL, false, 0, 'Reads the whole organisation, not one project (F-3).', '{}'::text[]),
  ('list_departments', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_gst_import_batches', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_gst_returns', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_leads', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_milestones', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('list_notices', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_opportunities', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_over_budget_projects', 'projexa', 'read', NULL, false, 0, 'Reads the whole organisation, not one project (F-3).', '{}'::text[]),
  ('list_sales_orders', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('mark_punch_item_ready', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('preview_boq_import', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('publish_mom', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('record_attendance', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('record_attendance_batch', 'projexa', 'write', 1, true, 2, NULL, '{}'::text[]),
  ('record_customer_approval', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('record_customer_complaint', 'projexa', 'write', 2, false, 2, NULL, ARRAY['description', 'category']::text[]),
  ('record_material_issue', 'projexa', 'write', 1, false, 2, NULL, ARRAY['issuedTo', 'note']::text[]),
  ('record_material_receipt', 'projexa', 'write', 2, true, 2, NULL, ARRAY['materialName', 'reference', 'notes', 'spec', 'unit']::text[]),
  ('record_timesheet', 'projexa', 'write', 1, false, 2, NULL, ARRAY['task', 'activityType']::text[]),
  ('record_vendor_dispute', 'projexa', 'write', 2, true, 2, NULL, ARRAY['description']::text[]),
  ('record_work_progress', 'projexa', 'write', 1, false, 2, NULL, ARRAY['remarks']::text[]),
  ('reject_timesheet', 'projexa', 'write', 2, false, 3, NULL, ARRAY['rejectionReason']::text[]),
  ('review_budget', 'projexa', 'read', NULL, false, 0, 'An alias that duplicates get_construction_budget_status.', '{}'::text[]),
  ('review_submittal', 'projexa', 'write', 2, false, 3, NULL, ARRAY['comments']::text[]),
  ('run_named_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('seal_boq', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('set_progress_drawing', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('update_line_item_budget', 'projexa', 'write', 2, true, 3, NULL, ARRAY['category']::text[]),
  ('update_milestone', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('update_mom_minutes', 'projexa', 'write', 1, false, 2, NULL, ARRAY['minutes']::text[]),
  ('update_progress_entry', 'projexa', 'write', 1, true, 2, NULL, ARRAY['remarks']::text[]),
  ('update_project', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'description']::text[]),
  ('update_roster_entry', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'trade', 'skillLevel']::text[]),
  ('update_task', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('verify_punch_item_closed', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('void_material_receipt', 'projexa', 'write', 2, true, 3, NULL, ARRAY['reason']::text[])
ON CONFLICT (function_id) DO UPDATE SET
  product = EXCLUDED.product, kind = EXCLUDED.kind, link_level = EXCLUDED.link_level, money_sensitive = EXCLUDED.money_sensitive,
  min_role_rank = EXCLUDED.min_role_rank, excluded_reason = EXCLUDED.excluded_reason, text_params = EXCLUDED.text_params;

DELETE FROM platform.ai_work_link_record_kinds WHERE kind <> ALL (ARRAY['project', 'boqs', 'boq_lines', 'activities', 'progress', 'tasks', 'meetings', 'documents', 'roster', 'attendance', 'timesheets', 'pipeline_tasks', 'people', 'rfis', 'submittals', 'punch_list', 'change_orders', 'site_diaries', 'site_instructions', 'milestones', 'progress_claims', 'interim_bills', 'materials', 'material_receipts', 'material_issues', 'kpi_entries', 'expenses', 'drawings', 'permits', 'meeting_minutes', 'wiki_pages', 'ffe_items', 'schedule_baselines']::text[]);
INSERT INTO platform.ai_work_link_record_kinds (kind, money_columns, filters) VALUES
  ('project', ARRAY['project_value', 'vat_rate_percent', 'retention_percent']::text[], '{"fields":{},"sort":[]}'::jsonb),
  ('boqs', ARRAY['contract_value_override']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"version":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["version","created_at"]}'::jsonb),
  ('boq_lines', ARRAY['rate', 'amount', 'material_cost', 'labour_cost', 'equipment_cost', 'budget_percentage', 'vendor_amount', 'material_amount', 'manpower_amount', 'rate_project', 'rate_contract', 'vendor_id', 'overhead_percent', 'profit_percent']::text[], '{"fields":{"boq_id":{"type":"text","ops":["eq","in"]},"item_code":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]},"rate":{"type":"numeric","ops":["eq","gt","lt"]},"amount":{"type":"numeric","ops":["eq","gt","lt"]},"budget_percentage":{"type":"numeric","ops":["eq","gt","lt"]},"breakdown_percentage":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["created_at","quantity","rate","amount","budget_percentage"]}'::jsonb),
  ('activities', '{}'::text[], '{"fields":{"category_id":{"type":"text","ops":["eq","in"]},"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at"]}'::jsonb),
  ('progress', '{}'::text[], '{"fields":{"entry_date":{"type":"date","ops":["eq","gt","lt"]},"activity_id":{"type":"text","ops":["eq","in"]},"boq_line_item_id":{"type":"text","ops":["eq","in"]},"percent_complete":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["entry_date","percent_complete","created_at"]}'::jsonb),
  ('tasks', '{}'::text[], '{"fields":{"status_id":{"type":"text","ops":["eq","in"]},"priority":{"type":"text","ops":["eq","in"]},"assignee_id":{"type":"text","ops":["eq","in"]},"number":{"type":"numeric","ops":["eq","gt","lt"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"completion_percentage":{"type":"numeric","ops":["eq","gt","lt"]},"is_archived":{"type":"boolean","ops":["eq"]}},"sort":["number","priority","completion_percentage","created_at","updated_at"]}'::jsonb),
  ('meetings', '{}'::text[], '{"fields":{"scheduled_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["scheduled_at","created_at"]}'::jsonb),
  ('documents', '{}'::text[], '{"fields":{"category":{"type":"text","ops":["eq","in"]},"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at","version_number"]}'::jsonb),
  ('roster', ARRAY['daily_rate']::text[], '{"fields":{"trade":{"type":"text","ops":["eq","in"]},"is_active":{"type":"boolean","ops":["eq"]},"daily_rate":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["name","created_at","daily_rate"]}'::jsonb),
  ('attendance', ARRAY['daily_cost']::text[], '{"fields":{"attendance_date":{"type":"date","ops":["eq","gt","lt"]},"roster_id":{"type":"text","ops":["eq","in"]},"status":{"type":"text","ops":["eq","in"]},"daily_cost":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["attendance_date","created_at","daily_cost"]}'::jsonb),
  ('timesheets', ARRAY['hourly_rate_snapshot', 'invoice_item_id']::text[], '{"fields":{"spent_on":{"type":"date","ops":["eq","gt","lt"]},"issue_id":{"type":"text","ops":["eq","in"]},"user_id":{"type":"text","ops":["eq","in"]},"activity_type":{"type":"text","ops":["eq","in"]},"hours":{"type":"numeric","ops":["eq","gt","lt"]},"hourly_rate_snapshot":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["spent_on","hours","created_at"]}'::jsonb),
  ('pipeline_tasks', ARRAY['params', 'result']::text[], '{"fields":{"function_id":{"type":"text","ops":["eq","in"]},"status":{"type":"text","ops":["eq","in"]},"created_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["created_at","sequence","status"],"omit_when_hidden":["params","result"]}'::jsonb),
  ('people', '{}'::text[], '{"fields":{"role":{"type":"text","ops":["eq","in"]}},"sort":["name"]}'::jsonb),
  ('rfis', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"ball_in_court":{"type":"text","ops":["eq","in"]},"assigned_to_id":{"type":"text","ops":["eq","in"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"number":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at"]}'::jsonb),
  ('submittals', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"type":{"type":"text","ops":["eq","in"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"number":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at"]}'::jsonb),
  ('punch_list', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"priority":{"type":"text","ops":["eq","in"]},"trade":{"type":"text","ops":["eq","in"]},"assigned_to_id":{"type":"text","ops":["eq","in"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"number":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at"]}'::jsonb),
  ('change_orders', ARRAY['cost_impact']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"trade":{"type":"text","ops":["eq","in"]},"number":{"type":"numeric","ops":["eq","gt","lt"]},"cost_impact":{"type":"numeric","ops":["eq","gt","lt"]},"schedule_impact_days":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at","cost_impact","schedule_impact_days"]}'::jsonb),
  ('site_diaries', '{}'::text[], '{"fields":{"diary_date":{"type":"date","ops":["eq","gt","lt"]}},"sort":["diary_date","created_at"]}'::jsonb),
  ('site_instructions', '{}'::text[], '{"fields":{"issue_date":{"type":"date","ops":["eq","gt","lt"]},"si_number":{"type":"numeric","ops":["eq","gt","lt"]},"cost_impact":{"type":"boolean","ops":["eq"]},"time_impact":{"type":"boolean","ops":["eq"]}},"sort":["si_number","issue_date","created_at"]}'::jsonb),
  ('milestones', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"target_date":{"type":"date","ops":["eq","gt","lt"]}},"sort":["name","created_at"]}'::jsonb),
  ('progress_claims', ARRAY['retention_percent', 'customer_id', 'interim_bill_id']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"boq_id":{"type":"text","ops":["eq","in"]},"scheduled_date":{"type":"date","ops":["eq","gt","lt"]},"retention_percent":{"type":"numeric","ops":["eq","gt","lt"]},"customer_id":{"type":"text","ops":["eq","in"]}},"sort":["scheduled_date","created_at","retention_percent"]}'::jsonb),
  ('interim_bills', ARRAY['retention_percent', 'gross_amount', 'retention_amount', 'net_payable', 'retention_released_amount', 'sales_invoice_id']::text[], '{"fields":{"boq_id":{"type":"text","ops":["eq","in"]},"bill_number":{"type":"numeric","ops":["eq","gt","lt"]},"bill_date":{"type":"date","ops":["eq","gt","lt"]},"gross_amount":{"type":"numeric","ops":["eq","gt","lt"]},"net_payable":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["bill_number","bill_date","created_at","gross_amount","net_payable"]}'::jsonb),
  ('materials', ARRAY['unit_cost']::text[], '{"fields":{"name":{"type":"text","ops":["eq"]},"is_active":{"type":"boolean","ops":["eq"]},"unit_cost":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["name","created_at","unit_cost"]}'::jsonb),
  ('material_receipts', ARRAY['unit_cost', 'vendor_id']::text[], '{"fields":{"material_id":{"type":"text","ops":["eq","in"]},"received_date":{"type":"date","ops":["eq","gt","lt"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]},"unit_cost":{"type":"numeric","ops":["eq","gt","lt"]},"vendor_id":{"type":"text","ops":["eq","in"]}},"sort":["received_date","created_at","quantity"]}'::jsonb),
  ('material_issues', '{}'::text[], '{"fields":{"material_id":{"type":"text","ops":["eq","in"]},"boq_line_item_id":{"type":"text","ops":["eq","in"]},"issued_date":{"type":"date","ops":["eq","gt","lt"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["issued_date","created_at","quantity"]}'::jsonb),
  ('kpi_entries', ARRAY['target_value', 'actual_value']::text[], '{"fields":{"kpi_definition_id":{"type":"text","ops":["eq","in"]},"metric_name":{"type":"text","ops":["eq","in"]},"period":{"type":"text","ops":["eq","in"]},"approval_status":{"type":"text","ops":["eq","in"]},"actual_value":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["created_at","period","actual_value"]}'::jsonb),
  ('expenses', ARRAY['amount', 'description']::text[], '{"fields":{"expense_head":{"type":"text","ops":["eq","in"]},"expense_date":{"type":"date","ops":["eq","gt","lt"]},"is_rework":{"type":"boolean","ops":["eq"]},"amount":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["expense_date","created_at","amount"]}'::jsonb),
  ('drawings', '{}'::text[], '{"fields":{"drawing_no":{"type":"text","ops":["eq","in"]},"revision":{"type":"text","ops":["eq","in"]},"drawing_status":{"type":"text","ops":["eq","in"]},"discipline":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]}},"sort":["name","created_at","version_number"]}'::jsonb),
  ('permits', '{}'::text[], '{"fields":{"permit_number":{"type":"text","ops":["eq","in"]},"permit_authority":{"type":"text","ops":["eq","in"]},"expiry_date":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["name","created_at"]}'::jsonb),
  ('meeting_minutes', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"meeting_type":{"type":"text","ops":["eq","in"]},"scheduled_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["scheduled_at","created_at"]}'::jsonb),
  ('wiki_pages', '{}'::text[], '{"fields":{"slug":{"type":"text","ops":["eq","in"]},"title":{"type":"text","ops":["eq"]}},"sort":["slug","title","updated_at"]}'::jsonb),
  ('ffe_items', ARRAY['unit_cost', 'unit_price', 'vendor_id']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]},"room_or_area":{"type":"text","ops":["eq","in"]},"unit_cost":{"type":"numeric","ops":["eq","gt","lt"]},"unit_price":{"type":"numeric","ops":["eq","gt","lt"]},"vendor_id":{"type":"text","ops":["eq","in"]}},"sort":["item_name","created_at","unit_cost","unit_price"]}'::jsonb),
  ('schedule_baselines', '{}'::text[], '{"fields":{"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at"]}'::jsonb)
ON CONFLICT (kind) DO UPDATE SET money_columns = EXCLUDED.money_columns, filters = EXCLUDED.filters;

CREATE OR REPLACE FUNCTION public.ai_work_link__registry_version()
RETURNS text
LANGUAGE sql IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $fn$ SELECT '9a7682c82eb3dfaa65e6836871fdab63d5efe3c6a1e8b267835a7fe3d25bbff4'::text $fn$;

REVOKE ALL ON FUNCTION public.ai_work_link__registry_version() FROM PUBLIC, anon, authenticated, app_runtime;
GRANT EXECUTE ON FUNCTION public.ai_work_link__registry_version() TO service_role;
-- END GENERATED

COMMIT;
