-- PROJEXA-BUILD-002 WP-05a, waves 1 and 2 (register rows AW-301 and AW-302): the third generated seed of the Universal AI Work Link's
-- function allow-list. It follows drizzle/0644_build002_awl_seed_project_boq.sql and drizzle/0643_build002_record_kinds.sql (WP-06, applied after 0644), which stay as they were.
--
-- WHAT
--   platform.ai_work_link_functions       19 rows are added to the 33 of 0644 (a function nobody had reviewed for links had no row at
--                                         all), each with a link level, a rank and its text parameters, so the table holds 52 rows and 34 of
--                                         them are on links:
--                                           wave 1  reads   get_boq_line_items (3), run_named_report (2), get_project_schedule (2),
--                                                           list_milestones (2), get_manpower_cost_report (2), get_designer_timesheet_report (2),
--                                                           get_project_analysis (3)
--                                                   writes  create_milestone, update_milestone, create_schedule_task (level 1, rank 2)
--                                         wave 2  reads   preview_boq_import (3), list_change_orders (2), get_change_order (2),
--                                                           list_billing_claims (3), get_billing_due_queue (3)
--                                                   writes  apply_boq_import (2), create_change_order (2), create_site_instruction (2),
--                                                           update_line_item_budget (3), all level 2, money sensitive except the site instruction
--                                         The number in brackets is the minimum role rank. create_boq, the eleventh function of wave 2, is
--                                         already a level-2 row since 0644. The other 33 rows are written again exactly as 0644 wrote them.
--   platform.ai_work_link_record_kinds    the same 33 record kinds as 0643, unchanged.
--   public.ai_work_link__registry_version()  the sha256 of exactly the rows above, so the running database can say it holds this seed.
--
-- WHAT IS NOT HERE. The parameters each function declares, and the id parameters that get the same-project check, are read by the Edge
-- Function from supabase/functions/ai-work-link/function-registry.generated.json, not from the database. Links already minted keep the
-- function ceiling they were minted with (allowed_functions): a person re-mints a link to use a new function.
--
-- ORDER, read before applying. The block below deletes every function row it does not name, exactly as 0644 and 0628 do. It names the 52
-- functions of this branch (0644 plus waves 1 and 2). A seed written by another wave (waves 3 to 9 each add one) names its own set; apply the
-- seeds in migration-number order and take the highest one as the whole truth, or re-run scripts/gen-ai-link-registry.ts on the merged
-- registry so that one block names every wave. Applying this file after a later wave's seed would remove that wave's rows.
--
-- GENERATED. The block between the BEGIN and END GENERATED markers is written by scripts/gen-ai-link-registry.ts (CURRENT_SEED_MIGRATION
-- points here). Do not edit it by hand. `bun scripts/gen-ai-link-registry.ts --check` and src/scripts/gen-ai-link-registry.test.ts fail
-- while this block, or either JSON file under supabase/functions/ai-work-link/, differs from what the registry generates.
--
-- ONE-SHOT ONCE APPLIED. After this file has been applied live it is never edited again; the next registry change adds another seed
-- migration and moves CURRENT_SEED_MIGRATION.
--
-- IDEMPOTENT: rows are upserted by key and rows of a function or kind the block no longer names are deleted, so applying this file twice, or
-- after 0628, 0644 or 0643, leaves the tables exactly as the block says. Nothing here touches platform.ai_work_link_settings.
--
-- DATA LOSS: none. Additive: nineteen rows and a function body.
--
-- HOW IT IS APPLIED: by the PM through the Supabase MCP, after the always-aborted rehearsal passed and migrations 0621 to 0628, 0644 and 0643 are
-- applied. This migration is written by an engineer agent and is not applied by it.
--
-- ROLLBACK: drizzle/down/0650_build002_awl_seed_coverage_waves_1_2.down.sql

BEGIN;

SET LOCAL lock_timeout = '5s';

-- BEGIN GENERATED BY scripts/gen-ai-link-registry.ts (do not edit by hand; run the generator)
-- registry version 4fb552013e210a5772a45da664b44199c665cc0753d80f0d3f4580dc4e8ac0a3
DELETE FROM platform.ai_work_link_functions WHERE function_id <> ALL (ARRAY['add_boq_lines', 'add_roster_entry', 'apply_boq_import', 'create_activity', 'create_boq', 'create_boq_revision', 'create_change_order', 'create_document', 'create_meeting', 'create_milestone', 'create_project', 'create_schedule_task', 'create_site_instruction', 'detect_construction_budget_schedule_risk', 'generate_construction_progress_summary', 'get_billing_due_queue', 'get_boq_line_items', 'get_change_order', 'get_compliance_stats', 'get_construction_budget_status', 'get_construction_kpi_status', 'get_construction_project_dashboard', 'get_designer_timesheet_report', 'get_manpower_cost_report', 'get_overdue_items', 'get_project_analysis', 'get_project_schedule', 'get_sales_pipeline_overview', 'list_billing_claims', 'list_change_orders', 'list_compliance_items', 'list_customers', 'list_delayed_activities', 'list_departments', 'list_gst_import_batches', 'list_gst_returns', 'list_leads', 'list_milestones', 'list_notices', 'list_opportunities', 'list_over_budget_projects', 'list_sales_orders', 'preview_boq_import', 'record_attendance', 'record_timesheet', 'record_work_progress', 'review_budget', 'run_named_report', 'seal_boq', 'update_line_item_budget', 'update_milestone', 'update_project']::text[]);
INSERT INTO platform.ai_work_link_functions (function_id, product, kind, link_level, money_sensitive, min_role_rank, excluded_reason, text_params) VALUES
  ('add_boq_lines', 'projexa', 'write', 2, true, 2, NULL, '{}'::text[]),
  ('add_roster_entry', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'trade', 'employeeCode']::text[]),
  ('apply_boq_import', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_activity', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'unit']::text[]),
  ('create_boq', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_boq_revision', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_change_order', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title', 'description', 'reason', 'trade']::text[]),
  ('create_document', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'category']::text[]),
  ('create_meeting', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('create_milestone', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('create_project', 'projexa', 'write', NULL, false, 0, 'A link is bound to one project, so it cannot make another one: the New project with my AI flow and the internal pipeline do.', '{}'::text[]),
  ('create_schedule_task', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('create_site_instruction', 'projexa', 'write', 2, false, 2, NULL, ARRAY['toContractor', 'description', 'drawingRef']::text[]),
  ('detect_construction_budget_schedule_risk', 'projexa', 'read', NULL, false, 0, 'Calls a server-side model (F-2): the internal AI never runs on link traffic.', '{}'::text[]),
  ('generate_construction_progress_summary', 'projexa', 'read', NULL, false, 0, 'Calls a server-side model (F-2): the internal AI never runs on link traffic.', '{}'::text[]),
  ('get_billing_due_queue', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_boq_line_items', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_change_order', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_compliance_stats', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('get_construction_budget_status', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_construction_kpi_status', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_construction_project_dashboard', 'projexa', 'read', 0, true, 1, NULL, '{}'::text[]),
  ('get_designer_timesheet_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_manpower_cost_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_overdue_items', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('get_project_analysis', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_schedule', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_sales_pipeline_overview', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_billing_claims', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('list_change_orders', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('list_compliance_items', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_customers', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_delayed_activities', 'projexa', 'read', NULL, false, 0, 'Reads the whole organisation, not one project (F-3).', '{}'::text[]),
  ('list_departments', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_gst_import_batches', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_gst_returns', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_leads', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_milestones', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('list_notices', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_opportunities', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_over_budget_projects', 'projexa', 'read', NULL, false, 0, 'Reads the whole organisation, not one project (F-3).', '{}'::text[]),
  ('list_sales_orders', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('preview_boq_import', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('record_attendance', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('record_timesheet', 'projexa', 'write', 1, false, 2, NULL, ARRAY['task', 'activityType']::text[]),
  ('record_work_progress', 'projexa', 'write', 1, false, 2, NULL, ARRAY['remarks']::text[]),
  ('review_budget', 'projexa', 'read', NULL, false, 0, 'An alias that duplicates get_construction_budget_status.', '{}'::text[]),
  ('run_named_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('seal_boq', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('update_line_item_budget', 'projexa', 'write', 2, true, 3, NULL, ARRAY['category']::text[]),
  ('update_milestone', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('update_project', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'description']::text[])
ON CONFLICT (function_id) DO UPDATE SET
  product = EXCLUDED.product, kind = EXCLUDED.kind, link_level = EXCLUDED.link_level, money_sensitive = EXCLUDED.money_sensitive,
  min_role_rank = EXCLUDED.min_role_rank, excluded_reason = EXCLUDED.excluded_reason, text_params = EXCLUDED.text_params;

DELETE FROM platform.ai_work_link_record_kinds WHERE kind <> ALL (ARRAY['project', 'boqs', 'boq_lines', 'activities', 'progress', 'tasks', 'meetings', 'documents', 'roster', 'attendance', 'timesheets', 'pipeline_tasks', 'people']::text[]);
INSERT INTO platform.ai_work_link_record_kinds (kind, money_columns, filters) VALUES
  ('project', ARRAY['project_value', 'vat_rate_percent', 'retention_percent']::text[], '{"fields":{},"sort":[]}'::jsonb),
  ('boqs', ARRAY['contract_value_override']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"version":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["version","created_at"]}'::jsonb),
  ('boq_lines', ARRAY['rate', 'amount', 'material_cost', 'labour_cost', 'equipment_cost', 'budget_percentage', 'vendor_amount', 'material_amount', 'manpower_amount', 'rate_project', 'rate_contract']::text[], '{"fields":{"boq_id":{"type":"text","ops":["eq","in"]},"item_code":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]},"rate":{"type":"numeric","ops":["eq","gt","lt"]},"amount":{"type":"numeric","ops":["eq","gt","lt"]},"budget_percentage":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["created_at","quantity","rate","amount","budget_percentage"]}'::jsonb),
  ('activities', '{}'::text[], '{"fields":{"category_id":{"type":"text","ops":["eq","in"]},"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at"]}'::jsonb),
  ('progress', '{}'::text[], '{"fields":{"entry_date":{"type":"date","ops":["eq","gt","lt"]},"activity_id":{"type":"text","ops":["eq","in"]},"boq_line_item_id":{"type":"text","ops":["eq","in"]},"percent_complete":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["entry_date","percent_complete","created_at"]}'::jsonb),
  ('tasks', '{}'::text[], '{"fields":{"status_id":{"type":"text","ops":["eq","in"]},"priority":{"type":"text","ops":["eq","in"]},"assignee_id":{"type":"text","ops":["eq","in"]},"number":{"type":"numeric","ops":["eq","gt","lt"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"completion_percentage":{"type":"numeric","ops":["eq","gt","lt"]},"is_archived":{"type":"boolean","ops":["eq"]}},"sort":["number","priority","completion_percentage","created_at","updated_at"]}'::jsonb),
  ('meetings', '{}'::text[], '{"fields":{"scheduled_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["scheduled_at","created_at"]}'::jsonb),
  ('documents', '{}'::text[], '{"fields":{"category":{"type":"text","ops":["eq","in"]},"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at","version_number"]}'::jsonb),
  ('roster', ARRAY['daily_rate']::text[], '{"fields":{"trade":{"type":"text","ops":["eq","in"]},"is_active":{"type":"boolean","ops":["eq"]},"daily_rate":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["name","created_at","daily_rate"]}'::jsonb),
  ('attendance', ARRAY['daily_cost']::text[], '{"fields":{"attendance_date":{"type":"date","ops":["eq","gt","lt"]},"roster_id":{"type":"text","ops":["eq","in"]},"status":{"type":"text","ops":["eq","in"]},"daily_cost":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["attendance_date","created_at","daily_cost"]}'::jsonb),
  ('timesheets', ARRAY['hourly_rate_snapshot', 'invoice_item_id']::text[], '{"fields":{"spent_on":{"type":"date","ops":["eq","gt","lt"]},"issue_id":{"type":"text","ops":["eq","in"]},"user_id":{"type":"text","ops":["eq","in"]},"activity_type":{"type":"text","ops":["eq","in"]},"hours":{"type":"numeric","ops":["eq","gt","lt"]},"hourly_rate_snapshot":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["spent_on","hours","created_at"]}'::jsonb),
  ('pipeline_tasks', ARRAY['params', 'result']::text[], '{"fields":{"function_id":{"type":"text","ops":["eq","in"]},"status":{"type":"text","ops":["eq","in"]},"created_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["created_at","sequence","status"],"omit_when_hidden":["params","result"]}'::jsonb),
  ('people', '{}'::text[], '{"fields":{"role":{"type":"text","ops":["eq","in"]}},"sort":["name"]}'::jsonb)
ON CONFLICT (kind) DO UPDATE SET money_columns = EXCLUDED.money_columns, filters = EXCLUDED.filters;

CREATE OR REPLACE FUNCTION public.ai_work_link__registry_version()
RETURNS text
LANGUAGE sql IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $fn$ SELECT '4fb552013e210a5772a45da664b44199c665cc0753d80f0d3f4580dc4e8ac0a3'::text $fn$;

REVOKE ALL ON FUNCTION public.ai_work_link__registry_version() FROM PUBLIC, anon, authenticated, app_runtime;
GRANT EXECUTE ON FUNCTION public.ai_work_link__registry_version() TO service_role;
-- END GENERATED

COMMIT;
