-- PRE-APPROVED-LIVE-DDL: Owner (Rajat Agarwal) directive of 2026-10-02 in a live Claude Code session: "the external AI / internal AI can make the complete project, edit, delete, update, etc for that user as per role and its organization" and "the external AI / internal AI cannot code on this"; this migration is that work (package lf-b2-ai-crud, requirements R5, R6, R7).
-- PROJEXA AI CREATE / UPDATE / DELETE: the ninth generated seed of the Universal AI Work Link's function allow-list, plus the per-person switch
-- "let my AI act without asking".
--
-- WHAT
--   1. platform.ai_work_link_functions   the 113 rows of 0669 plus 27 new functions (140 rows, 122 on links), from src/lib/pipeline/function-registry.ts
--                                        and scripts/gen-ai-link-registry.data.ts:
--                                          level 1 (direct): update_boq, create_sprint, update_sprint, add_sprint_task, remove_sprint_task,
--                                                            update_time_entry, update_mom_details, update_meeting, update_room, update_placement,
--                                                            update_mood_board, update_permit
--                                          level 2 (a draft the person confirms): delete_boq, update_boq_line_amounts, delete_progress_entry,
--                                                            archive_task, close_sprint, delete_time_entry, dispose_document, delete_mom,
--                                                            update_material, remove_room, remove_placement, update_floor_plan_status,
--                                                            remove_mood_board_item, delete_permit, archive_project
--                                        The other 113 rows are written again exactly as 0669 wrote them. The record kinds are the 33 of 0643, unchanged.
--   2. public.ai_work_link__registry_version()  the sha256 of exactly those rows.
--   3. (GROUP 2, below the generated block) platform.ai_work_link_person_settings and the functions that read and set a person's
--      act_without_asking switch, and the record_intent / intent_claim predicates that use it.
--
-- WHY. Before this file an AI could create almost everything but delete nothing and update little (BUILD-002 had decided to keep every delete off
-- links). The owner's order of 2026-10-02 SUPERSEDES that BUILD-002 plan decision: the person's AI may now create, update, delete and archive
-- what the person may, as per role and organisation. Every delete, removal and archive is level 2 (a draft the person confirms) unless the PERSON
-- has switched "let my AI act without asking" on. The coverage list, with what is not done and why, is ai-os/AI_CRUD_COVERAGE.md.
-- Nothing here lets an AI change the app's code, its release bundle or any file (the owner's "cannot code on this"): every new function writes
-- project data through the same service the app's own route calls.
--
-- LINKS ALREADY MINTED KEEP THEIR OLD FUNCTION CEILING. A link's allowed_functions is fixed when it is minted, so a link minted before this file
-- does not carry the 27 new functions: the person re-mints a link (or makes a new user link) to give their AI the new functions.
--
-- ERRORS. None new from the generated block. The GROUP 2 functions raise the same AW4xx codes as the functions of 0668 they sit beside.
--
-- GRANTS. The generated block grants EXECUTE on public.ai_work_link__registry_version() to service_role only, as every earlier seed did. GROUP 2: see
-- its own comments; the new table has RLS forced and no grants (only SECURITY DEFINER functions read or write it).
--
-- GENERATED. The block between the BEGIN and END GENERATED markers is written by scripts/gen-ai-link-registry.ts (CURRENT_SEED_MIGRATION
-- points here). Do not edit it by hand. `bun scripts/gen-ai-link-registry.ts --check` and src/scripts/gen-ai-link-registry.test.ts fail
-- while this block, or either JSON file under supabase/functions/ai-work-link/, differs from what the registry generates.
--
-- IDEMPOTENT: rows are upserted by key (INSERT ... ON CONFLICT DO UPDATE) and rows of a function or kind the block no longer names are deleted, so
-- applying this file twice, or after 0669, leaves the tables exactly as the block says. Nothing here touches platform.ai_work_link_settings.
--
-- DATA LOSS: none. 27 rows are added and a function body is replaced; GROUP 2 adds an empty table and re-creates four functions of 0668.
--
-- HOW IT IS APPLIED: by the PM through the Supabase MCP, after the always-aborted rehearsal passed and migrations up to 0683 are applied. This
-- migration is written by an engineer agent (cloud package lf-b2-ai-crud) and is not applied by it.
--
-- ROLLBACK: drizzle/down/0685_awl_ai_crud.down.sql

BEGIN;

SET LOCAL lock_timeout = '5s';

-- BEGIN GENERATED BY scripts/gen-ai-link-registry.ts (do not edit by hand; run the generator)
-- registry version 1ebba97f7025068298c0f1a5b466e35c30f35ef8b1350ff3b174ad71d1f54763
DELETE FROM platform.ai_work_link_functions WHERE function_id <> ALL (ARRAY['add_boq_lines', 'add_meeting_action_item', 'add_meeting_outcome', 'add_mood_board_item', 'add_room', 'add_roster_entry', 'add_sprint_task', 'answer_rfi', 'apply_boq_import', 'approve_kpi_entry', 'approve_timesheet', 'archive_project', 'archive_task', 'capture_artifact', 'capture_schedule_baseline', 'close_rfi', 'close_sprint', 'compare_boq_revisions', 'compare_schedule_baseline', 'create_activity', 'create_boq', 'create_boq_revision', 'create_change_order', 'create_document', 'create_drawing', 'create_ffe_item', 'create_floor_plan', 'create_material', 'create_meeting', 'create_milestone', 'create_mom', 'create_mood_board', 'create_permit', 'create_progress_category', 'create_progress_claim', 'create_project', 'create_punch_list_item', 'create_rfi', 'create_schedule_task', 'create_site_diary', 'create_site_instruction', 'create_sprint', 'create_submittal', 'create_wiki_page', 'delete_boq', 'delete_mom', 'delete_permit', 'delete_progress_entry', 'delete_time_entry', 'detect_construction_budget_schedule_risk', 'dispose_document', 'draft_progress_claim', 'generate_construction_progress_summary', 'get_billing_due_queue', 'get_boq_line_items', 'get_change_order', 'get_compliance_stats', 'get_construction_budget_status', 'get_construction_kpi_status', 'get_construction_project_dashboard', 'get_daily_progress_report', 'get_designer_timesheet_report', 'get_ffe_margin_summary', 'get_gantt_schedule', 'get_manpower_cost_report', 'get_material_cost_report', 'get_overdue_items', 'get_project_analysis', 'get_project_budget_variance', 'get_project_exceptions', 'get_project_schedule', 'get_sales_pipeline_overview', 'link_roster_employee', 'list_billing_claims', 'list_change_orders', 'list_compliance_items', 'list_customers', 'list_delayed_activities', 'list_departments', 'list_gst_import_batches', 'list_gst_returns', 'list_leads', 'list_milestones', 'list_notices', 'list_opportunities', 'list_over_budget_projects', 'list_sales_orders', 'mark_punch_item_ready', 'place_furniture', 'preview_boq_import', 'publish_mom', 'record_attendance', 'record_attendance_batch', 'record_customer_approval', 'record_customer_complaint', 'record_material_issue', 'record_material_receipt', 'record_timesheet', 'record_vendor_dispute', 'record_work_progress', 'reject_progress_claim', 'reject_timesheet', 'remove_mood_board_item', 'remove_placement', 'remove_room', 'remove_sprint_task', 'review_budget', 'review_submittal', 'run_named_report', 'seal_boq', 'set_progress_drawing', 'submit_boq_for_approval', 'submit_change_order_for_approval', 'submit_kpi_entry', 'submit_progress_claim', 'submit_timesheet', 'update_boq', 'update_boq_line_amounts', 'update_document_metadata', 'update_ffe_status', 'update_floor_plan_status', 'update_line_item_budget', 'update_material', 'update_meeting', 'update_milestone', 'update_mom_details', 'update_mom_minutes', 'update_mood_board', 'update_permit', 'update_placement', 'update_progress_entry', 'update_project', 'update_room', 'update_roster_entry', 'update_sprint', 'update_task', 'update_time_entry', 'update_wiki_page', 'verify_punch_item_closed', 'void_material_receipt']::text[]);
INSERT INTO platform.ai_work_link_functions (function_id, product, kind, link_level, money_sensitive, min_role_rank, excluded_reason, text_params) VALUES
  ('add_boq_lines', 'projexa', 'write', 2, true, 2, NULL, '{}'::text[]),
  ('add_meeting_action_item', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('add_meeting_outcome', 'projexa', 'write', 1, false, 2, NULL, ARRAY['notes']::text[]),
  ('add_mood_board_item', 'projexa', 'write', 1, false, 2, NULL, ARRAY['label', 'notes']::text[]),
  ('add_room', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name']::text[]),
  ('add_roster_entry', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'trade', 'employeeCode']::text[]),
  ('add_sprint_task', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('answer_rfi', 'projexa', 'write', 2, false, 2, NULL, ARRAY['answer']::text[]),
  ('apply_boq_import', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('approve_kpi_entry', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('approve_timesheet', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('archive_project', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('archive_task', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('capture_artifact', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'text']::text[]),
  ('capture_schedule_baseline', 'projexa', 'write', 2, false, 3, NULL, ARRAY['name']::text[]),
  ('close_rfi', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('close_sprint', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('compare_boq_revisions', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('compare_schedule_baseline', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('create_activity', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'unit']::text[]),
  ('create_boq', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_boq_revision', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title']::text[]),
  ('create_change_order', 'projexa', 'write', 2, true, 2, NULL, ARRAY['title', 'description', 'reason', 'trade']::text[]),
  ('create_document', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'category']::text[]),
  ('create_drawing', 'projexa', 'write', 2, false, 2, NULL, ARRAY['name', 'externalUrl', 'drawingNo', 'rev', 'discipline', 'kind']::text[]),
  ('create_ffe_item', 'projexa', 'write', 2, true, 2, NULL, ARRAY['itemName', 'roomOrArea', 'description', 'sku']::text[]),
  ('create_floor_plan', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'floorLevel']::text[]),
  ('create_material', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'unit', 'spec']::text[]),
  ('create_meeting', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('create_milestone', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('create_mom', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'minutes', 'meetingType', 'attendees', 'agenda']::text[]),
  ('create_mood_board', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'roomOrArea', 'description']::text[]),
  ('create_permit', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'externalUrl', 'permitNumber', 'permitAuthority']::text[]),
  ('create_progress_category', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name']::text[]),
  ('create_progress_claim', 'projexa', 'write', 2, true, 3, NULL, ARRAY['milestoneDescription']::text[]),
  ('create_project', 'projexa', 'write', 2, false, 2, NULL, ARRAY['name', 'description']::text[]),
  ('create_punch_list_item', 'projexa', 'write', 1, false, 2, NULL, ARRAY['description', 'location', 'trade']::text[]),
  ('create_rfi', 'projexa', 'write', 1, false, 2, NULL, ARRAY['subject', 'question']::text[]),
  ('create_schedule_task', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('create_site_diary', 'projexa', 'write', 1, false, 2, NULL, ARRAY['weather', 'workDone', 'visitors', 'issues', 'instructions', 'materialReceived', 'remarks']::text[]),
  ('create_site_instruction', 'projexa', 'write', 2, false, 2, NULL, ARRAY['toContractor', 'description', 'drawingRef']::text[]),
  ('create_sprint', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'goal']::text[]),
  ('create_submittal', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'specSection']::text[]),
  ('create_wiki_page', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'content']::text[]),
  ('delete_boq', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('delete_mom', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('delete_permit', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('delete_progress_entry', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('delete_time_entry', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('detect_construction_budget_schedule_risk', 'projexa', 'read', NULL, false, 0, 'Calls a server-side model (F-2): the internal AI never runs on link traffic.', '{}'::text[]),
  ('dispose_document', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('draft_progress_claim', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('generate_construction_progress_summary', 'projexa', 'read', NULL, false, 0, 'Calls a server-side model (F-2): the internal AI never runs on link traffic.', '{}'::text[]),
  ('get_billing_due_queue', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_boq_line_items', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_change_order', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_compliance_stats', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('get_construction_budget_status', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_construction_kpi_status', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_construction_project_dashboard', 'projexa', 'read', 0, true, 1, NULL, '{}'::text[]),
  ('get_daily_progress_report', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_designer_timesheet_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_ffe_margin_summary', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_gantt_schedule', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_manpower_cost_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('get_material_cost_report', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_overdue_items', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('get_project_analysis', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_budget_variance', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_exceptions', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('get_project_schedule', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('get_sales_pipeline_overview', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('link_roster_employee', 'projexa', 'write', NULL, false, 0, 'An employee id is an organisation-wide HR record (personal data), not project data, so it cannot be checked against the link''s project (spec 9.10, F-3). The internal pipeline runs it for a manager.', '{}'::text[]),
  ('list_billing_claims', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('list_change_orders', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('list_compliance_items', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_customers', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_delayed_activities', 'projexa', 'read', NULL, false, 0, 'Reads the whole organisation, not one project (F-3).', '{}'::text[]),
  ('list_departments', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_gst_import_batches', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_gst_returns', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_leads', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_milestones', 'projexa', 'read', 0, false, 2, NULL, '{}'::text[]),
  ('list_notices', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_opportunities', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('list_over_budget_projects', 'projexa', 'read', NULL, false, 0, 'Reads the whole organisation, not one project (F-3).', '{}'::text[]),
  ('list_sales_orders', 'projexa', 'read', NULL, false, 0, 'Organisation-scoped read, not project data (F-3).', '{}'::text[]),
  ('mark_punch_item_ready', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('place_furniture', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('preview_boq_import', 'projexa', 'read', 0, true, 3, NULL, '{}'::text[]),
  ('publish_mom', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('record_attendance', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('record_attendance_batch', 'projexa', 'write', 1, true, 2, NULL, '{}'::text[]),
  ('record_customer_approval', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('record_customer_complaint', 'projexa', 'write', 2, false, 2, NULL, ARRAY['description', 'category']::text[]),
  ('record_material_issue', 'projexa', 'write', 1, false, 2, NULL, ARRAY['issuedTo', 'note']::text[]),
  ('record_material_receipt', 'projexa', 'write', 2, true, 2, NULL, ARRAY['materialName', 'reference', 'notes', 'spec', 'unit']::text[]),
  ('record_timesheet', 'projexa', 'write', 1, false, 2, NULL, ARRAY['task', 'activityType']::text[]),
  ('record_vendor_dispute', 'projexa', 'write', 2, true, 2, NULL, ARRAY['description']::text[]),
  ('record_work_progress', 'projexa', 'write', 1, false, 2, NULL, ARRAY['remarks']::text[]),
  ('reject_progress_claim', 'projexa', 'write', 2, true, 3, NULL, ARRAY['rejectionReason']::text[]),
  ('reject_timesheet', 'projexa', 'write', 2, false, 3, NULL, ARRAY['rejectionReason']::text[]),
  ('remove_mood_board_item', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('remove_placement', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('remove_room', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('remove_sprint_task', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('review_budget', 'projexa', 'read', NULL, false, 0, 'An alias that duplicates get_construction_budget_status.', '{}'::text[]),
  ('review_submittal', 'projexa', 'write', 2, false, 3, NULL, ARRAY['comments']::text[]),
  ('run_named_report', 'projexa', 'read', 0, true, 2, NULL, '{}'::text[]),
  ('seal_boq', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('set_progress_drawing', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('submit_boq_for_approval', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('submit_change_order_for_approval', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('submit_kpi_entry', 'projexa', 'write', 2, true, 2, NULL, ARRAY['period']::text[]),
  ('submit_progress_claim', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('submit_timesheet', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('update_boq', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('update_boq_line_amounts', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('update_document_metadata', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'category']::text[]),
  ('update_ffe_status', 'projexa', 'write', 2, true, 3, NULL, '{}'::text[]),
  ('update_floor_plan_status', 'projexa', 'write', 2, false, 2, NULL, '{}'::text[]),
  ('update_line_item_budget', 'projexa', 'write', 2, true, 3, NULL, ARRAY['category']::text[]),
  ('update_material', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'unit', 'spec']::text[]),
  ('update_meeting', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title']::text[]),
  ('update_milestone', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('update_mom_details', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'meetingType']::text[]),
  ('update_mom_minutes', 'projexa', 'write', 1, false, 2, NULL, ARRAY['minutes']::text[]),
  ('update_mood_board', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'roomOrArea', 'description']::text[]),
  ('update_permit', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'permitNumber', 'permitAuthority', 'notes']::text[]),
  ('update_placement', 'projexa', 'write', 1, false, 2, NULL, '{}'::text[]),
  ('update_progress_entry', 'projexa', 'write', 1, true, 2, NULL, ARRAY['remarks']::text[]),
  ('update_project', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'description']::text[]),
  ('update_room', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name']::text[]),
  ('update_roster_entry', 'projexa', 'write', 2, true, 2, NULL, ARRAY['name', 'trade', 'skillLevel']::text[]),
  ('update_sprint', 'projexa', 'write', 1, false, 2, NULL, ARRAY['name', 'goal']::text[]),
  ('update_task', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'description']::text[]),
  ('update_time_entry', 'projexa', 'write', 1, true, 2, NULL, ARRAY['activityType', 'comments']::text[]),
  ('update_wiki_page', 'projexa', 'write', 1, false, 2, NULL, ARRAY['title', 'content']::text[]),
  ('verify_punch_item_closed', 'projexa', 'write', 2, false, 3, NULL, '{}'::text[]),
  ('void_material_receipt', 'projexa', 'write', 2, true, 3, NULL, ARRAY['reason']::text[])
ON CONFLICT (function_id) DO UPDATE SET
  product = EXCLUDED.product, kind = EXCLUDED.kind, link_level = EXCLUDED.link_level, money_sensitive = EXCLUDED.money_sensitive,
  min_role_rank = EXCLUDED.min_role_rank, excluded_reason = EXCLUDED.excluded_reason, text_params = EXCLUDED.text_params;

DELETE FROM platform.ai_work_link_record_kinds WHERE kind <> ALL (ARRAY['project', 'boqs', 'boq_lines', 'activities', 'progress', 'tasks', 'meetings', 'documents', 'roster', 'attendance', 'timesheets', 'pipeline_tasks', 'people', 'rfis', 'submittals', 'punch_list', 'change_orders', 'site_diaries', 'site_instructions', 'milestones', 'progress_claims', 'interim_bills', 'materials', 'material_receipts', 'material_issues', 'kpi_entries', 'expenses', 'drawings', 'permits', 'meeting_minutes', 'wiki_pages', 'ffe_items', 'schedule_baselines']::text[]);
INSERT INTO platform.ai_work_link_record_kinds (kind, money_columns, filters) VALUES
  ('project', ARRAY['project_value', 'vat_rate_percent', 'retention_percent']::text[], '{"fields":{},"sort":[]}'::jsonb),
  ('boqs', ARRAY['contract_value_override']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"version":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["version","created_at"]}'::jsonb),
  ('boq_lines', ARRAY['rate', 'amount', 'material_cost', 'labour_cost', 'equipment_cost', 'budget_percentage', 'vendor_amount', 'material_amount', 'manpower_amount', 'rate_project', 'rate_contract', 'vendor_id', 'overhead_percent', 'profit_percent']::text[], '{"fields":{"boq_id":{"type":"text","ops":["eq","in"]},"item_code":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]},"rate":{"type":"numeric","ops":["eq","gt","lt"]},"amount":{"type":"numeric","ops":["eq","gt","lt"]},"budget_percentage":{"type":"numeric","ops":["eq","gt","lt"]},"breakdown_percentage":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["created_at","quantity","rate","amount","budget_percentage"]}'::jsonb),
  ('activities', '{}'::text[], '{"fields":{"category_id":{"type":"text","ops":["eq","in"]},"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at"]}'::jsonb),
  ('progress', '{}'::text[], '{"fields":{"entry_date":{"type":"date","ops":["eq","gt","lt"]},"activity_id":{"type":"text","ops":["eq","in"]},"boq_line_item_id":{"type":"text","ops":["eq","in"]},"percent_complete":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["entry_date","percent_complete","created_at"]}'::jsonb),
  ('tasks', '{}'::text[], '{"fields":{"status_id":{"type":"text","ops":["eq","in"]},"priority":{"type":"text","ops":["eq","in"]},"assignee_id":{"type":"text","ops":["eq","in"]},"number":{"type":"numeric","ops":["eq","gt","lt"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"completion_percentage":{"type":"numeric","ops":["eq","gt","lt"]},"is_archived":{"type":"boolean","ops":["eq"]}},"sort":["number","priority","completion_percentage","created_at","updated_at"]}'::jsonb),
  ('meetings', '{}'::text[], '{"fields":{"scheduled_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["scheduled_at","created_at"]}'::jsonb),
  ('documents', '{}'::text[], '{"fields":{"category":{"type":"text","ops":["eq","in"]},"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at","version_number"]}'::jsonb),
  ('roster', ARRAY['daily_rate']::text[], '{"fields":{"trade":{"type":"text","ops":["eq","in"]},"is_active":{"type":"boolean","ops":["eq"]},"daily_rate":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["name","created_at","daily_rate"]}'::jsonb),
  ('attendance', ARRAY['daily_cost']::text[], '{"fields":{"attendance_date":{"type":"date","ops":["eq","gt","lt"]},"roster_id":{"type":"text","ops":["eq","in"]},"status":{"type":"text","ops":["eq","in"]},"daily_cost":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["attendance_date","created_at","daily_cost"]}'::jsonb),
  ('timesheets', ARRAY['hourly_rate_snapshot', 'invoice_item_id']::text[], '{"fields":{"spent_on":{"type":"date","ops":["eq","gt","lt"]},"issue_id":{"type":"text","ops":["eq","in"]},"user_id":{"type":"text","ops":["eq","in"]},"activity_type":{"type":"text","ops":["eq","in"]},"hours":{"type":"numeric","ops":["eq","gt","lt"]},"hourly_rate_snapshot":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["spent_on","hours","created_at"]}'::jsonb),
  ('pipeline_tasks', ARRAY['params', 'result']::text[], '{"fields":{"function_id":{"type":"text","ops":["eq","in"]},"status":{"type":"text","ops":["eq","in"]},"created_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["created_at","sequence","status"],"omit_when_hidden":["params","result"]}'::jsonb),
  ('people', '{}'::text[], '{"fields":{"role":{"type":"text","ops":["eq","in"]}},"sort":["name"]}'::jsonb),
  ('rfis', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"ball_in_court":{"type":"text","ops":["eq","in"]},"assigned_to_id":{"type":"text","ops":["eq","in"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"number":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at"]}'::jsonb),
  ('submittals', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"type":{"type":"text","ops":["eq","in"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"number":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at"]}'::jsonb),
  ('punch_list', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"priority":{"type":"text","ops":["eq","in"]},"trade":{"type":"text","ops":["eq","in"]},"assigned_to_id":{"type":"text","ops":["eq","in"]},"due_date":{"type":"date","ops":["eq","gt","lt"]},"number":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at"]}'::jsonb),
  ('change_orders', ARRAY['cost_impact']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"trade":{"type":"text","ops":["eq","in"]},"number":{"type":"numeric","ops":["eq","gt","lt"]},"cost_impact":{"type":"numeric","ops":["eq","gt","lt"]},"schedule_impact_days":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["number","created_at","cost_impact","schedule_impact_days"]}'::jsonb),
  ('site_diaries', '{}'::text[], '{"fields":{"diary_date":{"type":"date","ops":["eq","gt","lt"]}},"sort":["diary_date","created_at"]}'::jsonb),
  ('site_instructions', '{}'::text[], '{"fields":{"issue_date":{"type":"date","ops":["eq","gt","lt"]},"si_number":{"type":"numeric","ops":["eq","gt","lt"]},"cost_impact":{"type":"boolean","ops":["eq"]},"time_impact":{"type":"boolean","ops":["eq"]}},"sort":["si_number","issue_date","created_at"]}'::jsonb),
  ('milestones', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"target_date":{"type":"date","ops":["eq","gt","lt"]}},"sort":["name","created_at"]}'::jsonb),
  ('progress_claims', ARRAY['retention_percent', 'customer_id', 'interim_bill_id']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"boq_id":{"type":"text","ops":["eq","in"]},"scheduled_date":{"type":"date","ops":["eq","gt","lt"]},"retention_percent":{"type":"numeric","ops":["eq","gt","lt"]},"customer_id":{"type":"text","ops":["eq","in"]}},"sort":["scheduled_date","created_at","retention_percent"]}'::jsonb),
  ('interim_bills', ARRAY['retention_percent', 'gross_amount', 'retention_amount', 'net_payable', 'retention_released_amount', 'sales_invoice_id']::text[], '{"fields":{"boq_id":{"type":"text","ops":["eq","in"]},"bill_number":{"type":"numeric","ops":["eq","gt","lt"]},"bill_date":{"type":"date","ops":["eq","gt","lt"]},"gross_amount":{"type":"numeric","ops":["eq","gt","lt"]},"net_payable":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["bill_number","bill_date","created_at","gross_amount","net_payable"]}'::jsonb),
  ('materials', ARRAY['unit_cost']::text[], '{"fields":{"name":{"type":"text","ops":["eq"]},"is_active":{"type":"boolean","ops":["eq"]},"unit_cost":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["name","created_at","unit_cost"]}'::jsonb),
  ('material_receipts', ARRAY['unit_cost', 'vendor_id']::text[], '{"fields":{"material_id":{"type":"text","ops":["eq","in"]},"received_date":{"type":"date","ops":["eq","gt","lt"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]},"unit_cost":{"type":"numeric","ops":["eq","gt","lt"]},"vendor_id":{"type":"text","ops":["eq","in"]}},"sort":["received_date","created_at","quantity"]}'::jsonb),
  ('material_issues', '{}'::text[], '{"fields":{"material_id":{"type":"text","ops":["eq","in"]},"boq_line_item_id":{"type":"text","ops":["eq","in"]},"issued_date":{"type":"date","ops":["eq","gt","lt"]},"quantity":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["issued_date","created_at","quantity"]}'::jsonb),
  ('kpi_entries', ARRAY['target_value', 'actual_value']::text[], '{"fields":{"kpi_definition_id":{"type":"text","ops":["eq","in"]},"metric_name":{"type":"text","ops":["eq","in"]},"period":{"type":"text","ops":["eq","in"]},"approval_status":{"type":"text","ops":["eq","in"]},"actual_value":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["created_at","period","actual_value"]}'::jsonb),
  ('expenses', ARRAY['amount', 'description']::text[], '{"fields":{"expense_head":{"type":"text","ops":["eq","in"]},"expense_date":{"type":"date","ops":["eq","gt","lt"]},"is_rework":{"type":"boolean","ops":["eq"]},"amount":{"type":"numeric","ops":["eq","gt","lt"]}},"sort":["expense_date","created_at","amount"]}'::jsonb),
  ('drawings', '{}'::text[], '{"fields":{"drawing_no":{"type":"text","ops":["eq","in"]},"revision":{"type":"text","ops":["eq","in"]},"drawing_status":{"type":"text","ops":["eq","in"]},"discipline":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]}},"sort":["name","created_at","version_number"]}'::jsonb),
  ('permits', '{}'::text[], '{"fields":{"permit_number":{"type":"text","ops":["eq","in"]},"permit_authority":{"type":"text","ops":["eq","in"]},"expiry_date":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["name","created_at"]}'::jsonb),
  ('meeting_minutes', '{}'::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"meeting_type":{"type":"text","ops":["eq","in"]},"scheduled_at":{"type":"timestamptz","ops":["gt","lt"]}},"sort":["scheduled_at","created_at"]}'::jsonb),
  ('wiki_pages', '{}'::text[], '{"fields":{"slug":{"type":"text","ops":["eq","in"]},"title":{"type":"text","ops":["eq"]}},"sort":["slug","title","updated_at"]}'::jsonb),
  ('ffe_items', ARRAY['unit_cost', 'unit_price', 'vendor_id']::text[], '{"fields":{"status":{"type":"text","ops":["eq","in"]},"category":{"type":"text","ops":["eq","in"]},"room_or_area":{"type":"text","ops":["eq","in"]},"unit_cost":{"type":"numeric","ops":["eq","gt","lt"]},"unit_price":{"type":"numeric","ops":["eq","gt","lt"]},"vendor_id":{"type":"text","ops":["eq","in"]}},"sort":["item_name","created_at","unit_cost","unit_price"]}'::jsonb),
  ('schedule_baselines', '{}'::text[], '{"fields":{"name":{"type":"text","ops":["eq"]}},"sort":["name","created_at"]}'::jsonb)
ON CONFLICT (kind) DO UPDATE SET money_columns = EXCLUDED.money_columns, filters = EXCLUDED.filters;

CREATE OR REPLACE FUNCTION public.ai_work_link__registry_version()
RETURNS text
LANGUAGE sql IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $fn$ SELECT '1ebba97f7025068298c0f1a5b466e35c30f35ef8b1350ff3b174ad71d1f54763'::text $fn$;

REVOKE ALL ON FUNCTION public.ai_work_link__registry_version() FROM PUBLIC, anon, authenticated, app_runtime;
GRANT EXECUTE ON FUNCTION public.ai_work_link__registry_version() TO service_role;
-- END GENERATED

-- =============================================================================================================================================
-- GROUP 2: "let my AI act without asking", a switch that belongs to ONE PERSON.
--
-- Before this file the only switches were the global kill switch (platform.ai_work_link_settings.writes_enabled) and each link's own ceiling
-- (authority_level 0 or 1, fixed at mint). A level-2 function was a draft on every link, always. Now a person may switch on "act without asking":
-- then THEIR links (and only theirs) may run a level-2 function directly, exactly as a level-1 one, through POST /actions. Every other rule stays:
--   - the kill switch: with writes off every link is at effective level 0, nothing runs directly and the claim answers not_enabled first;
--   - the link's own ceiling: a link made at level 0 stays drafts-only whatever the person's switch says (effective level 0);
--   - the role: the effective function list is still the person's rank, read now; a person below the member rank has effective level 0;
--   - the switch is read NOW, at record time and again at claim time, so switching it off stops an action recorded a moment before (ROLE_CHANGED);
--   - another person's switch has no effect on this person's links, and a switch kept for another organisation has none either (the row names
--     the organisation, and it must be the person's organisation now).
-- Default: off. A row exists only once the person has used the switch.
--
--   platform.ai_work_link_person_settings (user_id PK, org_id, act_without_asking, updated_at)   RLS forced, no policy, no grant: only the SECURITY
--       DEFINER functions below read or write it.
--   public.ai_work_link__acts_without_asking(user_id, org_id)   the person's switch, false when absent (owner-only).
--   public.ai_work_link__direct_ok(ctx, link_level)   THE predicate a direct action needs: effective level 1, and a level-1 function, or a level-2
--       function with the person's switch on (owner-only). It replaces `link_level = 1` in record_intent and in intent_claim.
--   RE-CREATED ai_work_link__resolve and ai_work_link__live (0668 bodies, kept equal): the context also says `act_without_asking`, so the Edge
--       function can tell the AI that a level-2 change may be made directly. Nothing else in them changes.
--   RE-CREATED ai_work_link_record_intent and ai_work_link_intent_claim (0668 bodies): the one predicate above, nothing else.
--   public.ai_work_link_person_setting(user_id)         the person's switch, for the app route that has resolved the person from their PROJEXA
--       session (supabase/functions/ai-work-link/person-settings.ts, the same session and person gates as the confirm route). service_role only.
--   public.ai_work_link_person_setting_set(user_id, on)  sets it. Refuses AW403 USER_NOT_ACTIVE for a person who is not an active user of an
--       organisation. service_role only.
-- ERRORS: AW403 USER_NOT_ACTIVE (setter); AW400 BAD_VALUE (setter, a null value). The re-created functions raise what they raised.
-- GRANTS: the helpers are owner-only; the two setting functions are granted to service_role alone.
-- =============================================================================================================================================

CREATE TABLE IF NOT EXISTS platform.ai_work_link_person_settings (
  user_id text PRIMARY KEY,
  org_id text NOT NULL,
  act_without_asking boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE platform.ai_work_link_person_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform.ai_work_link_person_settings FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE platform.ai_work_link_person_settings FROM PUBLIC, anon, authenticated, app_runtime, service_role;

CREATE OR REPLACE FUNCTION public.ai_work_link__acts_without_asking(p_user_id text, p_org_id text)
RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
BEGIN
  RETURN coalesce((
    SELECT s.act_without_asking FROM platform.ai_work_link_person_settings s
    WHERE s.user_id = p_user_id AND s.org_id = p_org_id), false);
END
$fn$;

CREATE OR REPLACE FUNCTION public.ai_work_link__direct_ok(p_ctx jsonb, p_link_level integer)
RETURNS boolean
LANGUAGE plpgsql IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $fn$
BEGIN
  RETURN coalesce((p_ctx ->> 'effective_level')::integer, 0) >= 1
     AND (p_link_level = 1 OR (p_link_level = 2 AND coalesce((p_ctx ->> 'act_without_asking')::boolean, false)));
END
$fn$;

CREATE OR REPLACE FUNCTION public.ai_work_link__resolve(p_token text)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
DECLARE
  v_hash text := public.ai_work_link__hash_token(p_token);
  v_l record;
  v_u record;
  v_p record;
  v_pid text;
  v_pname text;
  v_rank integer;
  v_writes boolean;
  v_level integer;
  v_fns text[];
  v_gone constant jsonb := jsonb_build_object('status', 'gone');
BEGIN
  IF v_hash IS NULL THEN
    RETURN v_gone;
  END IF;
  SELECT l.id, l.org_id, l.user_id, l.project_id, l.scope, l.status, l.expires_at, l.authority_level, l.allowed_functions, l.hide_personal, l.label
    INTO v_l
  FROM platform.user_ai_links l
  WHERE l.token_hash = v_hash AND l.product = 'projexa';
  IF NOT FOUND OR v_l.status <> 'active' OR v_l.expires_at IS NULL OR v_l.expires_at <= now() THEN
    RETURN v_gone;
  END IF;

  -- PMD-33: a link acts as exactly one person, so it stops when that person is no longer an active user of the organisation
  SELECT u.id, u.name, u.role::text AS role, u.is_active, u.org_id INTO v_u
  FROM compliance.users u WHERE u.id = v_l.user_id;
  IF NOT FOUND OR NOT v_u.is_active OR v_u.org_id IS DISTINCT FROM v_l.org_id THEN
    RETURN v_gone;
  END IF;

  IF v_l.scope = 'user' THEN
    -- a user link has no project of its own: each project it works in is bound and checked by ai_work_link__bind on that call
    v_pid := NULL;
    v_pname := NULL;
  ELSE
    -- the project still exists in the organisation and is still readable by this person (spec 10.3)
    SELECT pr.id, pr.name, pr.org_id, pr.access_level::text AS access_level, pr.lead_user_id INTO v_p
    FROM compliance.projects pr WHERE pr.id = v_l.project_id;
    IF NOT FOUND OR v_p.org_id IS DISTINCT FROM v_l.org_id
       OR NOT public.ai_work_link__can_read_project(v_p.access_level, v_p.lead_user_id, v_u.id, v_u.role) THEN
      RETURN v_gone;
    END IF;
    v_pid := v_p.id;
    v_pname := v_p.name;
  END IF;

  v_rank := public.ai_work_link__role_rank(v_u.role);
  SELECT coalesce((SELECT s.writes_enabled FROM platform.ai_work_link_settings s WHERE s.id), false) INTO v_writes;

  -- spec 10.9: level 0 while no executor exists, and for any person below rank 2; otherwise the ceiling chosen at mint
  v_level := CASE WHEN NOT v_writes OR v_rank < 2 THEN 0 ELSE v_l.authority_level END;

  v_fns := public.ai_work_link__fns(v_l.scope, false, v_l.allowed_functions, v_rank);

  RETURN jsonb_build_object(
    'status', 'ok',
    'link_id', v_l.id,
    'scope', v_l.scope,
    'org_id', v_l.org_id,
    'user_id', v_u.id,
    'user_name', v_u.name,
    'project_id', v_pid,
    'project_name', v_pname,
    'live_role', v_u.role,
    'live_rank', v_rank,
    'authority_level', v_l.authority_level,
    'allowed_functions', to_jsonb(v_l.allowed_functions),
    'effective_level', v_level,
    'effective_functions', to_jsonb(v_fns),
    'money_visible', v_rank >= 3,
    'hide_personal', v_l.hide_personal,
    'label', v_l.label,
    'expires_at', to_char(v_l.expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'writes_enabled', v_writes,
    -- lf-b2-ai-crud: the person's own switch, read now (it decides nothing while the effective level is 0)
    'act_without_asking', public.ai_work_link__acts_without_asking(v_u.id, v_l.org_id));
END
$fn$;

CREATE OR REPLACE FUNCTION public.ai_work_link__live(p_link_id text)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
DECLARE
  v_l record;
  v_u record;
  v_p record;
  v_pid text;
  v_pname text;
  v_rank integer;
  v_writes boolean;
  v_level integer;
  v_fns text[];
  v_gone constant jsonb := jsonb_build_object('status', 'gone');
BEGIN
  IF p_link_id IS NULL THEN
    RETURN v_gone;
  END IF;
  SELECT l.id, l.org_id, l.user_id, l.project_id, l.scope, l.status, l.expires_at, l.authority_level, l.allowed_functions, l.hide_personal, l.label
    INTO v_l
  FROM platform.user_ai_links l
  WHERE l.id = p_link_id AND l.product = 'projexa';
  IF NOT FOUND OR v_l.status <> 'active' OR v_l.expires_at IS NULL OR v_l.expires_at <= now() THEN
    RETURN v_gone;
  END IF;

  SELECT u.id, u.name, u.role::text AS role, u.is_active, u.org_id INTO v_u
  FROM compliance.users u WHERE u.id = v_l.user_id;
  IF NOT FOUND OR NOT v_u.is_active OR v_u.org_id IS DISTINCT FROM v_l.org_id THEN
    RETURN v_gone;
  END IF;

  IF v_l.scope = 'user' THEN
    v_pid := NULL;
    v_pname := NULL;
  ELSE
    SELECT pr.id, pr.name, pr.org_id, pr.access_level::text AS access_level, pr.lead_user_id INTO v_p
    FROM compliance.projects pr WHERE pr.id = v_l.project_id;
    IF NOT FOUND OR v_p.org_id IS DISTINCT FROM v_l.org_id
       OR NOT public.ai_work_link__can_read_project(v_p.access_level, v_p.lead_user_id, v_u.id, v_u.role) THEN
      RETURN v_gone;
    END IF;
    v_pid := v_p.id;
    v_pname := v_p.name;
  END IF;

  v_rank := public.ai_work_link__role_rank(v_u.role);
  SELECT coalesce((SELECT s.writes_enabled FROM platform.ai_work_link_settings s WHERE s.id), false) INTO v_writes;
  v_level := CASE WHEN NOT v_writes OR v_rank < 2 THEN 0 ELSE v_l.authority_level END;

  v_fns := public.ai_work_link__fns(v_l.scope, false, v_l.allowed_functions, v_rank);

  RETURN jsonb_build_object(
    'status', 'ok',
    'link_id', v_l.id,
    'scope', v_l.scope,
    'org_id', v_l.org_id,
    'user_id', v_u.id,
    'user_name', v_u.name,
    'project_id', v_pid,
    'project_name', v_pname,
    'live_role', v_u.role,
    'live_rank', v_rank,
    'authority_level', v_l.authority_level,
    'allowed_functions', to_jsonb(v_l.allowed_functions),
    'effective_level', v_level,
    'effective_functions', to_jsonb(v_fns),
    'money_visible', v_rank >= 3,
    'hide_personal', v_l.hide_personal,
    'label', v_l.label,
    'expires_at', to_char(v_l.expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'writes_enabled', v_writes,
    'act_without_asking', public.ai_work_link__acts_without_asking(v_u.id, v_l.org_id));
END
$fn$;

CREATE OR REPLACE FUNCTION public.ai_work_link_record_intent(
  p_token text, p_kind text, p_function_id text, p_params jsonb, p_idempotency_key text DEFAULT NULL, p_project_id text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
DECLARE
  v_ctx jsonb := public.ai_work_link__require_in(p_token, p_project_id, false);
  v_link text := v_ctx ->> 'link_id';
  v_project text := v_ctx ->> 'project_id';
  v_now timestamptz := clock_timestamp();
  v_fn record;
  v_key text;
  v_existing record;
  v_id text := replace(gen_random_uuid()::text, '-', '');
  v_status text;
  v_expires timestamptz;
  v_confirm text;
  v_confirm_hash text;
  v_hour integer;
  v_day integer;
  v_projects integer;
  v_inserted text;
BEGIN
  IF p_kind IS NULL OR p_kind NOT IN ('action', 'draft') THEN
    RAISE EXCEPTION 'BAD_KIND' USING ERRCODE = 'AW400';
  END IF;
  IF p_params IS NULL OR jsonb_typeof(p_params) <> 'object' OR octet_length(p_params::text) > 8192 THEN
    RAISE EXCEPTION 'BAD_PARAMS' USING ERRCODE = 'AW400';
  END IF;
  -- the effective list of THIS context: a user link outside a project holds create_project and nothing else, inside one every function
  -- but create_project, a project link every function but create_project. So a draft with no project can only be a new project.
  IF p_function_id IS NULL
     OR NOT (p_function_id = ANY (ARRAY(SELECT jsonb_array_elements_text(v_ctx -> 'effective_functions')))) THEN
    RAISE EXCEPTION 'FUNCTION_NOT_ON_LINK' USING ERRCODE = 'AW403';
  END IF;
  SELECT f.function_id, f.kind, f.link_level INTO v_fn
  FROM platform.ai_work_link_functions f WHERE f.function_id = p_function_id;
  IF v_fn.kind IS DISTINCT FROM 'write' THEN
    RAISE EXCEPTION 'NOT_A_WRITE' USING ERRCODE = 'AW400';
  END IF;
  IF v_project IS NULL AND p_function_id <> 'create_project' THEN
    RAISE EXCEPTION 'PROJECT_REQUIRED' USING ERRCODE = 'AW400';
  END IF;
  -- with no project in the context this is true for any projectId: a new project is not made inside another one
  IF p_params ? 'projectId' AND (p_params ->> 'projectId') IS DISTINCT FROM v_project THEN
    RAISE EXCEPTION 'WRONG_PROJECT' USING ERRCODE = 'AW403';
  END IF;
  -- lf-b2-ai-crud: a direct action needs effective level 1 and a level-1 function, or a level-2 function with the PERSON's switch on
  IF p_kind = 'action' AND NOT public.ai_work_link__direct_ok(v_ctx, v_fn.link_level) THEN
    RAISE EXCEPTION 'LEVEL_NOT_ALLOWED' USING ERRCODE = 'AW403';
  END IF;

  v_key := nullif(btrim(coalesce(p_idempotency_key, '')), '');
  IF v_key IS NULL THEN
    v_key := encode(sha256(convert_to(jsonb_build_object(
      'function', p_function_id, 'params', p_params, 'utc_date', to_char(v_now AT TIME ZONE 'UTC', 'YYYY-MM-DD'),
      'project', CASE WHEN v_ctx ->> 'scope' = 'user' THEN v_project END)::text, 'UTF8')), 'hex');
  ELSIF char_length(v_key) > 128 THEN
    RAISE EXCEPTION 'BAD_PARAMS' USING ERRCODE = 'AW400';
  ELSIF v_ctx ->> 'scope' = 'user' THEN
    -- a retry key of a user link is per project: the same key in two projects is two changes, never a replay of the first
    v_key := encode(sha256(convert_to(coalesce(v_project, '') || ':' || v_key, 'UTF8')), 'hex');
  END IF;

  -- an unexecuted intent past its expiry, and an executing one that ran out of time, must not keep holding a key
  PERFORM public.ai_work_link__sweep_intents(v_link);

  SELECT i.id, i.status, i.kind, i.expires_at, i.submission_id, i.result, i.failure INTO v_existing
  FROM platform.ai_work_link_intent i
  WHERE i.link_id = v_link AND i.idempotency_key = v_key
    AND i.status IN ('recorded', 'executing', 'done', 'awaiting_confirmation', 'confirmed');
  IF FOUND THEN
    RETURN jsonb_build_object(
      'intent_id', v_existing.id, 'status', v_existing.status, 'kind', v_existing.kind, 'function_id', p_function_id,
      'replayed', true, 'confirm_token', NULL,
      'expires_at', to_char(v_existing.expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
      'submission_id', v_existing.submission_id, 'result', v_existing.result, 'failure', v_existing.failure);
  END IF;

  SELECT count(*) FILTER (WHERE i.created_at > v_now - interval '1 hour'), count(*) INTO v_hour, v_day
  FROM platform.ai_work_link_intent i WHERE i.link_id = v_link AND i.created_at > v_now - interval '1 day';
  IF v_hour >= 30 THEN
    RAISE EXCEPTION 'WRITE_CAP_HOUR' USING ERRCODE = 'AW429';
  END IF;
  IF v_day >= 200 THEN
    RAISE EXCEPTION 'WRITE_CAP_DAY' USING ERRCODE = 'AW429';
  END IF;
  -- a new project is rarer than a daily entry: 5 a person a day, over every link the person has (the 5 shell projects a day of 0631)
  IF p_function_id = 'create_project' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('ai_work_link_new_project:' || (v_ctx ->> 'user_id'), 0));
    SELECT count(*) INTO v_projects
    FROM platform.ai_work_link_intent i
    WHERE i.user_id = v_ctx ->> 'user_id' AND i.function_id = 'create_project' AND i.created_at > v_now - interval '1 day';
    IF v_projects >= 5 THEN
      RAISE EXCEPTION 'PROJECT_CAP_DAY' USING ERRCODE = 'AW429';
    END IF;
  END IF;

  IF p_kind = 'draft' THEN
    v_status := 'awaiting_confirmation';
    v_expires := v_now + interval '48 hours';
    v_confirm := encode(extensions.gen_random_bytes(32), 'hex');
    v_confirm_hash := encode(sha256(convert_to(v_confirm, 'UTF8')), 'hex');
  ELSE
    v_status := 'recorded';
    v_expires := v_now + interval '1 hour';
  END IF;

  INSERT INTO platform.ai_work_link_intent (
    id, link_id, org_id, project_id, user_id, function_id, params, kind, idempotency_key, status,
    confirm_token_hash, expires_at, created_at)
  VALUES (
    v_id, v_link, v_ctx ->> 'org_id', v_project, v_ctx ->> 'user_id', p_function_id, p_params, p_kind, v_key,
    v_status, v_confirm_hash, v_expires, v_now)
  ON CONFLICT (link_id, idempotency_key) WHERE status IN ('recorded', 'executing', 'done', 'awaiting_confirmation', 'confirmed')
  DO NOTHING
  RETURNING id INTO v_inserted;

  IF v_inserted IS NULL THEN
    -- a concurrent request recorded the same key between the read above and the insert: report that one
    SELECT i.id, i.status, i.kind, i.expires_at, i.submission_id, i.result, i.failure INTO v_existing
    FROM platform.ai_work_link_intent i
    WHERE i.link_id = v_link AND i.idempotency_key = v_key
      AND i.status IN ('recorded', 'executing', 'done', 'awaiting_confirmation', 'confirmed');
    RETURN jsonb_build_object(
      'intent_id', v_existing.id, 'status', v_existing.status, 'kind', v_existing.kind, 'function_id', p_function_id,
      'replayed', true, 'confirm_token', NULL,
      'expires_at', to_char(v_existing.expires_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
      'submission_id', v_existing.submission_id, 'result', v_existing.result, 'failure', v_existing.failure);
  END IF;

  UPDATE platform.user_ai_links SET write_count = write_count + 1 WHERE id = v_link;

  RETURN jsonb_build_object(
    'intent_id', v_id, 'status', v_status, 'kind', p_kind, 'function_id', p_function_id, 'replayed', false,
    'confirm_token', v_confirm,
    'expires_at', to_char(v_expires AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'submission_id', NULL, 'result', NULL, 'failure', NULL);
END
$fn$;

CREATE OR REPLACE FUNCTION public.ai_work_link_intent_claim(p_intent_id text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
DECLARE
  v_link text;
  v_i record;
  v_ctx jsonb;
  v_writes boolean;
  v_now timestamptz := clock_timestamp();
  v_fn_level smallint;
  v_why text;
BEGIN
  SELECT i.link_id INTO v_link FROM platform.ai_work_link_intent i WHERE i.id = p_intent_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'refused', 'reason', 'not_found');
  END IF;

  -- the switch first: with writes off nothing about the intent changes (spec 9.5: it waits)
  SELECT coalesce((SELECT s.writes_enabled FROM platform.ai_work_link_settings s WHERE s.id), false) INTO v_writes;
  IF NOT v_writes THEN
    RETURN jsonb_build_object('status', 'not_enabled');
  END IF;

  PERFORM public.ai_work_link__sweep_intents(v_link);

  SELECT i.id, i.link_id, i.org_id, i.project_id, i.user_id, i.function_id, i.params, i.kind, i.status, i.confirmed_by INTO v_i
  FROM platform.ai_work_link_intent i WHERE i.id = p_intent_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'refused', 'reason', 'not_found');
  END IF;

  IF v_i.status = 'executing' THEN
    RETURN jsonb_build_object('status', 'refused', 'reason', 'already_executing');
  END IF;
  IF v_i.status = 'expired' THEN
    RETURN jsonb_build_object('status', 'refused', 'reason', 'expired');
  END IF;
  IF NOT ((v_i.kind = 'action' AND v_i.status = 'recorded') OR (v_i.kind = 'draft' AND v_i.status = 'confirmed')) THEN
    RETURN jsonb_build_object('status', 'refused', 'reason', 'not_claimable', 'current', v_i.status);
  END IF;
  -- a draft runs only after its own person confirmed it
  IF v_i.kind = 'draft' AND v_i.confirmed_by IS DISTINCT FROM v_i.user_id THEN
    RETURN jsonb_build_object('status', 'refused', 'reason', 'not_confirmed_by_owner');
  END IF;

  v_ctx := public.ai_work_link__live(v_i.link_id);
  -- a user link's intent names its project: the link must still be able to read it (organisation and readability, checked now)
  IF v_ctx ->> 'status' = 'ok' AND v_ctx ->> 'scope' = 'user' AND v_i.project_id IS NOT NULL THEN
    v_ctx := coalesce(public.ai_work_link__bind(v_ctx, v_i.project_id), jsonb_build_object('status', 'gone'));
  END IF;
  v_why := NULL;
  IF v_ctx ->> 'status' IS DISTINCT FROM 'ok' OR v_ctx ->> 'user_id' IS DISTINCT FROM v_i.user_id OR v_ctx ->> 'project_id' IS DISTINCT FROM v_i.project_id THEN
    v_why := 'LINK_GONE';
  ELSE
    SELECT f.link_level INTO v_fn_level FROM platform.ai_work_link_functions f WHERE f.function_id = v_i.function_id;
    -- lf-b2-ai-crud: an action is held to the same predicate as at record time, read NOW (the person may have switched it off since)
    IF NOT (v_i.function_id = ANY (ARRAY(SELECT jsonb_array_elements_text(v_ctx -> 'effective_functions'))))
       OR (v_i.kind = 'action' AND NOT public.ai_work_link__direct_ok(v_ctx, coalesce(v_fn_level, 0))) THEN
      v_why := 'ROLE_CHANGED';
    END IF;
  END IF;
  IF v_why IS NOT NULL THEN
    UPDATE platform.ai_work_link_intent
    SET status = 'refused', failure = jsonb_build_object('code', v_why, 'missing', '[]'::jsonb)
    WHERE id = v_i.id;
    RETURN jsonb_build_object('status', 'refused', 'reason', v_why);
  END IF;

  UPDATE platform.ai_work_link_intent SET status = 'executing', claimed_at = v_now WHERE id = v_i.id;
  RETURN jsonb_build_object(
    'status', 'ok',
    'intent', jsonb_build_object('id', v_i.id, 'kind', v_i.kind, 'function_id', v_i.function_id, 'params', v_i.params),
    'ctx', jsonb_build_object(
      'link_id', v_i.link_id, 'org_id', v_ctx ->> 'org_id', 'user_id', v_ctx ->> 'user_id', 'project_id', v_ctx ->> 'project_id',
      'live_role', v_ctx ->> 'live_role', 'live_rank', (v_ctx ->> 'live_rank')::integer,
      'effective_level', (v_ctx ->> 'effective_level')::integer, 'money_visible', (v_ctx ->> 'money_visible')::boolean));
END
$fn$;

-- the person's switch, for the app route that resolved the person from their own PROJEXA session (never from a link token)
CREATE OR REPLACE FUNCTION public.ai_work_link_person_setting(p_user_id text)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
DECLARE
  v_u record;
  v_s record;
BEGIN
  SELECT u.id, u.org_id, u.is_active INTO v_u FROM compliance.users u WHERE u.id = p_user_id;
  IF NOT FOUND OR NOT v_u.is_active OR v_u.org_id IS NULL THEN
    RAISE EXCEPTION 'USER_NOT_ACTIVE' USING ERRCODE = 'AW403';
  END IF;
  SELECT s.act_without_asking, s.updated_at INTO v_s
  FROM platform.ai_work_link_person_settings s WHERE s.user_id = v_u.id AND s.org_id = v_u.org_id;
  RETURN jsonb_build_object(
    'act_without_asking', coalesce(v_s.act_without_asking, false),
    'updated_at', CASE WHEN v_s.updated_at IS NULL THEN NULL ELSE to_char(v_s.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') END);
END
$fn$;

CREATE OR REPLACE FUNCTION public.ai_work_link_person_setting_set(p_user_id text, p_act_without_asking boolean)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $fn$
DECLARE
  v_u record;
BEGIN
  IF p_act_without_asking IS NULL THEN
    RAISE EXCEPTION 'BAD_VALUE' USING ERRCODE = 'AW400';
  END IF;
  SELECT u.id, u.org_id, u.is_active INTO v_u FROM compliance.users u WHERE u.id = p_user_id;
  IF NOT FOUND OR NOT v_u.is_active OR v_u.org_id IS NULL THEN
    RAISE EXCEPTION 'USER_NOT_ACTIVE' USING ERRCODE = 'AW403';
  END IF;
  -- the row names the person's organisation NOW: a person who moves organisation starts with the switch off there
  INSERT INTO platform.ai_work_link_person_settings (user_id, org_id, act_without_asking, updated_at)
  VALUES (v_u.id, v_u.org_id, p_act_without_asking, now())
  ON CONFLICT (user_id) DO UPDATE SET org_id = EXCLUDED.org_id, act_without_asking = EXCLUDED.act_without_asking, updated_at = EXCLUDED.updated_at;
  RETURN public.ai_work_link_person_setting(v_u.id);
END
$fn$;

REVOKE ALL ON FUNCTION public.ai_work_link__acts_without_asking(text, text) FROM PUBLIC, anon, authenticated, app_runtime, service_role;
REVOKE ALL ON FUNCTION public.ai_work_link__direct_ok(jsonb, integer) FROM PUBLIC, anon, authenticated, app_runtime, service_role;
REVOKE ALL ON FUNCTION public.ai_work_link_person_setting(text) FROM PUBLIC, anon, authenticated, app_runtime;
GRANT EXECUTE ON FUNCTION public.ai_work_link_person_setting(text) TO service_role;
REVOKE ALL ON FUNCTION public.ai_work_link_person_setting_set(text, boolean) FROM PUBLIC, anon, authenticated, app_runtime;
GRANT EXECUTE ON FUNCTION public.ai_work_link_person_setting_set(text, boolean) TO service_role;

COMMIT;
