export type ComplianceTemplate = {
  id: string;
  title: string;
  complianceType: "GST" | "TDS" | "MCA" | "PF" | "ESIC" | "INCOME_TAX" | "ROC" | "LABOUR" | "ENVIRONMENTAL" | "OTHER";
  description: string;
  recurrenceType: "monthly" | "quarterly" | "half_yearly" | "annually";
  dueDateRule: string;
  entityTypes: string[];
  priority: "low" | "medium" | "high" | "critical";
  registrationLabel: string;
  amount: number | null;
};

export const COMPLIANCE_TEMPLATES: ComplianceTemplate[] = [
  // ─── GST Returns (15) ───────────────────────────────────────────
  { id: "gst-gstr1", title: "GSTR-1 (Outward Supplies)", complianceType: "GST", description: "Monthly return of outward supplies. Details of all B2B, B2C, credit/debit notes, and export supplies made during the month.", recurrenceType: "monthly", dueDateRule: "11th of next month", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "critical", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr3b", title: "GSTR-3B (Summary Return)", complianceType: "GST", description: "Monthly summary return for GST liability, input tax credit, and tax payment. Self-assessed tax must be paid along with filing.", recurrenceType: "monthly", dueDateRule: "20th of next month", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "critical", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr3b-qtr", title: "GSTR-3B (Quarterly - QRMP)", complianceType: "GST", description: "Quarterly summary return for taxpayers under QRMP scheme with 35% advance tax payment in first month of quarter.", recurrenceType: "quarterly", dueDateRule: "22nd/24th/26th of month following quarter", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-itc04", title: "ITC-04 (ITC Statement)", complianceType: "GST", description: "Quarterly statement of input tax credit availed on reverse charge, ISD, and stock transfer. Filed by registered persons availing ITC from these sources.", recurrenceType: "quarterly", dueDateRule: "25th of month following quarter", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr5", title: "GSTR-5 (Non-Resident Taxpayer)", complianceType: "GST", description: "Monthly return for non-resident taxable persons. Details of supplies made, ITC claimed, and tax payable.", recurrenceType: "monthly", dueDateRule: "20th of next month", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "medium", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr6", title: "GSTR-6 (ISD Return)", complianceType: "GST", description: "Monthly return for Input Service Distributor. Distribution of input tax credit to recipient units.", recurrenceType: "monthly", dueDateRule: "13th of next month", entityTypes: ["Pvt Ltd", "LLP"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr7", title: "GSTR-7 (TDS Return)", complianceType: "GST", description: "Monthly return for persons required to deduct TDS under GST. Statement of TDS deducted, TDS deposited, and TDS certificates issued.", recurrenceType: "monthly", dueDateRule: "10th of next month", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr8", title: "GSTR-8 (E-Commerce Operator)", complianceType: "GST", description: "Monthly return for e-commerce operators. Details of supplies made through marketplace, TCS collected and deposited.", recurrenceType: "monthly", dueDateRule: "10th of next month", entityTypes: ["Pvt Ltd", "LLP"], priority: "medium", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr9", title: "GSTR-9 (Annual Return)", complianceType: "GST", description: "Annual return providing consolidated summary of all monthly/quarterly returns filed during the financial year. Includes turnover, ITC, tax paid, and refund details.", recurrenceType: "annually", dueDateRule: "31st December of following FY", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "critical", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr9c", title: "GSTR-9C (Reconciliation Statement)", complianceType: "GST", description: "Annual reconciliation statement reconciling GSTR-9 with audited financial statements. Required for taxpayers with aggregate turnover above Rs. 5 Crore.", recurrenceType: "annually", dueDateRule: "31st December of following FY", entityTypes: ["Pvt Ltd", "LLP"], priority: "critical", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr4", title: "GSTR-4 (Composition Return)", complianceType: "GST", description: "Quarterly return for composition scheme taxpayers. Statement of supplies made, tax payable, and tax paid.", recurrenceType: "quarterly", dueDateRule: "18th of month following quarter", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-emp101", title: "EMP-01 (E-Way Bill Extension)", complianceType: "GST", description: "Monthly statement of extension of e-way bills. Details of e-way bills extended beyond the original validity period.", recurrenceType: "monthly", dueDateRule: "Last day of next month", entityTypes: ["Pvt Ltd", "LLP", "Partnership", "Sole Proprietor"], priority: "low", registrationLabel: "GSTIN", amount: null },
  { id: "gst-anx1", title: "ANX-1 (Annexure-1 Invoice Details)", complianceType: "GST", description: "Furnish invoice-level details of outward supplies in Annexure-1 of GST returns. Required for taxpayers with turnover above Rs. 5 Crore.", recurrenceType: "monthly", dueDateRule: "9th of next month", entityTypes: ["Pvt Ltd", "LLP"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-anx2", title: "ANX-2 (Annexure-2 ITC Matching)", complianceType: "GST", description: "Furnish ITC details from auto-populated GSTR-2B. Confirm or modify ITC claims in Annexure-2.", recurrenceType: "monthly", dueDateRule: "11th of next month", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "gst-gstr2b", title: "GSTR-2B (Auto-Populated ITC)", complianceType: "GST", description: "Review auto-populated ITC statement. Verify ITC eligibility from inward supplies. No filing required but must be reviewed monthly.", recurrenceType: "monthly", dueDateRule: "14th of next month (auto-generated)", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "high", registrationLabel: "GSTIN", amount: null },

  // ─── TDS Returns (10) ───────────────────────────────────────────
  { id: "tds-24q", title: "Form 24Q (TDS on Salary)", complianceType: "TDS", description: "Quarterly TDS return for salary deductions under Section 192. Includes salary break-up, TDS deducted, and TDS deposited.", recurrenceType: "quarterly", dueDateRule: "31st May / 31st Jul / 31st Oct / 31st Jan", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "critical", registrationLabel: "TAN", amount: null },
  { id: "tds-26q", title: "Form 26Q (TDS on Non-Salary)", complianceType: "TDS", description: "Quarterly TDS return for deductions under Sections 194A-194Q. Covers contractor payments, rent, professional fees, interest, commission.", recurrenceType: "quarterly", dueDateRule: "31st May / 31st Jul / 31st Oct / 31st Jan", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "critical", registrationLabel: "TAN", amount: null },
  { id: "tds-27q", title: "Form 27Q (TDS on NRI Payments)", complianceType: "TDS", description: "Quarterly TDS return for deductions from payments to non-residents under Sections 195, 196. Includes NRI payments for services, interest, royalties, FDI.", recurrenceType: "quarterly", dueDateRule: "31st May / 31st Jul / 31st Oct / 31st Jan", entityTypes: ["Pvt Ltd", "LLP"], priority: "high", registrationLabel: "TAN", amount: null },
  { id: "tds-27eq", title: "Form 27EQ (TCS Return)", complianceType: "TDS", description: "Quarterly TCS return for tax collected at source. Covers TCS on sale of goods, motor vehicles, lottery, foreign remittance, and specified transactions.", recurrenceType: "quarterly", dueDateRule: "31st May / 31st Jul / 31st Oct / 31st Jan", entityTypes: ["Pvt Ltd", "LLP"], priority: "high", registrationLabel: "TAN", amount: null },
  { id: "tds-16a", title: "Form 16A (TDS Certificate - Non-Salary)", complianceType: "TDS", description: "Issue TDS certificates to deductees for non-salary deductions. Must be generated within 15 days of filing the quarterly return.", recurrenceType: "quarterly", dueDateRule: "15 days after filing return", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "high", registrationLabel: "TAN", amount: null },
  { id: "tds-16", title: "Form 16 (TDS Certificate - Salary)", complianceType: "TDS", description: "Annual TDS certificate for salary income. Must be issued by 15th June for the previous financial year. Contains salary break-up and tax computation.", recurrenceType: "annually", dueDateRule: "15th June", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "critical", registrationLabel: "TAN", amount: null },
  { id: "tds-192", title: "TDS Section 192 - Salary", complianceType: "TDS", description: "Monthly deduction of TDS from employee salaries. Rate: As per slab. Due date: 7th of next month for deposit.", recurrenceType: "monthly", dueDateRule: "7th of next month (deposit)", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "critical", registrationLabel: "TAN", amount: null },
  { id: "tds-194a", title: "TDS Section 194A - Interest", complianceType: "TDS", description: "TDS on interest income other than securities. Rate: 10% (20% if PAN not available). Threshold: Rs. 40,000 (Rs. 50,000 for senior citizens).", recurrenceType: "monthly", dueDateRule: "7th of next month (deposit)", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "medium", registrationLabel: "TAN", amount: null },
  { id: "tds-194c", title: "TDS Section 194C - Contractor", complianceType: "TDS", description: "TDS on payments to contractors. Rate: 1% (individual/HUF) or 2% (others). Threshold: Rs. 30,000 per payment or Rs. 1,00,000 annually.", recurrenceType: "monthly", dueDateRule: "7th of next month (deposit)", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "high", registrationLabel: "TAN", amount: null },
  { id: "tds-194j", title: "TDS Section 194J - Professional Fees", complianceType: "TDS", description: "TDS on professional fees, technical services, royalty, and director remuneration. Rate: 10%. Threshold: Rs. 30,000 per payment.", recurrenceType: "monthly", dueDateRule: "7th of next month (deposit)", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "high", registrationLabel: "TAN", amount: null },

  // ─── PF / ESIC (6) ──────────────────────────────────────────────
  { id: "pf-monthly", title: "PF Monthly Return (ECR)", complianceType: "PF", description: "Monthly Electronic Challan cum Return filing with EPFO. Includes employee and employer contributions (12% + 12%), EDLI (0.5%), and EPS (8.33%).", recurrenceType: "monthly", dueDateRule: "15th of next month", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "critical", registrationLabel: "PF Code", amount: null },
  { id: "pf-annual", title: "PF Annual Return", complianceType: "PF", description: "Annual return filing with EPFO providing consolidated PF contribution details for all employees during the financial year.", recurrenceType: "annually", dueDateRule: "30th April", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "high", registrationLabel: "PF Code", amount: null },
  { id: "pf-edli", title: "EDLI Contribution Return", complianceType: "PF", description: "Quarterly Employee Deposit Linked Insurance contribution return. 0.5% of basic wages from employer.", recurrenceType: "quarterly", dueDateRule: "15th of month following quarter", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "medium", registrationLabel: "PF Code", amount: null },
  { id: "esic-half", title: "ESIC Half-Yearly Return", complianceType: "ESIC", description: "Half-yearly return for Employee State Insurance contributions. Covers employee health insurance, maternity, disability, and dependent benefits.", recurrenceType: "half_yearly", dueDateRule: "12th November / 12th May", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "high", registrationLabel: "ESIC Code", amount: null },
  { id: "esic-monthly", title: "ESIC Monthly Contribution", complianceType: "ESIC", description: "Monthly deposit of ESIC contributions. Employer: 3.25%, Employee: 0.75% of gross wages. Deposit by 15th of following month.", recurrenceType: "monthly", dueDateRule: "15th of next month", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "critical", registrationLabel: "ESIC Code", amount: null },
  { id: "pf-apcr", title: "PF APCR (Annual PF Compliance Report)", complianceType: "PF", description: "Annual PF compliance report to be filed with EPFO. Includes employee strength, wage details, and contribution summary.", recurrenceType: "annually", dueDateRule: "30th September", entityTypes: ["Pvt Ltd", "LLP"], priority: "medium", registrationLabel: "PF Code", amount: null },

  // ─── Income Tax (8) ─────────────────────────────────────────────
  { id: "itr-filing", title: "ITR Filing (Corporate)", complianceType: "INCOME_TAX", description: "Annual income tax return filing for companies. ITR-6 for companies (except those claiming exemption under Section 11). Due: October 31.", recurrenceType: "annually", dueDateRule: "31st October", entityTypes: ["Pvt Ltd", "LLP"], priority: "critical", registrationLabel: "PAN", amount: null },
  { id: "itr-audit", title: "Tax Audit Report (Form 3CB/3CD)", complianceType: "INCOME_TAX", description: "Tax audit report by CA for businesses with turnover exceeding Rs. 1 Crore. Includes Form 3CD with 44 clauses covering all transaction details.", recurrenceType: "annually", dueDateRule: "30th September", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "critical", registrationLabel: "PAN", amount: null },
  { id: "adv-tax-q1", title: "Advance Tax - Q1 (June 15)", complianceType: "INCOME_TAX", description: "First installment of advance tax payment. 15% of estimated tax liability for companies. Due by June 15th.", recurrenceType: "quarterly", dueDateRule: "15th June", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "PAN", amount: null },
  { id: "adv-tax-q2", title: "Advance Tax - Q2 (September 15)", complianceType: "INCOME_TAX", description: "Second installment of advance tax. 45% cumulative of estimated tax liability for companies.", recurrenceType: "quarterly", dueDateRule: "15th September", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "PAN", amount: null },
  { id: "adv-tax-q3", title: "Advance Tax - Q3 (December 15)", complianceType: "INCOME_TAX", description: "Third installment of advance tax. 75% cumulative of estimated tax liability for companies.", recurrenceType: "quarterly", dueDateRule: "15th December", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "PAN", amount: null },
  { id: "adv-tax-q4", title: "Advance Tax - Q4 (March 15)", complianceType: "INCOME_TAX", description: "Fourth and final installment of advance tax. 100% of estimated tax liability for companies.", recurrenceType: "quarterly", dueDateRule: "15th March", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "PAN", amount: null },
  { id: "tds-certificate-issue", title: "TDS Certificate Issuance", complianceType: "INCOME_TAX", description: "Ensure all TDS certificates (Form 16, 16A) are issued to deductees within due dates. Form 16 by June 15, Form 16A within 15 days of return filing.", recurrenceType: "annually", dueDateRule: "15th June (Form 16)", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership"], priority: "high", registrationLabel: "TAN", amount: null },
  { id: "it-return-individual", title: "ITR Filing (Individual Directors)", complianceType: "INCOME_TAX", description: "Ensure all company directors file their individual ITR. ITR-3/4 for business/professional income. Due: July 31 (no audit) or Oct 31 (with audit).", recurrenceType: "annually", dueDateRule: "31st July", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "high", registrationLabel: "PAN", amount: null },

  // ─── MCA / ROC (12) ─────────────────────────────────────────────
  { id: "mca-aoc4", title: "AOC-4 (Financial Statements)", complianceType: "MCA", description: "Filing of financial statements with ROC within 30 days of Annual General Meeting. Includes Balance Sheet, P&L, and subsidiary financials.", recurrenceType: "annually", dueDateRule: "30 days after AGM", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "CIN", amount: null },
  { id: "mca-mgt7", title: "MGT-7 (Annual Return)", complianceType: "MCA", description: "Annual return filing with ROC within 60 days of AGM. Includes registered office details, shareholding, directors, meetings, and penalties.", recurrenceType: "annually", dueDateRule: "60 days after AGM", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "CIN", amount: null },
  { id: "mca-dir3ky", title: "DIR-3 KYC (Director KYC)", complianceType: "MCA", description: "Annual KYC for every director holding DIN. Must be filed between April 1 and September 30. Non-filing leads to DIN deactivation.", recurrenceType: "annually", dueDateRule: "30th September", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "DIN", amount: null },
  { id: "mca-adt1", title: "ADT-1 (Auditor Appointment)", complianceType: "MCA", description: "Filing of auditor appointment/resignation with ROC within 15 days of AGM or appointment. Includes Form ADT-1 with auditor details and term.", recurrenceType: "annually", dueDateRule: "15 days after AGM", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "CIN", amount: null },
  { id: "mca-mgt14", title: "MGT-14 (Resolution Filing)", complianceType: "MCA", description: "Filing of board/shareholder resolutions with ROC within 30 days of passing. Covers all material resolutions as per Section 179(3).", recurrenceType: "monthly", dueDateRule: "30 days after resolution passed", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "high", registrationLabel: "CIN", amount: null },
  { id: "mca-inc20a", title: "INC-20A (Business Commencement)", complianceType: "MCA", description: "Declaration of business commencement within 180 days of incorporation. Mandatory for all companies incorporated after Nov 2018.", recurrenceType: "annually", dueDateRule: "180 days from incorporation", entityTypes: ["Pvt Ltd", "OPC"], priority: "critical", registrationLabel: "CIN", amount: null },
  { id: "mca-inc22a", title: "INC-22A (Registered Office Verification)", complianceType: "MCA", description: "Verification of registered office within 30 days of incorporation. Upload photo of office with address visible. One-time filing.", recurrenceType: "annually", dueDateRule: "30 days from incorporation", entityTypes: ["Pvt Ltd", "OPC"], priority: "high", registrationLabel: "CIN", amount: null },
  { id: "mca-din-activation", title: "DIN Activation (Form DIR-5)", complianceType: "MCA", description: "Reactivation of deactivated DIN. Required if DIR-3 KYC was not filed for 3 consecutive years. Process takes 30 days.", recurrenceType: "annually", dueDateRule: "On demand", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "high", registrationLabel: "DIN", amount: null },
  { id: "mca-charge", title: "Charge Registration (Form CHG-1)", complianceType: "MCA", description: "Registration of creation/modification/satisfaction of charges on company assets within 30 days. Mandatory for secured borrowings.", recurrenceType: "annually", dueDateRule: "30 days from charge creation", entityTypes: ["Pvt Ltd", "LLP"], priority: "high", registrationLabel: "CIN", amount: null },
  { id: "mca-board-meeting", title: "Board of Directors Meeting", complianceType: "MCA", description: "Quarterly board meeting as required under Companies Act. Minimum 4 meetings per year with maximum 120 days gap between meetings.", recurrenceType: "quarterly", dueDateRule: "Max 120 days gap", entityTypes: ["Pvt Ltd", "OPC"], priority: "high", registrationLabel: "CIN", amount: null },
  { id: "mca-agm", title: "Annual General Meeting (AGM)", complianceType: "MCA", description: "Conduct Annual General Meeting within 6 months of financial year end (i.e., by September 30). First AGM within 18 months of incorporation.", recurrenceType: "annually", dueDateRule: "By 30th September", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "critical", registrationLabel: "CIN", amount: null },
  { id: "mca-msme-return", title: "MSME-1 (Outstanding MSME Payments)", complianceType: "MCA", description: "Half-yearly return on outstanding payments to MSME suppliers. Due: April 30 and October 31. Covers all payments exceeding 45 days.", recurrenceType: "half_yearly", dueDateRule: "30th April / 31st October", entityTypes: ["Pvt Ltd", "LLP"], priority: "high", registrationLabel: "CIN", amount: null },

  // ─── Labour (5) ─────────────────────────────────────────────────
  { id: "labour-pt-monthly", title: "Professional Tax - Monthly", complianceType: "LABOUR", description: "Monthly professional tax deduction from employee salaries and deposit with state government. Rates vary by state.", recurrenceType: "monthly", dueDateRule: "End of next month", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "medium", registrationLabel: "Registration No.", amount: null },
  { id: "labour-lwf", title: "Labour Welfare Fund", complianceType: "LABOUR", description: "Annual contribution to Labour Welfare Fund for employee welfare activities. Amount and due date vary by state (typically June/December).", recurrenceType: "annually", dueDateRule: "Varies by state (Jun/Dec)", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "medium", registrationLabel: "Registration No.", amount: null },
  { id: "labour-minwage", title: "Minimum Wage Compliance", complianceType: "LABOUR", description: "Ensure all employee wages meet or exceed the minimum wage notified by the relevant state government. Review and update annually on April 1.", recurrenceType: "annually", dueDateRule: "1st April (review date)", entityTypes: ["Pvt Ltd", "LLP", "Partnership"], priority: "high", registrationLabel: "Registration No.", amount: null },
  { id: "labour-factory", title: "Factory License Renewal", complianceType: "LABOUR", description: "Annual renewal of factory license under the Factories Act, 1948. Valid until December 31. Apply for renewal by October 31.", recurrenceType: "annually", dueDateRule: "31st October (apply by)", entityTypes: ["Pvt Ltd"], priority: "high", registrationLabel: "Factory License No.", amount: null },
  { id: "labour-shop-est", title: "Shop & Establishment License", complianceType: "LABOUR", description: "Registration/renewal of Shop & Establishment license under state-specific Acts. Typically valid for 1-3 years depending on state.", recurrenceType: "annually", dueDateRule: "Varies by state", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "medium", registrationLabel: "Registration No.", amount: null },

  // ─── Environmental (3) ──────────────────────────────────────────
  { id: "env-pcb-consent", title: "PCB Consent to Operate", complianceType: "ENVIRONMENTAL", description: "Obtain/renew Consent to Operate from State Pollution Control Board. Validity: 5 years for Red category, 10 years for Orange/Green.", recurrenceType: "annually", dueDateRule: "Before expiry (monitor annually)", entityTypes: ["Pvt Ltd"], priority: "critical", registrationLabel: "Consent No.", amount: null },
  { id: "env-hw-return", title: "Hazardous Waste Return", complianceType: "ENVIRONMENTAL", description: "Annual return on hazardous waste generation, collection, treatment, and disposal. Filed with State Pollution Control Board.", recurrenceType: "annually", dueDateRule: "30th June", entityTypes: ["Pvt Ltd"], priority: "high", registrationLabel: "Consent No.", amount: null },
  { id: "env-ec-clearance", title: "Environmental Clearance (if applicable)", complianceType: "ENVIRONMENTAL", description: "Environmental clearance for projects requiring EIA. Monitor compliance with clearance conditions. Half-yearly compliance report.", recurrenceType: "half_yearly", dueDateRule: "Every 6 months", entityTypes: ["Pvt Ltd"], priority: "high", registrationLabel: "EC File No.", amount: null },

  // ─── Other / General (6) ────────────────────────────────────────
  { id: "other-roc-annual-filing-llp", title: "LLP Form 8 (Statement of Account)", complianceType: "OTHER", description: "Annual filing of Statement of Account & Solvency for LLP with ROC. Due within 30 days of end of financial year (May 30).", recurrenceType: "annually", dueDateRule: "30th May", entityTypes: ["LLP"], priority: "critical", registrationLabel: "LLPIN", amount: null },
  { id: "other-roc-annual-return-llp", title: "LLP Form 11 (Annual Return)", complianceType: "OTHER", description: "Annual return filing for LLP with ROC. Due within 60 days of end of financial year (June 30). Includes partner details and changes.", recurrenceType: "annually", dueDateRule: "30th June", entityTypes: ["LLP"], priority: "critical", registrationLabel: "LLPIN", amount: null },
  { id: "other-gst-annual-itr", title: "GST Annual Return Reconciliation", complianceType: "OTHER", description: "Reconcile GST annual return (GSTR-9) data with ITR figures before filing. Ensure turnover and tax figures match across both filings.", recurrenceType: "annually", dueDateRule: "Before 31st December", entityTypes: ["Pvt Ltd", "LLP", "OPC", "Partnership", "Sole Proprietor"], priority: "high", registrationLabel: "GSTIN", amount: null },
  { id: "other-board-minutes", title: "Board Meeting Minutes Circulation", complianceType: "OTHER", description: "Circulate draft minutes of board meeting within 7 days and final approved minutes within 15 days of the meeting.", recurrenceType: "quarterly", dueDateRule: "7 days after board meeting", entityTypes: ["Pvt Ltd", "OPC"], priority: "medium", registrationLabel: "CIN", amount: null },
  { id: "other-shareholder-register", title: "Shareholder Register Update", complianceType: "OTHER", description: "Maintain and update register of members, shareholders, and debenture holders. Review after every share transfer or issue.", recurrenceType: "quarterly", dueDateRule: "Within 7 days of change", entityTypes: ["Pvt Ltd"], priority: "medium", registrationLabel: "CIN", amount: null },
  { id: "other-statutory-register", title: "Statutory Registers Maintenance", complianceType: "OTHER", description: "Maintain all statutory registers: register of members, directors, charges, contracts, debentures, and key managerial personnel.", recurrenceType: "annually", dueDateRule: "Ongoing (annual review)", entityTypes: ["Pvt Ltd", "LLP", "OPC"], priority: "medium", registrationLabel: "CIN", amount: null },
];

export function getTemplatesByType(type: string): ComplianceTemplate[] {
  return COMPLIANCE_TEMPLATES.filter((t) => t.complianceType === type);
}

export function getTemplatesByEntityType(entityType: string): ComplianceTemplate[] {
  return COMPLIANCE_TEMPLATES.filter((t) => t.entityTypes.includes(entityType));
}

export function searchTemplates(query: string): ComplianceTemplate[] {
  const q = query.toLowerCase();
  return COMPLIANCE_TEMPLATES.filter(
    (t) =>
      t.title.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.complianceType.toLowerCase().includes(q) ||
      t.dueDateRule.toLowerCase().includes(q)
  );
}