// R67 D-31 (R-090): the printed trade-wise attendance summary.
//
// Modelled on work-progress-report-pdf.ts exactly: a pure function over a plain
// data object, returning an ArrayBuffer, independently unit-testable with no DB
// or tenant context, using pdf-generator.ts's shared branded-document helpers.
// It exists here rather than in PROJEXA because PROJEXA must not gain a PDF
// library; it relays these bytes.
//
// It does NO arithmetic of its own. The rows, the totals and the headline count
// are computed by construction-reports-service.ts's own pure builders and passed
// in, so a printed sheet and the screen it was printed from cannot disagree --
// the failure mode a second, PDF-local sum would reintroduce.
import { createBrandedDocument, drawDocumentHeader, drawSectionLabel, drawFooterNote, pdfToBuffer, autoTable } from "@/lib/pdf-generator"
import type { AttendanceSummaryRow } from "@/lib/services/construction-reports-service"

export type AttendanceSummaryPdfData = {
  org: { name: string; address: string | null; gstin: string | null }
  projectName: string
  from: string | null
  to: string | null
  rows: AttendanceSummaryRow[]
  totals: Omit<AttendanceSummaryRow, "trade">
  headcount: number
  /** False when the two aggregates behind this summary disagree -- printed as a warning line rather than hidden. */
  ties: boolean
}

function money(n: number): string {
  return n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

/** Trims a whole number to "12" and keeps a half day as "12.5" -- worker-days are the one column that legitimately halves. */
function count(n: number): string {
  return Number.isInteger(n) ? String(n) : String(Math.round(n * 100) / 100)
}

/** "Mason 12 · Electrician 4 · Helper 9" -- the same headline sentence the screen shows, built from the same rows. */
export function attendanceHeadlineParts(rows: AttendanceSummaryRow[]): string {
  return rows
    .filter((r) => r.present + r.halfDay > 0)
    .map((r) => `${r.trade} ${count(r.present + r.halfDay)}`)
    .join(" · ")
}

export function generateAttendanceSummaryPdf(data: AttendanceSummaryPdfData): ArrayBuffer {
  const doc = createBrandedDocument()
  const window = data.from && data.to ? (data.from === data.to ? data.from : `${data.from} to ${data.to}`) : "All recorded attendance"
  let y = drawDocumentHeader(doc, {
    orgName: data.org.name,
    orgAddress: data.org.address,
    orgGstin: data.org.gstin,
    documentTitle: "Attendance Summary",
    documentSubtitle: `${data.projectName} · ${window}`,
  })
  y += 16

  doc.setFontSize(10)
  doc.setFont("helvetica", "bold")
  doc.text(`${count(data.headcount)} people on site`, 32, y)
  doc.setFont("helvetica", "normal")
  y += 14
  const parts = attendanceHeadlineParts(data.rows)
  if (parts) {
    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text(parts, 32, y)
    doc.setTextColor(28, 43, 58)
    y += 16
  }

  if (!data.ties) {
    // Never silently print a total that the underlying aggregates disagree
    // about -- the same rule the screen applies before it lets you export.
    doc.setFontSize(9)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(176, 58, 58)
    doc.text("The per-trade rows do not add up to the totals for this window -- treat these figures as provisional.", 32, y)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(28, 43, 58)
    y += 16
  }

  drawSectionLabel(doc, "By trade", 32, y)
  y += 8

  if (data.rows.length === 0) {
    // A day with no attendance recorded is a legitimate answer, not an error.
    doc.setFont("helvetica", "italic")
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text("No attendance recorded for this project in this window.", 32, y + 14)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(28, 43, 58)
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Trade", "Present", "Half day", "Absent", "Worker-days", "Cost"]],
      body: data.rows.map((r) => [r.trade, count(r.present), count(r.halfDay), count(r.absent), count(r.workerDays), money(r.cost)]),
      foot: [["Total", count(data.totals.present), count(data.totals.halfDay), count(data.totals.absent), count(data.totals.workerDays), money(data.totals.cost)]],
      margin: { left: 32, right: 32 },
      headStyles: { fillColor: "#1C2B3A", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
      footStyles: { fillColor: "#F5820A", textColor: "#FFFFFF", fontStyle: "bold", fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 4 },
      columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "right" } },
    })
  }

  drawFooterNote(doc, "Generated by VERIDIAN AI OS · Attendance Summary")
  return pdfToBuffer(doc)
}
