// R67 E-05 (R-103): the Material Cost Report's printed form.
//
// Same shape as work-progress-report-pdf.ts, deliberately: a pure function
// over a plain data object, returning an ArrayBuffer, independently testable
// with no DB or tenant context, drawn with pdf-generator.ts's shared branded
// helpers. PROJEXA must not gain a PDF library, so this is where the bytes are
// made and the projexa route only relays them.
//
// NOTHING IS RECOMPUTED HERE. The rows and the grand total arrive already
// aggregated by construction-materials-service.ts#aggregateMaterialCostReport,
// which is the one place this report's arithmetic lives. A PDF that re-added
// the column itself would be a second summation path, and the whole point of
// R-103 is that a QS can add the printed column by hand and get the printed
// total.
import { createBrandedDocument, drawDocumentHeader, drawSectionLabel, drawFooterNote, pdfToBuffer, autoTable } from "@/lib/pdf-generator"
import type { MaterialCostReport } from "@/lib/services/construction-materials-service"

export type MaterialCostReportPdfData = {
  org: { name: string; address?: string | null; gstin?: string | null }
  projectName: string
  /** ISO code, e.g. "AED". Null when the org has no base currency -- then the money columns carry no token at all rather than a guessed one. */
  currency: string | null
  report: MaterialCostReport
}

/** Two decimals, grouped, no currency token -- the code goes in the column header, once. */
function money(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

/** The en dash. "We do not have this figure" is not "this figure is zero". */
const EMPTY = "–"

/** The period line printed under the title, and the same words the empty state uses. */
export function periodLabel(from: string | null, to: string | null): string {
  if (from && to) return `${from} to ${to}`
  if (from) return `from ${from}`
  if (to) return `up to ${to}`
  return "all recorded receipts"
}

export function generateMaterialCostReportPdf(data: MaterialCostReportPdfData): ArrayBuffer {
  const { report } = data
  const unit = data.currency ? ` (${data.currency})` : ""

  const doc = createBrandedDocument({ orientation: "l" }) // nine columns need the width
  let y = drawDocumentHeader(doc, {
    orgName: data.org.name,
    orgAddress: data.org.address,
    orgGstin: data.org.gstin,
    documentTitle: "Material Cost Report",
    documentSubtitle: `${data.projectName} · ${periodLabel(report.params.from, report.params.to)}`,
  })
  y += 16

  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.setFont("helvetica", "normal")
  doc.text(`Grouped by: ${report.params.groupBy === "vendor" ? "Vendor" : "Material"}`, 32, y)
  y += 18

  drawSectionLabel(doc, "Receipts by cost", 32, y)
  y += 8

  if (report.rows.length === 0) {
    // A period with no receipts is a real answer, not an error -- the same
    // rule work-progress-report-pdf.ts states for an empty BoQ. Still a valid
    // PDF, never a 4xx.
    doc.setFont("helvetica", "italic")
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(`No receipts recorded for ${periodLabel(report.params.from, report.params.to)}.`, 32, y + 14)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(28, 43, 58)
  } else {
    autoTable(doc, {
      startY: y,
      head: [[
        "Material", "Spec", "Vendor", "Unit", "Qty Received",
        `Total Cost${unit}`, `Avg Unit Cost${unit}`, `Master Unit Cost${unit}`, `Variance${unit}`,
      ]],
      body: [
        ...report.rows.map((r) => [
          r.name,
          r.spec ?? EMPTY,
          r.vendorName ?? EMPTY,
          r.unit ?? EMPTY,
          r.totalQuantityReceived.toLocaleString("en-US"),
          money(r.totalCost),
          money(r.averageUnitCost),
          r.masterUnitCost === null ? EMPTY : money(r.masterUnitCost),
          r.variance === null ? EMPTY : money(r.variance),
        ]),
        // The grand total is the figure this report exists for, so it is a row
        // of the table rather than a line underneath it -- it can never be cut
        // off a page break separately from the rows it totals.
        ["Grand Total", "", "", "", report.totals.quantity.toLocaleString("en-US"), money(report.totals.cost), "", "", ""],
      ],
      styles: { fontSize: 7.5, cellPadding: 3 },
      headStyles: { fillColor: [28, 43, 58] },
      columnStyles: { 4: { halign: "right" }, 5: { halign: "right" }, 6: { halign: "right" }, 7: { halign: "right" }, 8: { halign: "right" } },
      margin: { left: 32, right: 32 },
    })
  }

  drawFooterNote(doc, "Voided receipts are excluded. Generated by VERIDIAN AI.")
  return pdfToBuffer(doc)
}
