// PROJEXA-BUILD-002 WP-09b: the ai-work-link-exec Edge function. It runs one AI-work-link write through the real pipeline (spec 9.6, 9.8). Deno.serve
// only: the routes and every rule are in handler.ts (bun-testable), the pipeline is the generated bundle app.bundle.mjs (scripts/build-ai-work-link-exec.ts,
// built at deploy time, never committed). Deploy with verify_jwt FALSE: the caller is the ai-work-link function, which presents the shared internal
// secret AWL_EXEC_INTERNAL_SECRET; without that secret and APP_RUNTIME_DATABASE_URL every request is 503 NOT_CONFIGURED (handler.ts).
import "./process-global.ts"
import { createClient } from "npm:@supabase/supabase-js@2"
import { claimSyncOp, handleExec } from "./handler.ts"
// @ts-ignore generated by scripts/build-ai-work-link-exec.ts; not in the repository
import { linkExecHealth, runLinkIntent, runLinkRead, runSyncOp } from "./app.bundle.mjs"

// A driver error that surfaces outside any await (a socket that closes after the request was answered, a refused connection) would otherwise end the
// isolate with an empty 503 and no log line. Log its class and a redacted, shortened message, and keep the isolate alive so the handler's own catch answers.
const redact = (v: unknown): string => String((v as { message?: unknown })?.message ?? v).replace(/postgres(ql)?:\/\/\S+/gi, "<hidden>").slice(0, 300)
globalThis.addEventListener("unhandledrejection", (e: PromiseRejectionEvent) => {
  console.error("ai-work-link-exec: unhandled rejection:", redact(e.reason))
  e.preventDefault()
})
globalThis.addEventListener("error", (e: ErrorEvent) => {
  console.error("ai-work-link-exec: uncaught error:", redact(e.error ?? e.message))
  e.preventDefault()
})

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? ""
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
// claim and finish are granted to service_role only (drizzle/0629); the business writes go through APP_RUNTIME_DATABASE_URL inside the bundle
const client = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } })

const rpc = async (fn: string, args?: Record<string, unknown>) => {
  const { data, error } = await client.rpc(fn, args)
  return { data, error: error ? { message: error.message, code: error.code ?? undefined } : null }
}

Deno.serve((req: Request) =>
  handleExec(req, {
    rpc,
    secret: Deno.env.get("AWL_EXEC_INTERNAL_SECRET"),
    syncSecret: Deno.env.get("AWL_SYNC_EXEC_SECRET") || undefined,
    syncClaim: (op) => claimSyncOp(rpc, op),
    dbConfigured: Boolean(Deno.env.get("APP_RUNTIME_DATABASE_URL")),
    run: runLinkIntent,
    read: runLinkRead,
    syncRun: runSyncOp,
    health: linkExecHealth,
  }),
)
