// Server-rendered, print-friendly standalone HTML document -- adopted
// verbatim as a technique from meettrack-v2's /api/pdf route (no PDF
// generation library dependency; browsers print-to-PDF natively), reskinned
// with VERIDIAN's own brand tokens. See PLATFORM_STRATEGY.md §25.
import { NextRequest, NextResponse } from "next/server"
import { requireAuth } from "@/lib/supabase/auth-guard"
import { getVeriMeeting, ServiceError } from "@/lib/services/veri-meeting-service"

type RouteContext = { params: Promise<{ id: string }> }

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

export async function GET(_request: NextRequest, { params }: RouteContext) {
  const { response, orgId } = await requireAuth()
  if (response) return response
  if (!orgId) return NextResponse.json({ error: "No organisation found" }, { status: 400 })

  try {
    const { id } = await params
    const meeting = await getVeriMeeting({ orgId }, id)

    const attendees = Array.isArray(meeting.attendees) ? (meeting.attendees as string[]).join(", ") : ""
    const agenda = Array.isArray(meeting.agenda) ? (meeting.agenda as string[]) : []
    const rows = meeting.actionItems
      .map(
        (item) => `
      <tr>
        <td>${esc(item.task.title)}</td>
        <td>${esc(item.task.status)}</td>
      </tr>`
      )
      .join("")

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${esc(meeting.systemId ?? "MOM")} - ${esc(meeting.title)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', system-ui, -apple-system, sans-serif; color: #1C2B3A; padding: 32px; max-width: 860px; margin: auto; background: #FFFDF9; }
  h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
  h2 { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #0E7C6E; margin: 24px 0 8px; }
  .meta { font-size: 13px; color: #4a4f6a; margin-bottom: 8px; }
  .system-id { font-size: 11px; color: #8890aa; font-family: monospace; margin-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #f9fafb; padding: 10px 8px; text-align: left; font-size: 12px; font-weight: 600; border-bottom: 2px solid #e5e7eb; }
  td { padding: 10px 8px; font-size: 13px; border-bottom: 1px solid #e5e7eb; }
  .minutes { white-space: pre-wrap; font-size: 13px; line-height: 1.6; }
  .status { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; background: #dce8f8; color: #1C2B3A; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <div style="border-bottom:2px solid #1C2B3A;padding-bottom:16px;margin-bottom:20px">
    <p class="system-id">${esc(meeting.systemId ?? "")}</p>
    <h1>${esc(meeting.title)}</h1>
    <p class="meta">${new Date(meeting.scheduledAt).toLocaleString()} &nbsp;|&nbsp; ${esc(meeting.meetingType)} <span class="status">${esc(meeting.status)}</span></p>
    ${attendees ? `<p class="meta">Attendees: ${esc(attendees)}</p>` : ""}
  </div>

  ${agenda.length ? `<h2>Agenda</h2><ul>${agenda.map((a) => `<li>${esc(a)}</li>`).join("")}</ul>` : ""}

  <h2>Minutes</h2>
  <p class="minutes">${meeting.minutes ? esc(meeting.minutes) : "(no minutes recorded)"}</p>

  <h2>Action Items</h2>
  <table>
    <thead><tr><th>Item</th><th>Status</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="2">No action items</td></tr>'}</tbody>
  </table>

  <p style="margin-top:32px;font-size:11px;color:#9ca3af;text-align:center">Generated by VERIDIAN AI &middot; ${esc(meeting.systemId ?? "")}</p>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${meeting.systemId ?? "MOM"}.html"`,
      },
    })
  } catch (error) {
    if (error instanceof ServiceError) return NextResponse.json({ error: error.message }, { status: error.status })
    console.error("VERI Meetings export error:", error)
    return NextResponse.json({ error: "Failed to export meeting" }, { status: 500 })
  }
}
