-- Priority 3 UMR (tree4-unified/50-completion-plan/08-priority3-umr-tracker.yaml,
-- agent 1/umr-core). New foundational table: platform_assets, a single
-- Universal Metadata Registry every object on the platform can be indexed
-- into, instead of a full-table scan per object type. Investigated first,
-- not assumed: this did not exist before this migration -- see
-- ai-os/registry/ARTIFACTS.yaml (honest empty scaffold, left behind after
-- an earlier task's false "Universal Asset Registry" claim was caught and
-- corrected). This migration only adds the metadata index itself; it does
-- NOT retrofit the ~330 existing tables to register into it -- this pass
-- populates worker_agents/computation_engines/prompt_templates/
-- dynamic_chains only (see scripts/backfill-platform-assets.ts), a
-- documented follow-on covers the rest.
--
-- asset_id ('AST-000001') is generated by a real Postgres sequence, not an
-- app-side counter -- race-safe under concurrent inserts. registerAsset()
-- omits asset_id on insert and reads the column default back via
-- .returning(); the same default also makes any raw/manual insert correct
-- for free.

CREATE SEQUENCE IF NOT EXISTS compliance.asset_id_seq;

CREATE OR REPLACE FUNCTION compliance.generate_asset_id() RETURNS text
  LANGUAGE sql
  AS $$ SELECT 'AST-' || lpad(nextval('compliance.asset_id_seq')::text, 6, '0') $$;

DO $$ BEGIN
  CREATE TYPE compliance.asset_type AS ENUM (
    'report','screen','dashboard','ai_agent','workflow','api','prompt',
    'function','policy','rule','sql_query','email_template','notification',
    'template','project','task','document','decision','automation','role',
    'permission','computation_engine','dynamic_chain','other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE compliance.asset_status AS ENUM ('draft','active','archived','deleted');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS compliance.platform_assets (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  asset_id text NOT NULL UNIQUE DEFAULT compliance.generate_asset_id(),
  name text NOT NULL,
  asset_type compliance.asset_type NOT NULL,
  module text,
  department text,
  owner_id text, -- nullable = 'System'
  status compliance.asset_status NOT NULL DEFAULT 'active',
  created_by text,
  version text NOT NULL DEFAULT '1.0',
  tags jsonb NOT NULL DEFAULT '[]',
  ai_enabled boolean NOT NULL DEFAULT false,
  ai_capabilities jsonb,
  permissions jsonb,
  parent_asset_id text REFERENCES compliance.platform_assets(id),
  search_keywords text,
  purpose text,
  dependencies jsonb,
  source_table text NOT NULL,
  source_id text NOT NULL,
  org_id text, -- nullable = platform-tier asset, same convention as compliance.embeddings.org_id
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now(),
  -- One registry row per real object -- enforced at the DB level, not just
  -- in application code (registerAsset() also checks this pre-insert for a
  -- clean error, but the constraint is the actual guarantee).
  CONSTRAINT uq_platform_assets_source UNIQUE (source_table, source_id)
);

CREATE INDEX IF NOT EXISTS idx_platform_assets_type ON compliance.platform_assets(asset_type);
CREATE INDEX IF NOT EXISTS idx_platform_assets_module ON compliance.platform_assets(module);
CREATE INDEX IF NOT EXISTS idx_platform_assets_status ON compliance.platform_assets(status);
CREATE INDEX IF NOT EXISTS idx_platform_assets_owner ON compliance.platform_assets(owner_id);
CREATE INDEX IF NOT EXISTS idx_platform_assets_org ON compliance.platform_assets(org_id);
CREATE INDEX IF NOT EXISTS idx_platform_assets_parent ON compliance.platform_assets(parent_asset_id);
CREATE INDEX IF NOT EXISTS idx_platform_assets_tags ON compliance.platform_assets USING gin (tags);

-- Full-text search: mirrors the exact pattern compliance.documents already
-- uses (drizzle/0077_wave91_document_retention_fulltext_search.sql,
-- document-service.ts) -- a functional GIN index computed at query time,
-- no new stored tsvector column, consistent with this codebase's existing
-- "read-time computation over a live table" precedent.
CREATE INDEX IF NOT EXISTS idx_platform_assets_fulltext_search ON compliance.platform_assets
  USING gin (to_tsvector('english', coalesce(name, '') || ' ' || coalesce(search_keywords, '') || ' ' || coalesce(purpose, '')));

-- RLS: same nullable-org "org-scoped OR platform-default" posture as
-- compliance.veri_reward_achievement_definitions
-- (drizzle/0092_veri_reward.sql) -- app_runtime sees its own org's rows
-- plus every platform-tier (org_id IS NULL) row; service_role bypasses
-- entirely for admin/migration tooling.
ALTER TABLE compliance.platform_assets ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped_or_platform_default ON compliance.platform_assets FOR ALL TO app_runtime
    USING (org_id = compliance.current_org_id() OR org_id IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY service_role_bypass_platform_assets ON compliance.platform_assets FOR ALL TO service_role USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON compliance.platform_assets TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON compliance.platform_assets TO service_role;
GRANT USAGE ON SEQUENCE compliance.asset_id_seq TO app_runtime;
GRANT USAGE ON SEQUENCE compliance.asset_id_seq TO service_role;
