/// <reference types="bun-types" />
// Generates the pack a lawyer reads to review the DPDP job library and its playbook (owner, 2026-09-30):
//   dpdp-app/docs/LAWYER-REVIEW-PACK.md   one section per job, with the law it cites, every unconfirmed point, and boxes to tick
//   dpdp-app/docs/lawyer-review-checklist.csv   the same jobs as rows, so comments can be collected in a spreadsheet
//
// WHY THIS EXISTS: the library (31 firm + 28 institution jobs, drizzle/0602) and the words that explain each job to a busy person or to an AI
// (supabase/functions/dpdp-ai-link/playbook-data.ts) were written by AI authors and reviewed by other AI reviewers. No lawyer has reviewed
// them, and the pages say so. An AI cannot certify law; this script only gathers everything a lawyer needs into one place, in the order they
// will read it, so that the review is an afternoon and not a project. It writes NO verdict: every box is left empty and the top of the pack
// says "NOT REVIEWED". The lawyer's sign-off is a human act and is recorded by editing law.ts (removing a `verify` note) in a reviewed PR.
//
// Run:  bun scripts/dpdp/gen-lawyer-review-pack.ts          (rewrites both files; deterministic -- same inputs give the same bytes)
//       bun scripts/dpdp/gen-lawyer-review-pack.ts --check  (exit 1 if the committed files are out of date; used by the unit test)
//
// Sources, none copied by hand: LIB from scripts/dpdp/gen-library-seed.mjs (the jobs, their parts and law codes), PLAYBOOK_DATA from
// playbook-data.ts (the words), citeLawCode from law.ts (the plain meaning of each code and its `verify` note).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { PLAYBOOK_DATA } from "../../supabase/functions/dpdp-ai-link/playbook-data.ts"
import { PART_NAMES, type JobPlaybook } from "../../supabase/functions/dpdp-ai-link/playbook.ts"
import { citeLawCode, LAWS } from "../../supabase/functions/dpdp-ai-link/law.ts"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..")
const OUT_MD = join(ROOT, "dpdp-app/docs/LAWYER-REVIEW-PACK.md")
const OUT_CSV = join(ROOT, "dpdp-app/docs/lawyer-review-checklist.csv")

type LibJob = { key: string; edition: "firm" | "institution"; part: number; name: string; who: string; dataSet: string; law: string[]; dep: string | null }

/** The LIB block of gen-library-seed.mjs, evaluated in isolation (it is plain data + the tiny J() helper). */
export function loadLibrary(): LibJob[] {
  const src = readFileSync(join(ROOT, "scripts/dpdp/gen-library-seed.mjs"), "utf8").replace(/\r/g, "")
  const start = src.indexOf("var GO=")
  const end = src.indexOf("\nfunction esc(")
  if (start < 0 || end < 0) throw new Error("gen-library-seed.mjs no longer has the LIB block this script reads (var GO= ... function esc()).")
  const lib = new Function(`${src.slice(start, end)}\nreturn LIB`)() as Record<string, Array<[number, string, string, number, { ds: string; law: string[]; dep?: string }]>>
  const out: LibJob[] = []
  for (const edition of ["firm", "institution"] as const) {
    const jobs = lib[edition]
    jobs.forEach(([part, name, who, , o], i) => {
      out.push({ key: `${edition}-${String(i + 1).padStart(2, "0")}`, edition, part, name, who, dataSet: o.ds, law: o.law, dep: o.dep ?? null })
    })
  }
  return out
}

const md = (s: string) => s.replace(/\|/g, "\\|")
const csv = (s: string) => `"${s.replace(/"/g, '""').replace(/\r?\n/g, " ")}"`

export function build(): { md: string; csv: string; stats: { jobs: number; withPlaybook: number; codes: number; unconfirmed: number } } {
  const jobs = loadLibrary()
  const codeUse = new Map<string, string[]>()
  for (const j of jobs) for (const c of j.law) codeUse.set(c, [...(codeUse.get(c) ?? []), j.key])
  const codes = [...codeUse.keys()].sort()
  const cites = new Map(codes.map((c) => [c, citeLawCode(c)]))
  const unconfirmed = codes.filter((c) => c.slice(0, 2) !== "g:" && cites.get(c)?.verify)

  const L: string[] = []
  L.push("# VERIDIAN DPDP -- job library and playbook: pack for legal review")
  L.push("")
  L.push("> **STATUS: NOT REVIEWED BY A LAWYER.** Nothing in this pack has been confirmed by counsel. It was written and checked by AI. Every box below is empty on purpose.")
  L.push("")
  L.push("Generated by `scripts/dpdp/gen-lawyer-review-pack.ts` from the files named at the top of that script. Do not edit this file by hand; change the sources and regenerate.")
  L.push("")
  L.push("## What we are asking")
  L.push("")
  L.push("VERIDIAN DPDP gives an organisation a list of jobs (a **firm** edition of " + jobs.filter((j) => j.edition === "firm").length + " and an **institution** edition of " + jobs.filter((j) => j.edition === "institution").length + ") and, for each job, plain-language guidance a busy non-lawyer -- or an AI helping them -- follows. The pages say the list is not yet lawyer-reviewed. We would like counsel to read it and tell us, job by job, whether it is safe to put in front of customers.")
  L.push("")
  L.push("Please look for four kinds of problem, in this order of seriousness:")
  L.push("")
  L.push("1. **Wrong or overstated law** -- a section, rule, deadline or duty the text gets wrong, or states more firmly than the law does.")
  L.push("2. **A promise we cannot keep** -- wording that sounds like legal advice, a guarantee of compliance, or a substitute for the customer's own adviser.")
  L.push("3. **A missing duty or a missing caution** -- something a careful adviser would insist a small business or school be told.")
  L.push("4. **A job that should never be marked \"doesn't apply\"** -- or one where that answer needs more than a sentence of explanation.")
  L.push("")
  L.push("The playbook text deliberately does **not** state section numbers, rule numbers, penalties or deadlines of its own; the law behind each job is looked up from the table in section 2 below, which is where a citation error would live.")
  L.push("")
  L.push("## 1. The four sources of law the library cites")
  L.push("")
  L.push("| Code prefix | Instrument | Status as the pages describe it |")
  L.push("|---|---|---|")
  for (const [k, v] of Object.entries(LAWS)) L.push(`| \`${k}:\` | ${md(v.label)} | ${md(v.title)} |`)
  L.push("")
  L.push(`## 2. Every law code cited (${codes.length}), and what the product says it means`)
  L.push("")
  L.push(`**${unconfirmed.length} of these carry an open \`verify\` note** -- the product's own admission that the number or topic is not confirmed. They are listed first because they are the likeliest to be wrong.`)
  L.push("")
  L.push("| Code | Plain meaning shown to customers | Open point for counsel | Used by | Confirmed? |")
  L.push("|---|---|---|---|---|")
  const ordered = [...unconfirmed, ...codes.filter((c) => !unconfirmed.includes(c))]
  for (const c of ordered) {
    const ct = cites.get(c)
    const meaning = c.startsWith("g:") ? "Good practice -- not a legal duty" : ct ? `${ct.short}: ${ct.topic ?? "(no topic label recorded)"}` : "(code not recognised by the product)"
    const point = c.startsWith("g:") ? "" : ct?.verify ?? ""
    L.push(`| \`${c}\` | ${md(meaning)} | ${md(point)} | ${codeUse.get(c)!.join(", ")} | [ ] Yes  [ ] No |`)
  }
  L.push("")
  L.push("## 3. The jobs")
  L.push("")
  L.push("Each job lists: where it sits in the list, who does it, the law it cites, then the guidance an AI or a person is shown. Tick a box, or write what should change.")
  L.push("")
  let withPlaybook = 0
  const rows: string[] = [["key", "edition", "part", "job", "law codes", "playbook present", "law text OK (Y/N)", "guidance OK (Y/N)", "'doesn't apply' wording OK (Y/N)", "comment"].map(csv).join(",")]
  for (const edition of ["firm", "institution"] as const) {
    L.push(`### ${edition === "firm" ? "Firm edition (CA / accounting / professional-services firm)" : "Institution edition (school)"}`)
    L.push("")
    let part = 0
    for (const j of jobs.filter((x) => x.edition === edition)) {
      if (j.part !== part) {
        part = j.part
        L.push(`#### Part ${part} -- ${PART_NAMES[part] ?? ""}`)
        L.push("")
      }
      const pb: JobPlaybook | undefined = PLAYBOOK_DATA[j.key]
      if (pb) withPlaybook++
      L.push(`##### \`${j.key}\` -- ${j.name}`)
      L.push("")
      L.push(`- **Done by:** ${j.who}  ·  **Data set:** ${j.dataSet}${j.dep ? `  ·  **Only after:** "${j.dep}"` : ""}`)
      L.push(`- **Law cited:** ${j.law.length ? j.law.map((c) => `\`${c}\``).join(", ") : "none"}`)
      if (pb) {
        L.push(`- **Why (as shown):** ${pb.why}`)
        L.push(`- **Who (as shown):** ${pb.who}`)
        L.push("- **Steps (as shown):**")
        pb.steps.forEach((s, i) => L.push(`  ${i + 1}. ${s}`))
        L.push(`- **Evidence of "done":** ${pb.proof}`)
        L.push(`- **"Doesn't apply" is honest when:** ${pb.notApplicableWhen ?? "(no case listed -- the AI is told to say so and leave it to the owner)"}`)
        if (pb.watchFor.length) L.push(`- **Watch for:** ${pb.watchFor.join(" / ")}`)
        if (pb.email) L.push(`- **Email drafted for the user to send:** to *${pb.email.to}*, subject "${pb.email.subject}"`)
      } else {
        L.push("- **Guidance:** none written for this job -- a generic per-Part text is shown.")
      }
      L.push("- **Counsel:**  [ ] law text correct   [ ] guidance safe   [ ] \"doesn't apply\" wording right   [ ] change needed --  ____________________________")
      L.push("")
      rows.push([j.key, edition, String(j.part), j.name, j.law.join(" "), pb ? "yes" : "no", "", "", "", ""].map(csv).join(","))
    }
  }
  L.push("## 4. Sign-off")
  L.push("")
  L.push("| Reviewer name | Bar Council / practising registration no. | Date | Scope reviewed (all / firm / institution / list) | Signature |")
  L.push("|---|---|---|---|---|")
  L.push("| | | | | |")
  L.push("")
  L.push("A sign-off does not change the product by itself. The reviewer's corrections are made in `law.ts` / `playbook-data.ts` through an ordinary reviewed change, and an open `verify` note is removed only when the reviewer has confirmed that point.")
  L.push("")
  return { md: L.join("\n"), csv: rows.join("\n") + "\n", stats: { jobs: jobs.length, withPlaybook, codes: codes.length, unconfirmed: unconfirmed.length } }
}

if (import.meta.main) {
  const { md: mdText, csv: csvText, stats } = build()
  if (process.argv.includes("--check")) {
    const same = existsSync(OUT_MD) && existsSync(OUT_CSV) && readFileSync(OUT_MD, "utf8").replace(/\r/g, "") === mdText && readFileSync(OUT_CSV, "utf8").replace(/\r/g, "") === csvText
    console.log(same ? "lawyer review pack is up to date" : "lawyer review pack is OUT OF DATE -- run: bun scripts/dpdp/gen-lawyer-review-pack.ts")
    process.exit(same ? 0 : 1)
  }
  mkdirSync(dirname(OUT_MD), { recursive: true })
  writeFileSync(OUT_MD, mdText, "utf8")
  writeFileSync(OUT_CSV, csvText, "utf8")
  console.log(`wrote ${OUT_MD} and ${OUT_CSV}: ${stats.jobs} jobs (${stats.withPlaybook} with a written playbook), ${stats.codes} law codes, ${stats.unconfirmed} with an open verify note`)
}
