-- WO-DPDP-006/007: all 6 pending DPDP migrations, consolidated into one
-- paste, in dependency order, made idempotent (safe to run more than once
-- if it's ever unclear whether a prior run fully completed -- every
-- CREATE TYPE/TRIGGER/CONSTRAINT is now guarded, every CREATE TABLE/ADD
-- COLUMN uses IF NOT EXISTS). This file is generated by concatenating the
-- 6 already-reviewed migration files (0422-0427) with idempotency guards
-- added; it does not introduce any new logic beyond that.
--
-- Paste this whole file into the Supabase SQL Editor and run it once. The
-- verification block at the end reports exactly what landed.

BEGIN;
-- ============================================================
-- 0422_dpdp_obligation_write_restrict_auditors
-- ============================================================
-- WO-DPDP-002 Section 4.1 (RLS test row: "Auditor write is refused").
--
-- 0415's own comment said this was "enforced at the API/service layer via
-- requireRole" -- checked directly (WO-DPDP-002 test-planning pass,
-- 2026-09-16): no such capability check exists anywhere in the dpdp route
-- layer. Every mutating obligation route (accept/reject/assign/submit/
-- not-my-job/stuck) checks only requireDpdpSession() (any authenticated org
-- member) and then loadObligationOrThrow(tx, orgId, obligationId), which
-- filters WHERE org_id = orgId -- the ACTING org, not any RLS-visible org --
-- so today's app code happens not to let an auditor-related org touch
-- another org's obligation. But that safety is accidental (a side effect of
-- one helper's WHERE clause), not designed, and dpdp.obligation's own RLS
-- policy (app_runtime_relationship_scoped, FOR ALL) would allow the write at
-- the database level if any future code path queried/updated by
-- obligationId alone, relying on RLS the way every other RLS'd table in
-- this app does. This migration makes the database itself enforce what the
-- comment already claimed was true: an 'audits' relationship grants READ,
-- never WRITE. 'advises' (the CA/advisor role, which legitimately reviews
-- and accepts/rejects submitted proof -- see V.review in the spec) keeps
-- write access; only 'audits' loses it.
--
-- Verified via src/lib/services/dpdp-obligation-rls.test.ts: before this
-- migration, an app_runtime session in an 'audits' relationship can UPDATE
-- another org's obligation row; after, the identical UPDATE is rejected by
-- RLS (0 rows affected, not an exception -- see that test's own comment on
-- why UPDATE ... RETURNING rather than an error is what a blocked RLS
-- write actually looks like).
DROP POLICY IF EXISTS app_runtime_relationship_scoped ON "dpdp"."obligation";--> statement-breakpoint

CREATE POLICY app_runtime_obligation_read ON "dpdp"."obligation" FOR SELECT TO app_runtime
  USING (
    org_id = dpdp.current_org_id()
    OR (
      assigned_processor_org_id = dpdp.current_org_id()
      AND EXISTS (
        SELECT 1 FROM dpdp.relationship r
        WHERE r.kind = 'processes_for' AND r.from_org = dpdp.current_org_id()
          AND r.to_org = obligation.org_id AND r.agreement_signed_at IS NOT NULL AND r.ended_at IS NULL
      )
    )
    OR EXISTS (
      SELECT 1 FROM dpdp.relationship r
      WHERE r.kind IN ('advises', 'audits') AND r.from_org = dpdp.current_org_id()
        AND r.to_org = obligation.org_id AND r.ended_at IS NULL
    )
  );--> statement-breakpoint

CREATE POLICY app_runtime_obligation_write ON "dpdp"."obligation" FOR INSERT TO app_runtime
  WITH CHECK (
    org_id = dpdp.current_org_id()
    OR (
      assigned_processor_org_id = dpdp.current_org_id()
      AND EXISTS (
        SELECT 1 FROM dpdp.relationship r
        WHERE r.kind = 'processes_for' AND r.from_org = dpdp.current_org_id()
          AND r.to_org = obligation.org_id AND r.agreement_signed_at IS NOT NULL AND r.ended_at IS NULL
      )
    )
    OR EXISTS (
      SELECT 1 FROM dpdp.relationship r
      WHERE r.kind = 'advises' AND r.from_org = dpdp.current_org_id()
        AND r.to_org = obligation.org_id AND r.ended_at IS NULL
    )
  );--> statement-breakpoint

CREATE POLICY app_runtime_obligation_update ON "dpdp"."obligation" FOR UPDATE TO app_runtime
  USING (
    org_id = dpdp.current_org_id()
    OR (
      assigned_processor_org_id = dpdp.current_org_id()
      AND EXISTS (
        SELECT 1 FROM dpdp.relationship r
        WHERE r.kind = 'processes_for' AND r.from_org = dpdp.current_org_id()
          AND r.to_org = obligation.org_id AND r.agreement_signed_at IS NOT NULL AND r.ended_at IS NULL
      )
    )
    OR EXISTS (
      SELECT 1 FROM dpdp.relationship r
      WHERE r.kind = 'advises' AND r.from_org = dpdp.current_org_id()
        AND r.to_org = obligation.org_id AND r.ended_at IS NULL
    )
  )
  WITH CHECK (
    org_id = dpdp.current_org_id()
    OR (
      assigned_processor_org_id = dpdp.current_org_id()
      AND EXISTS (
        SELECT 1 FROM dpdp.relationship r
        WHERE r.kind = 'processes_for' AND r.from_org = dpdp.current_org_id()
          AND r.to_org = obligation.org_id AND r.agreement_signed_at IS NOT NULL AND r.ended_at IS NULL
      )
    )
    OR EXISTS (
      SELECT 1 FROM dpdp.relationship r
      WHERE r.kind = 'advises' AND r.from_org = dpdp.current_org_id()
        AND r.to_org = obligation.org_id AND r.ended_at IS NULL
    )
  );--> statement-breakpoint

CREATE POLICY app_runtime_obligation_delete ON "dpdp"."obligation" FOR DELETE TO app_runtime
  USING (
    org_id = dpdp.current_org_id()
    OR EXISTS (
      SELECT 1 FROM dpdp.relationship r
      WHERE r.kind = 'advises' AND r.from_org = dpdp.current_org_id()
        AND r.to_org = obligation.org_id AND r.ended_at IS NULL
    )
  );


-- ============================================================
-- 0423_dpdp_commercial_and_panel_schema
-- ============================================================
-- WO-DPDP-003 Section 4.9/4.10: commercial (file packs, custody, partner
-- sales) and the CERT-In-constrained auditor/cyber panel. All net-new.
--
-- Generated by `bun run db:generate`, then hand-edited: the raw generator
-- output also tried to CREATE TABLE dpdp.login_token and dpdp.session --
-- both already live in production (0417_dpdp_phase2_auth_tables). This is
-- the same drizzle-kit snapshot-drift class this repo's CLAUDE.md already
-- documents extensively elsewhere (tables added via db:push never make it
-- into a tracked snapshot, so a later db:generate "rediscovers" them as
-- missing) -- confirmed directly via information_schema before editing
-- this file, not assumed. Removed those two CREATE TABLE blocks; only the
-- 7 genuinely new tables below are real drizzle-kit output, unedited.
DO $$ BEGIN
  CREATE TYPE "dpdp"."credential_applies_to" AS ENUM('org', 'person', 'both');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."credential_region" AS ENUM('IN', 'EU', 'US', 'GLOBAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."firm_cred_state" AS ENUM('declared', 'evidence', 'expired');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."credential" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"issuer" text NOT NULL,
	"region" "dpdp"."credential_region" NOT NULL,
	"applies_to" "dpdp"."credential_applies_to" NOT NULL,
	"scope" text,
	"exact_wording" text,
	"no_scheme" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."custody" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"obligation_file_id" text NOT NULL,
	"term_years" integer DEFAULT 10 NOT NULL,
	"paid_at" timestamp,
	"keep_until" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."file_pack" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"pack_size" integer NOT NULL,
	"files_remaining" integer NOT NULL,
	"purchased_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."firm_cred" (
	"id" text PRIMARY KEY NOT NULL,
	"firm_id" text NOT NULL,
	"credential_id" text NOT NULL,
	"expires_on" date,
	"state" "dpdp"."firm_cred_state" DEFAULT 'declared' NOT NULL,
	"artefact_id" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."panel_firm" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"name" text NOT NULL,
	"city" text,
	"since" date,
	"headcount" integer,
	"response_sla" text,
	"jobs_via_us" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."panel_request" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"firm_id" text NOT NULL,
	"requested_at" timestamp DEFAULT now() NOT NULL,
	"responded_at" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."partner_sale" (
	"id" text PRIMARY KEY NOT NULL,
	"partner_id" text NOT NULL,
	"org_id" text NOT NULL,
	"at" timestamp DEFAULT now() NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	"commission_paise" integer NOT NULL,
	"recurs" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
-- RLS: straightforward org_id-scoped tenant isolation, matching 0415's
-- own generic-loop pattern for the rest of dpdp.*. credential/panel_firm
-- are read-mostly reference/marketplace data -- credential has no org_id
-- at all (global reference list, like obligation_template), panel_firm and
-- panel_request are org-scoped for writes but panel_firm's own listing is
-- meant to be visible across orgs (the "find an auditor" marketplace is
-- read-across-orgs by design), so panel_firm gets a permissive SELECT
-- (any authenticated org may browse the marketplace) alongside an
-- owner-org-scoped write policy, not a single org_id=current_org_id() FOR ALL.
ALTER TABLE "dpdp"."file_pack" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."file_pack" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."custody" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."custody" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- partner_sale has no org_id-based tenant context to scope by (the acting
-- session is a partner applicant, not a dpdp org) -- readable/writable
-- only by service_role until a real partner-auth plane exists (WO-DPDP-003
-- doesn't specify partner login; flagged, not invented). app_runtime gets
-- no policy at all here deliberately, so RLS default-denies every app_runtime
-- access until that plane is designed.
ALTER TABLE "dpdp"."partner_sale" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

ALTER TABLE "dpdp"."panel_firm" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_marketplace_read ON "dpdp"."panel_firm" FOR SELECT TO app_runtime USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_write ON "dpdp"."panel_firm" FOR INSERT TO app_runtime WITH CHECK (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_update ON "dpdp"."panel_firm" FOR UPDATE TO app_runtime USING (org_id = dpdp.current_org_id()) WITH CHECK (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."panel_request" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."panel_request" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- credential/firm_cred: credential is global reference data (like
-- obligation_template -- readable by everyone, writable by nobody at the
-- app layer; only service_role seeds it). firm_cred is scoped through its
-- firm_id -> panel_firm.org_id, not its own org_id column (it has none).
ALTER TABLE "dpdp"."credential" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_read_all ON "dpdp"."credential" FOR SELECT TO app_runtime USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."firm_cred" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_read_all ON "dpdp"."firm_cred" FOR SELECT TO app_runtime USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_write ON "dpdp"."firm_cred" FOR INSERT TO app_runtime
    WITH CHECK (EXISTS (SELECT 1 FROM dpdp.panel_firm f WHERE f.id = firm_id AND f.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_firm_update ON "dpdp"."firm_cred" FOR UPDATE TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.panel_firm f WHERE f.id = firm_id AND f.org_id = dpdp.current_org_id()))
    WITH CHECK (EXISTS (SELECT 1 FROM dpdp.panel_firm f WHERE f.id = firm_id AND f.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "dpdp"."file_pack", "dpdp"."custody", "dpdp"."partner_sale", "dpdp"."panel_firm",
  "dpdp"."credential", "dpdp"."firm_cred", "dpdp"."panel_request"
TO service_role;

-- Seed: the ONE CERT-In credential row, exact_wording as the sole source
-- of that sentence anywhere in this system (WO 4.10). dpdp_panel_service.ts
-- must render from this row, never a hand-typed string.
INSERT INTO "dpdp"."credential" (kind, issuer, region, applies_to, scope, exact_wording, no_scheme) VALUES
  ('cert_in_empanelment', 'CERT-In', 'IN', 'org', 'Section 10 data audit', 'This Organization is empanelled by CERT-In for providing information Security Auditing Service', false),
  ('dpdp_auditor', 'none', 'IN', 'both', 'Section 10 data audit', NULL, true)
ON CONFLICT DO NOTHING;


-- ============================================================
-- 0424_dpdp_ai_link_and_proposals
-- ============================================================
-- WO-DPDP-004 Section 5.10 -- "The AI Link", full formal schema
-- (supersedes this session's own earlier, simpler draft, never applied to
-- production -- see schema.ts's own comment on this table).
DO $$ BEGIN
  CREATE TYPE "dpdp"."ai_proposal_state" AS ENUM('pending', 'applied', 'discarded', 'expired');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."ai_link" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"identity_id" text NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL,
	"revoked_at" timestamp,
	CONSTRAINT "ai_link_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."ai_link_read" (
	"id" text PRIMARY KEY NOT NULL,
	"link_id" text NOT NULL,
	"at" timestamp DEFAULT now() NOT NULL,
	"user_agent_family" text,
	"ip_prefix" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."ai_proposal" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"ref" text NOT NULL,
	"source_label" text NOT NULL,
	"arrived_at" timestamp DEFAULT now() NOT NULL,
	"raw" text NOT NULL,
	"state" "dpdp"."ai_proposal_state" DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."ai_proposal_line" (
	"id" text PRIMARY KEY NOT NULL,
	"proposal_id" text NOT NULL,
	"seq" integer NOT NULL,
	"verb" text NOT NULL,
	"target_key" text NOT NULL,
	"payload" jsonb,
	"allowed" boolean NOT NULL,
	"refusal_reason" text,
	"approved" boolean DEFAULT false NOT NULL,
	"applied_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "dpdp"."ai_link" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_own_org ON "dpdp"."ai_link" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
-- The public token-lookup route (GET /api/dpdp/ai/[token]) has no tenant
-- context at all by design -- same no-context preauth shape as
-- 0420's app_runtime_event_preauth_insert.
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_lookup ON "dpdp"."ai_link" FOR SELECT TO app_runtime USING (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- ai_link_read has no org_id of its own (scoped through link_id ->
-- ai_link.org_id) -- RLS via a subquery, and the preauth INSERT (the
-- public route logging its own read) needs no context either.
ALTER TABLE "dpdp"."ai_link_read" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_link_org ON "dpdp"."ai_link_read" FOR SELECT TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.ai_link l WHERE l.id = link_id AND l.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_log_read ON "dpdp"."ai_link_read" FOR INSERT TO app_runtime WITH CHECK (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."ai_proposal" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."ai_proposal" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."ai_proposal_line" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_proposal_org ON "dpdp"."ai_proposal_line" FOR ALL TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.ai_proposal p WHERE p.id = proposal_id AND p.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "dpdp"."ai_link", "dpdp"."ai_link_read", "dpdp"."ai_proposal", "dpdp"."ai_proposal_line"
TO service_role;


-- ============================================================
-- 0425_dpdp_projection_function
-- ============================================================
-- WO-DPDP-004 Section 2.2, corrected per WO-DPDP-006 Section 2: this MUST
-- be a real Postgres SQL function, not app code, because the personal-data
-- exclusion is a security boundary enforced by the query itself -- no
-- future route, refactor or careless change can leak a principal's name,
-- phone or email through it, because those columns are never referenced
-- in the function body at all (SECURITY DEFINER means it runs with the
-- function owner's privileges and bypasses RLS entirely -- which is
-- exactly why this function must be hand-audited to touch nothing
-- personal-data-shaped, since RLS cannot be relied on to protect it).
--
-- p_org is `text`, not `uuid` -- this schema's organisation.id is a cuid2
-- text value (createId(), matching every other id in dpdp.*), not a native
-- Postgres uuid. The WO's own abbreviated signature assumed uuid PKs;
-- adapted to the real column type rather than casting or changing the PK
-- type project-wide.
CREATE OR REPLACE FUNCTION dpdp.projection(p_org text, p_asof timestamptz DEFAULT now())
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = 'dpdp', 'pg_temp'
AS $$
  WITH org AS (
    SELECT name FROM dpdp.organisation WHERE id = p_org
  ),
  duties AS (
    SELECT
      count(*) AS total,
      count(*) FILTER (WHERE state = 'closed') AS done,
      count(*) FILTER (WHERE state = 'open' AND due_on < p_asof::date) AS late
    FROM dpdp.obligation WHERE org_id = p_org
  ),
  cats AS (
    SELECT count(*) AS total FROM dpdp.data_category WHERE org_id = p_org
  ),
  located AS (
    SELECT count(DISTINCT dc.id) AS n
    FROM dpdp.data_category dc
    JOIN dpdp.data_location dl ON dl.category_id = dc.id AND dl.state = 'confirmed'
    WHERE dc.org_id = p_org
  ),
  rels AS (
    SELECT count(*) AS total, count(*) FILTER (WHERE agreement_signed_at IS NOT NULL) AS signed
    FROM dpdp.relationship WHERE from_org = p_org
  ),
  rights AS (
    -- Count only -- "no row from consent_token or rights_request beyond a
    -- reference number" (WO 2.2); this doesn't even select the reference.
    SELECT count(*) AS n FROM dpdp.rights_request
    WHERE org_id = p_org AND answered_at IS NULL AND received_at <= p_asof
  ),
  griev AS (
    SELECT count(*) AS n FROM dpdp.grievance WHERE org_id = p_org
  )
  SELECT string_agg(line, E'\n') FROM (
    VALUES
      (1, 'VERIDIAN · DPDP position for ' || coalesce((SELECT name FROM org), 'this organisation')),
      (2, 'Snapshot ' || to_char(p_asof, 'YYYY-MM-DD') || ' · read-only · no personal data'),
      (3, ''),
      (4, 'DUTIES  ' || (SELECT total FROM duties) || ' total · ' || (SELECT done FROM duties) || ' done · ' || (SELECT late FROM duties) || ' late'),
      (5, 'DATA MAP  ' || (SELECT total FROM cats) || ' categories · ' || (SELECT n FROM located) || ' located · ' || ((SELECT total FROM cats) - (SELECT n FROM located)) || ' unknown'),
      (6, 'OUTSIDE FIRMS  ' || (SELECT total FROM rels) || ' · agreements signed ' || (SELECT signed FROM rels)),
      (7, 'OPEN REQUESTS  ' || (SELECT n FROM rights)),
      (8, 'COMPLAINTS  ' || (SELECT n FROM griev)),
      (9, ''),
      (10, 'HOW TO REPLY'),
      (11, '  Output a VERIDIAN-INSTRUCTIONS block: one JSON array of'),
      (12, '  proposed lines, each { verb, targetKey, payload }.'),
      (13, '  verb is one of: ASSIGN, SET_DUE, NOTE, MARK_NA (reason required), DRAFT.'),
      (14, '  targetKey must be a real duty reference already in this snapshot.'),
      (15, '  Nothing else parses. The person pastes this back and approves'),
      (16, '  each line themselves before anything moves.')
  ) AS t(ord, line)
  ORDER BY ord;
$$;
--> statement-breakpoint
-- SECURITY DEFINER functions default to EXECUTE granted to PUBLIC in
-- Postgres -- revoke that and grant only to the roles that actually call
-- it, so no other role can invoke a function running with elevated
-- privileges "for free."
REVOKE ALL ON FUNCTION dpdp.projection(text, timestamptz) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION dpdp.projection(text, timestamptz) TO app_runtime, service_role;


-- ============================================================
-- 0426_dpdp_proof_modes_erasure_tasks
-- ============================================================
-- WO-DPDP-005 Sections 1-3: three proof modes (declare/fingerprint/hold,
-- replacing document custody with metadata-only proof by default),
-- erasure-as-coordination (we never touch a client's own systems), and the
-- email-as-interface task/token model.
DO $$ BEGIN
  CREATE TYPE "dpdp"."email_token_action" AS ENUM('yes', 'no', 'sign_in');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."erasure_place_state" AS ENUM('waiting', 'done', 'cannot', 'lawful_hold');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."erasure_place_type" AS ENUM('app', 'folder', 'email', 'paper', 'vendor', 'backup', 'law');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."proof_mode" AS ENUM('declare', 'fingerprint', 'hold');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."storage_state" AS ENUM('never_stored', 'held', 'deleted');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."task_answer" AS ENUM('yes', 'no');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE TYPE "dpdp"."task_answered_via" AS ENUM('email', 'app');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."email_token" (
	"id" text PRIMARY KEY NOT NULL,
	"task_id" text NOT NULL,
	"identity_id" text NOT NULL,
	"action" "dpdp"."email_token_action" NOT NULL,
	"token_hash" text NOT NULL,
	"issued_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL,
	"used_at" timestamp,
	CONSTRAINT "email_token_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."erasure_answer" (
	"id" text PRIMARY KEY NOT NULL,
	"erasure_id" text NOT NULL,
	"sent_at" timestamp DEFAULT now() NOT NULL,
	"body" text NOT NULL,
	"sent_by" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."erasure_place" (
	"id" text PRIMARY KEY NOT NULL,
	"erasure_id" text NOT NULL,
	"data_location_id" text NOT NULL,
	"place_type" "dpdp"."erasure_place_type" NOT NULL,
	"holder_person_id" text,
	"holder_org_id" text,
	"state" "dpdp"."erasure_place_state" DEFAULT 'waiting' NOT NULL,
	"confirmed_by" text,
	"confirmed_at" timestamp,
	"method_note" text,
	"refusal_law" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."erasure_request" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"rights_request_id" text NOT NULL,
	"received_at" timestamp DEFAULT now() NOT NULL,
	"due_at" timestamp NOT NULL,
	"state" text DEFAULT 'open' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."task" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"obligation_id" text NOT NULL,
	"seq" integer NOT NULL,
	"text" text NOT NULL,
	"subtext" text,
	"option_yes" text NOT NULL,
	"option_no" text NOT NULL,
	"answer" "dpdp"."task_answer",
	"answered_by" text,
	"answered_at" timestamp,
	"answered_via" "dpdp"."task_answered_via",
	"token_id" text
);
--> statement-breakpoint
ALTER TABLE "dpdp"."artefact" ADD COLUMN IF NOT EXISTS "proof_mode" "dpdp"."proof_mode" DEFAULT 'declare' NOT NULL;--> statement-breakpoint
ALTER TABLE "dpdp"."artefact" ADD COLUMN IF NOT EXISTS "storage_state" "dpdp"."storage_state" DEFAULT 'never_stored' NOT NULL;--> statement-breakpoint
ALTER TABLE "dpdp"."artefact" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "dpdp"."artefact" ADD COLUMN IF NOT EXISTS "client_location" text;--> statement-breakpoint
ALTER TABLE "dpdp"."artefact" ADD COLUMN IF NOT EXISTS "storage_path" text;--> statement-breakpoint
ALTER TABLE "dpdp"."obligation_template" ADD COLUMN IF NOT EXISTS "proof_mode" "dpdp"."proof_mode" DEFAULT 'declare' NOT NULL;--> statement-breakpoint

-- WO-005 1: "storage_state='never_stored' must be impossible to pair with
-- a storage path. Enforce with a CHECK constraint" -- the actual database-
-- level guarantee, not app-layer discipline.
DO $$ BEGIN
  ALTER TABLE "dpdp"."artefact" ADD CONSTRAINT "artefact_never_stored_no_path" CHECK (storage_state <> 'never_stored' OR storage_path IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- RLS: org_id-scoped, matching 0415's generic pattern. erasure_place has
-- no org_id of its own (scoped through erasure_id -> erasure_request.org_id),
-- same shape as ai_proposal_line's own subquery policy in 0424.
ALTER TABLE "dpdp"."erasure_request" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."erasure_request" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."erasure_place" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_erasure_org ON "dpdp"."erasure_place" FOR ALL TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.erasure_request e WHERE e.id = erasure_id AND e.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."erasure_answer" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_erasure_org ON "dpdp"."erasure_answer" FOR ALL TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.erasure_request e WHERE e.id = erasure_id AND e.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."task" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_org_scoped ON "dpdp"."task" FOR ALL TO app_runtime USING (org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
-- Answering FROM an email (the whole point of WO-005 3) has no session/org
-- context at all -- mirrors 0420's app_runtime_event_preauth_insert
-- precedent, scoped to UPDATE (answering an existing task) rather than
-- INSERT (tasks are only ever created from within the app, session-gated).
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_answer ON "dpdp"."task" FOR UPDATE TO app_runtime
    USING (dpdp.current_org_id() IS NULL) WITH CHECK (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

-- email_token has no org_id of its own (scoped through task_id ->
-- task.org_id); the public email-click route needs no context to look
-- itself up and mark itself used, same preauth shape as above.
ALTER TABLE "dpdp"."email_token" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_task_org ON "dpdp"."email_token" FOR SELECT TO app_runtime
    USING (EXISTS (SELECT 1 FROM dpdp.task t WHERE t.id = task_id AND t.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_insert ON "dpdp"."email_token" FOR INSERT TO app_runtime WITH CHECK (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_use ON "dpdp"."email_token" FOR UPDATE TO app_runtime
    USING (dpdp.current_org_id() IS NULL) WITH CHECK (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "dpdp"."erasure_request", "dpdp"."erasure_place", "dpdp"."erasure_answer",
  "dpdp"."task", "dpdp"."email_token"
TO service_role;


-- ============================================================
-- 0427_dpdp_membership_scoped_email
-- ============================================================
-- WO-DPDP-007 Sections 2 and 4: inbound message routing, digest-send caps,
-- independence conflict blocking, and membership-scoped email tokens.
DO $$ BEGIN
  CREATE TYPE "dpdp"."digest_format" AS ENUM('single', 'batched');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."digest_send" (
	"id" text PRIMARY KEY NOT NULL,
	"identity_id" text NOT NULL,
	"sent_at" timestamp DEFAULT now() NOT NULL,
	"membership_ids" text[] NOT NULL,
	"format" "dpdp"."digest_format" NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."inbound_message" (
	"id" text PRIMARY KEY NOT NULL,
	"membership_id" text,
	"task_id" text,
	"received_at" timestamp DEFAULT now() NOT NULL,
	"from_address" text NOT NULL,
	"body_stripped" text,
	"raw_retained_until" timestamp,
	"action_taken" text,
	"discarded_reason" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dpdp"."independence_block" (
	"id" text PRIMARY KEY NOT NULL,
	"membership_id" text NOT NULL,
	"target_org_id" text NOT NULL,
	"attempted_at" timestamp DEFAULT now() NOT NULL,
	"action" text NOT NULL,
	"reason" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "dpdp"."email_token" ADD COLUMN IF NOT EXISTS "membership_id" text NOT NULL;--> statement-breakpoint

-- WO-007 4.3: "the token is the enforcement, not a check" -- a trigger,
-- not a service-layer if-statement, so a future insert path that forgets
-- to check this still cannot create a cross-organisation token.
CREATE OR REPLACE FUNCTION dpdp.email_token_membership_matches_task_org() RETURNS trigger
  LANGUAGE plpgsql AS $$
DECLARE
  task_org text;
  member_org text;
BEGIN
  SELECT org_id INTO task_org FROM dpdp.task WHERE id = NEW.task_id;
  SELECT org_id INTO member_org FROM dpdp.membership WHERE id = NEW.membership_id;
  IF task_org IS NULL OR member_org IS NULL OR task_org <> member_org THEN
    RAISE EXCEPTION 'dpdp.email_token: membership % does not belong to task %''s organisation (WO-DPDP-007 4.3)', NEW.membership_id, NEW.task_id;
  END IF;
  RETURN NEW;
END;
$$;--> statement-breakpoint
CREATE OR REPLACE TRIGGER dpdp_email_token_membership_scope
  BEFORE INSERT ON dpdp.email_token
  FOR EACH ROW EXECUTE FUNCTION dpdp.email_token_membership_matches_task_org();--> statement-breakpoint

-- RLS, matching established patterns. inbound_message/digest_send/
-- independence_block have no org_id of their own -- scoped through
-- membership_id -> membership.org_id (a subquery policy, same shape as
-- ai_proposal_line/erasure_place before it).
ALTER TABLE "dpdp"."inbound_message" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_membership_org ON "dpdp"."inbound_message" FOR SELECT TO app_runtime
    USING (membership_id IS NOT NULL AND EXISTS (SELECT 1 FROM dpdp.membership m WHERE m.id = membership_id AND m.org_id = dpdp.current_org_id()));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
-- The inbound webhook itself has no session/org context -- preauth insert,
-- same shape as every other no-context write path in this schema.
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_insert ON "dpdp"."inbound_message" FOR INSERT TO app_runtime WITH CHECK (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."digest_send" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
-- digest_send has no org_id at all (it's identity-scoped, spanning
-- however many orgs that identity belongs to) -- readable by app_runtime
-- only through a context-free preauth path (the digest job itself runs
-- with no single org's context, by design) until a real per-identity
-- read surface is built; flagged, not over-engineered speculatively.
DO $$ BEGIN
  CREATE POLICY app_runtime_preauth_all ON "dpdp"."digest_send" FOR ALL TO app_runtime USING (dpdp.current_org_id() IS NULL) WITH CHECK (dpdp.current_org_id() IS NULL);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

ALTER TABLE "dpdp"."independence_block" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
  CREATE POLICY app_runtime_via_target_org ON "dpdp"."independence_block" FOR ALL TO app_runtime USING (target_org_id = dpdp.current_org_id());
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON
  "dpdp"."digest_send", "dpdp"."inbound_message", "dpdp"."independence_block"
TO service_role;

-- ============================================================
-- BOOKKEEPING -- records these 6 as applied in the same ledger table
-- the app's own migration tooling reads, so this repo's tracking stays
-- accurate afterward (the same "drizzle ledger" issue from Item 1,
-- applied here to these 6 up front instead of discovered later).
-- ============================================================
INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES
  ('2586de5c04bdead4a14199112c2ca6f39b402d178d94497c6061760fe077c481', 1789495400000),
  ('c844cae4794ad855c65f7e58487800f3f96b7bdd3413c33357bf1bc666058ce2', 1789538112094),
  ('c8be9b12621dc11d2b557fb72038787916ec5bc6052a6faa60010242d889019f', 1789539351417),
  ('e72f89547fb68d52d4527ea1f49d91339cc98cb165702768ee6e60aca9b23828', 1789539352417),
  ('6f5fa4e822fe346c15c3a55edf242ac6865d8afa25a96564910a0c25648ffab5', 1789541577746),
  ('c92d5a8e86bfad4c86911f9d5d184359124a86936610c0b7994d925fb0f88cb6', 1789541912511)
ON CONFLICT DO NOTHING;

-- ============================================================
-- VERIFICATION -- read this after running
-- ============================================================
SELECT
  (SELECT count(*) FROM information_schema.tables WHERE table_schema = 'dpdp' AND table_name IN
    ('credential','custody','file_pack','firm_cred','panel_firm','panel_request','partner_sale',
     'ai_link','ai_link_read','ai_proposal','ai_proposal_line',
     'erasure_request','erasure_place','erasure_answer','task','email_token',
     'digest_send','inbound_message','independence_block')) AS new_tables_present_of_19,
  (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'dpdp' AND table_name = 'artefact' AND column_name IN
    ('proof_mode','storage_state','deleted_at','client_location','storage_path')) AS artefact_new_columns_of_5,
  (SELECT count(*) FROM information_schema.columns WHERE table_schema = 'dpdp' AND table_name = 'email_token' AND column_name = 'membership_id') AS email_token_has_membership_id,
  (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'dpdp' AND p.proname = 'projection') AS projection_function_exists,
  (SELECT count(*) FROM pg_trigger WHERE tgname = 'dpdp_email_token_membership_scope') AS membership_scope_trigger_exists,
  (SELECT count(*) FROM pg_policies WHERE schemaname = 'dpdp' AND tablename = 'obligation' AND policyname = 'app_runtime_obligation_read') AS auditor_write_fix_applied;
-- Expect: 19, 5, 1, 1, 1, 1 -- if every number matches, all 6 migrations
-- landed correctly. If any number is lower, tell me which one and stop --
-- do not re-run this file a third time without me looking at it first.

COMMIT;
