/// <reference types="bun-types" />
// The lawyer-review pack (dpdp-app/docs/LAWYER-REVIEW-PACK.md, lawyer-review-checklist.csv) is GENERATED by scripts/dpdp/gen-lawyer-review-pack.ts from the job
// library (scripts/dpdp/gen-library-seed.mjs), the playbook (supabase/functions/dpdp-ai-link/playbook-data.ts) and the law table (law.ts). This test is what keeps
// the committed copy honest: change any of those sources without regenerating and it fails, so counsel is never handed a pack that no longer matches the product.
// It also pins the two promises the pack makes about itself: it says NOT REVIEWED, and it ticks nothing on anyone's behalf.
import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { build, loadLibrary } from "../../../scripts/dpdp/gen-lawyer-review-pack"
import { citeLawCode } from "../../../supabase/functions/dpdp-ai-link/law"
import { PLAYBOOK_DATA } from "../../../supabase/functions/dpdp-ai-link/playbook-data"

const ROOT = join(import.meta.dir, "../../..")
const read = (p: string) => readFileSync(join(ROOT, p), "utf8").replace(/\r/g, "")

describe("lawyer review pack", () => {
  const built = build()
  const jobs = loadLibrary()

  test("the committed files are exactly what the generator writes now (run: bun scripts/dpdp/gen-lawyer-review-pack.ts)", () => {
    expect(read("dpdp-app/docs/LAWYER-REVIEW-PACK.md")).toBe(built.md)
    expect(read("dpdp-app/docs/lawyer-review-checklist.csv")).toBe(built.csv)
  })

  test("every library job appears once, in both files, and has a written playbook", () => {
    expect(jobs.length).toBe(59)
    expect(jobs.filter((j) => j.edition === "firm").length).toBe(31)
    expect(jobs.filter((j) => j.edition === "institution").length).toBe(28)
    for (const j of jobs) {
      expect(built.md.split(`##### \`${j.key}\``).length - 1, j.key).toBe(1)
      expect(built.csv.split(`"${j.key}"`).length - 1, j.key).toBe(1)
      expect(PLAYBOOK_DATA[j.key], `${j.key} has no playbook entry`).toBeDefined()
    }
    expect(built.stats.withPlaybook).toBe(59)
  })

  test("every law code the library cites is listed, with the product's own open 'verify' note when it has one", () => {
    const codes = [...new Set(jobs.flatMap((j) => j.law))]
    expect(built.stats.codes).toBe(codes.length)
    let open = 0
    for (const c of codes) {
      expect(built.md, c).toContain(`| \`${c}\` |`)
      const cite = citeLawCode(c)
      if (!c.startsWith("g:") && cite?.verify) {
        open++
        expect(built.md, c).toContain(cite.verify.replace(/\|/g, "\\|"))
      }
    }
    expect(built.stats.unconfirmed).toBe(open)
    expect(open).toBeGreaterThan(0) // as long as this is 0 the pack would claim nothing is left for counsel to confirm
  })

  test("it says NOT REVIEWED and leaves every box empty: an AI cannot sign for a lawyer", () => {
    expect(built.md).toContain("STATUS: NOT REVIEWED BY A LAWYER")
    expect(built.md).not.toMatch(/\[[xX✓✔]\]/)
    expect(built.md).not.toMatch(/reviewed by counsel on/i)
    // the sign-off row is blank
    expect(built.md).toContain("| | | | | |")
  })
})
